### ISSUE TITLE
Rename the "Update Metadata" button to "Save"

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1004]
This is within the Civiform Admin's form builder UI.

**Comment by baipai** [comment]
Is this page? The "add block" button? Or where is the "update block" button?

<img width="1268" alt="Screen Shot 2021-05-17 at 10 12 26 PM" src="https://user-images.githubusercontent.com/11348330/118507084-7c97d200-b760-11eb-8a75-ad4163fd6f7b.png">

**Comment by neel-a-mehta** [comment]
It would be the Update Metadata button in the middle of the screen.

**Comment by kendrickt** [comment]
This is related to https://github.com/seattle-uat/civiform/issues/995, and https://github.com/seattle-uat/civiform/issues/291.

We have almost no client-side anything on this page, and each button is pretty much its own form submission which will reload the page. That means if you add/remove questions or add a block or navigate to another block, the block name/description are lost.

We could put more client-side stuff in here to at least combine the question bank and block name/description into one big form.

We can't really do cross-block stuff without a ton more work. We could add a warning that pops up if you've changed anything without clicking "Save", and try to navigate away.

**Comment by baipai** [comment]
I see, maybe it is better to just stay on the same button name or will changing to “update” make more sense for now?

**Comment by neel-a-mehta** [comment]
Can we just have it say "Save Name and Description" to make it clearer without substantially changing the page? The word "metadata" might get confusing, and "save" might be clearer than "update."

**Comment by kendrickt** [comment]
It looks like this now. Is this ok?

![](https://user-images.githubusercontent.com/12072571/120533125-43cd3f00-c395-11eb-9436-db6ac806aa0a.png)
