### ISSUE TITLE
Make confirmation page once applicant finishes applying

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1009]
Gives them feedback that their application went through. Give them a confirmation code too (a unique ID for their application that they can share with the program admin).

**Comment by ndmckinley** [comment]
Is this to replace the confirmation toast after submission?

**Comment by neel-a-mehta** [comment]
Good question. Main thing we have to ensure is that the applicant sees that they successfully submitted the form, and that they get their confirmation code. So we have two options:

- Offer a persistent toast that includes a confirmation code (ideally with a "Copy" CTA); can only be dismissed by hitting X.
- Offer a standalone confirmation page that includes a "congrats" message and a confirmation code.

Not sure which one's easier to implement -- up to you!

**Comment by neel-a-mehta** [comment]
Nathan just put this in -- 

![image](https://user-images.githubusercontent.com/77128518/118311051-63bbc200-b4bd-11eb-86a0-824199eba8aa.png)

Looks good, only hitch is that there's still a toast (and it looks like an error message) -- can we get rid of it?

![image](https://user-images.githubusercontent.com/77128518/118311135-8057fa00-b4bd-11eb-9efe-7888706c6d6b.png)
