### ISSUE TITLE
Make error messages in the question creation form easier to see

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1010]
Right now there are just random strings printed out on the page. A box that lights up when there's an error (and lights up a different color if there's no error), and that clearly shows the error message, would be great.

**Comment by kendrickt** [comment]
Started in https://github.com/seattle-uat/civiform/pull/635

**Comment by kendrickt** [comment]
Closing because the error messages are no long just random strings printed out on the page.
