### ISSUE TITLE
Ensure applicant experience matches UX mocks

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1016]
[These are the mocks](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457357026339778&cot=14) on Miro, and [this Tailwind playground](https://play.tailwindcss.com/JzARWTvFQP?file=css) has the style guidelines we need. Let's make sure the applicant's UI/UX matches those.

Especially important is listing the program name on the top of the page, since many applicants might forget what they're applying for halfway through.

**Comment by neel-a-mehta** [comment]
cc @natsid @AWBaumann

**Comment by neel-a-mehta** [comment]
All right, here's the main Figma file (with styles, components, mocks, etc.) from the UX team: https://www.figma.com/team_invite/redeem/haR79GuC8VYA6BvL8xT6YE

cc @natsid @AWBaumann

**Comment by lianne-oy** [comment]
Done for basics; already have specific tasks that still need to be cleaned up.
