### ISSUE TITLE
Let TIs set the display language for a program form

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1032]
Feedback from the City of Seattle:

> Are TIs able to change the display language? Just thinking TIs might go through the application with a client sitting next to them (or over the phone). [Since it's easier for the TI to not have to translate from English to the client's language on-the-fly.]

I think applicants can set the language if they're applying, but that screen may be skipped if the TI is applying on a client's behalf. Instead, we should show that screen in *all* cases, including if the TI is applying.

**Comment by carolinedanzi** [comment]
Additional context: currently, once an applicant sets their display language, they cannot change it. We could fix that issue and this one by providing a link on the applicant overview page to change their language (this can use the existing `ApplicantInformationController`

**Comment by neel-a-mehta** [comment]
TIs can change the site language up top in the header bar when they're applying for a client.

![image](https://user-images.githubusercontent.com/77128518/123462232-e47edb00-d59e-11eb-89ae-a0c99233ae2d.png)
