### ISSUE TITLE
In form builder, let CiviForm admin refer to entity's name in repeated questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1049]
Suppose a CiviForm admin creates an enumerator question that asks, "Please list all your children." The applicant enters nicknames (i.e. "entity names") for each of their children: e.g. "Sherlock", "Joan", "Marcus". 

Then, when the applicant is filling out questions inside that enumerator block, they should be able to see the nickname of the entity they're entering details for. If there was a repeated Birth Date question, for instance, they'd see "Enter Sherlock's birth date", then "Enter Joan's birth date", then "Enter Marcus's birth date".

We need to create a feature that lets admins refer to the "enumerated/repeated entity name" in the names or descriptions of repeated questions. Perhaps we'd add a magic token like "$$" or "@@", which would be auto-replaced with the current entity name. So the question builder UI might look something like this:

![image](https://user-images.githubusercontent.com/77128518/117473539-158c4900-af28-11eb-889c-640d018b8c28.png)

I'm guessing we'd want to show some help text explaining to the user how to use this magic token (and only surface it if the "Question Enumeration" field is non-null).

**Comment by neel-a-mehta** [comment]
cc @kendrickt

**Comment by kendrickt** [comment]
Ready for story acceptance

**Comment by kendrickt** [comment]
The magic tokens are

$this
$this.parent (for a nested repeated entity's parent)
$this.parent.parent (ad infinitum for deeply nested repeated entities)

**Comment by neel-a-mehta** [comment]
Great! Thanks. Will review.

**Comment by neel-a-mehta** [comment]
Hey, that looks nice!

![image](https://user-images.githubusercontent.com/77128518/118739158-50d32580-b80e-11eb-8cd1-d65fac43c350.png)

Had a couple UX comments so I might make a separate issue for that, but this is approved!
