### ISSUE TITLE
In form builder, alert CiviForm admin that the form is saved when they add/remove a question

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1050]
The mental model for the form builder is a bit inconsistent: you have to hit "Update"/"Save" to commit changes to the block name or description, but adding or removing a question (and I think a block) is automatically saved. The latter situation is fine, but we should alert the user that their data is auto-saved. Either have a toast (though that could get annoying), or have a subtle "Saved at [time]" message at the top, kind of like Google Docs does.

**Comment by kendrickt** [comment]
Related to #291 and #995

**Comment by kendrickt** [comment]
[DUPLICATE #995] 

Solution: every action on this page is an atomic form submission, so we'll make the block name/description edit atomic by using a modal that forces the admin to save it. Then everything on this view will behave the same.
