### ISSUE TITLE
Document i18n processes

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1055]
There are two translation processes:

1. Translation of admin-configurable resources including question and program definitions. This is done using the admin UI and does not require code changes.
2. Translation of hard-coded CiviForm UI. This is done using Play Framework's i18n libraries and requires code changes + deployment.

@carolinedanzi is the expert for 2.

**Comment by carolinedanzi** [comment]
Updated https://github.com/seattle-uat/civiform/wiki/Internationalization-(i18n) to describe the two different localization processes

**Comment by lianne-oy** [comment]
Done but needs review... Bion to review.
