### ISSUE TITLE
Document CBO/Trusted Intermediary management

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1056]
Provide user-manual type documentation for how the CiviForm admin manages trusted intermediary organizations and accounts within those organizations inside the tool.

**Comment by lianne-oy** [comment]
Draft [here](https://docs.google.com/document/d/15KS8I4BcJTcHjfLIWuSkUCvuFoW_n8wg1Zg51QCj4X8/edit#heading=h.15u4z22srwai)
