### ISSUE TITLE
"File upload" question type: Limit default uploads to images and PDFs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1067]
Right now from #404, the File Upload question type lets you upload any file type you want. From #423 we know that we want to limit the types of files people can upload to just images and PDFs (so GIF, JPG, PNG, PDF). #423 will let admins change these rules, but allowing only those 4 types seems like a reasonable default. 

Note that this limitation is more for the benefit of novice users. A sophisticated prankster can always change a file's type to one of these 4 (or hide something irrelevant in a PDF), but we're not trying to address that here. We just want to help novice users know what they can, and can not, submit.

**Comment by neel-a-mehta** [comment]
cc @hmhsu

**Comment by neel-a-mehta** [comment]
Testing on desktop:

- Visit a File Upload question
- Try uploading a file. Notice that the file browser filters out non-image, non-PDF files - PASS.
- Try to forcibly upload an Excel file anyway (turn off filtering on the file browser) => the system lets me do it! - NO PASS.

Can we add some server side checking to ensure that only images and PDFs are uploaded? The `<input accept="...">` technique *suggests* that the applicant only upload these file types, but it doesn't mandate it. On my Chromebook at least, I could bypass that.

**Comment by hmhsu** [comment]
Thanks for finding the bypass issue.  There isn't a built-in way to do this on the AWS side so the best we can do is to check the file extension, probably easier at client side. Given that this is to help guide the users to upload the right types of files, I'd think this is good enough. Agreed that certainly more can be done to improve this.
