### ISSUE TITLE
Let admins change a question's enumeration/repeat status after it's created

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1091]
Once I create a question, I can't go back and change whether it's repeated. I just ran into this problem while testing -- I made a question that I wanted to repeat, but I forgot to set it while editing, and now I can't go back and change it.

If we can't fix the root problem, a workaround is to inform the user that a question's repeating settings can't be changed after it's created. Ideally we'd add a button to let someone clone the question and start creating a new one with new repeater settings. 

Or we could make this less of a big deal by letting admins delete/archive questions (#997).

**Comment by kendrickt** [comment]
If admins "move" repeated questions around, they will lose the references to already existing applicant data. This is also why we don't allow renaming of questions.

I think the "copy" question button is super useful.

**Comment by neel-a-mehta** [comment]
Ah, that makes sense. #1187 covers renaming; good catch that that would be difficult.

I'll make an issue for copying a question -- that seems to be an easy workaround to the thorny problems surfaced here.

**Comment by neel-a-mehta** [comment]
It sounds like cloning is a better move since changing enumeration status would mess up too many things. Closing this.
