### ISSUE TITLE
On applicant homepage, show last applied date / # questions answers / # questions left

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1105]
Each program gets its own "card" on the applicant homepage. On that card, there's an "Apply" button. We should also add some text that says the last time the applicant submitted an application for that program (in that case, the button should probably say "Re-Apply" instead).

You can also show the number of questions the applicant has left before they're done with the program, and show the status of which programs are complete / in progress.

This is especially important for TIs, who have to juggle many different clients and need to remember which programs they currently had in progress.

**Comment by neel-a-mehta** [comment]
- How many questions are completed
- How many questions are left
- Whether you've submitted the form yet
- If you submitted it, when did you last submit

**Comment by kendrickt** [comment]
I'm concerned with deceiving % complete messages because with enumerators, it can blow up very quickly.

Though once you've added the common enumerators (children, household members, etc), then it should be more accurate.

**Comment by neel-a-mehta** [comment]
Yeah, that's a good point -- enumerators make the percent complete indeterminate. Perhaps we can just show "Not Started / In Progress / Complete"?

**Comment by UXDESIGNNAM** [comment]
Hi Holly. Can you assign me to this pls?
