### ISSUE TITLE
Add a dialog for confirming deletion of enumerator entities

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#1117]
**Is your feature request related to a problem? Please describe.**

From @kendrickt on #1110:

> Problem: Applicant cannot un-delete an entity.
> Solution: add a warning to verify with applicant that they want to delete it. This can include a message about needing to click save and continue to actually persist these changes.

**Done when**
When an applicant clicks the remove entity button, a dialog pops up to warn them that they are about to delete the entity

**Comment by WaterLily** [comment]
I'd like to work on this one (I checked on slack about it).
