### ISSUE TITLE
Document trickier parts of `Play` framework forms.

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#1121]
We should make a new wiki section (possibly its own wiki page) for documenting working with forms in `Play`. Should live under the "Developer guide" section of the CiviForm wiki.

The `Play` framework has some amount of existing documentation, but it doesn't cover some trickier/edge cases. The new wiki section should link out to these docs:
* https://www.playframework.com/documentation/2.8.x/JavaForms
* https://www.playframework.com/documentation/2.8.x/JavaFormHelpers

And should also expand on:
* lists
* optional numbers
* [anything else?]

**Comment by lianne-oy** [comment]
Will do in final week

**Comment by carolinedanzi** [comment]
Started a Wiki doc here: https://github.com/seattle-uat/civiform/wiki/Form-Submission-with-Play
