### ISSUE TITLE
Enumerator question deletions aren't staged properly

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1135]
**Describe the bug**
In `ApplicantService#stageAndUpdateIfValid`, enumerator question deletions are not staged properly. This means if it is invalid, the deletions are lost to the void, and then very unexpected behavior can happen.

**To Reproduce**
1. Publish a program with an enumerator question, and a repeated question. (the ete enumerator program from browser tests can be used)
2. Create an "a" and "b" repeated entity, and then answer the repeated question with a different answer for "a" and "b".
3. Go back to edit the enumerator block
4. click the delete button for "a", > delete the string in the input field for "b" > save and continue
5. You should still be in the enumerator block, but there's an error that says "please fill in values for each row". Now fill in "c", and save and continue.
6. Make your way back to the summary review page

**Expected behavior**
Based on the user input, "a" should be deleted, and "b" should be renamed to "c".

However, the result is "a" is renamed to "c".

**Problem**
Enumerator deletions are not "staged", which means the state of the repeated entities after an invalid staging does not match what is stored, which means when the updates are finally valid and persisted, the outcome will not match what the user expects.

**Comment by carolinedanzi** [comment]
Discussion in standup: perhaps for this question, client-side validation would work best. Validation criteria:

1. No blank entity names
2. All entity names are unique

**Comment by kendrickt** [comment]
I think i18n and testing is gonna be tricky with javascript.
