### ISSUE TITLE
Minify `tailwind.css` and remove unused CSS classes

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1147]
## Problem

Google Lighthouse reports a lot of problems with our `tailwind.css` file, which weighs in at 4.5 MB. Some of the errors:

![image](https://user-images.githubusercontent.com/77128518/118337026-e144f980-b4e0-11eb-96b2-bb222521030e.png)

![image](https://user-images.githubusercontent.com/77128518/118337054-eb66f800-b4e0-11eb-84e3-f6e8dd39621a.png)

![image](https://user-images.githubusercontent.com/77128518/118337075-f6ba2380-b4e0-11eb-8083-5bbb8bffde96.png)

## Solution

Find a way to remove unused classes from Tailwind, and/or minify the CSS file to get the size down. [Tailwind has some helpful docs](https://tailwindcss.com/docs/optimizing-for-production) we may want to use.

**Comment by neel-a-mehta** [comment]
cc @natsid @AWBaumann in case you know how to do it (not urgent, but we'll want to do it eventually)

**Comment by ndmckinley** [comment]
(I did this)
