### ISSUE TITLE
Toasts should have a dismiss button instead of disappearing automatically

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#1177]
Currently our toasts disappear after a timeout, and it doesn't seem to be enough time for our users to read the message.

Would be a better experience to leave the toast up until the user dismisses it.

**Comment by AWBaumann** [comment]
That's already configurable. By default, a toast message will close after 3 seconds. If you set the duration to <= 0 then it'll remain visible until dismissed by the user.

**Comment by neel-a-mehta** [comment]
Relatedly, we might not want to show the toast at all for when the applicant submits a program form, since we'll already be showing them a confirmation page (#1139).

**Comment by natsid** [comment]
I'm going to close this because as @AWBaumann mentioned above:

>  If you set the duration to <= 0 then it'll remain visible until dismissed by the user.

Since the description doesn't mention the specific places where this should be changed, it's difficult to act on this task explicitly. But since the functionality already exists, it should be simple to add if/when a user reports a specific place where this should be updated.
