### ISSUE TITLE
Handle program description text overflow

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#1180]
Do something more graceful than this:

![Screen Shot 2021-05-17 at 4 49 52 PM](https://user-images.githubusercontent.com/5732310/118571528-252f3d00-b733-11eb-903d-edb3cf3bad3f.png)

Add scrolling ? Though this solution probably won't work well on mobile.

**Comment by AWBaumann** [comment]
We should be using this:
https://blog.tailwindcss.com/multi-line-truncation-with-tailwindcss-line-clamp

**Comment by natsid** [comment]
Thanks, Aaron! Didn't know about line clamp. I think that will come in handy. I think that will require a little more UX work to figure out what the expansion story is, especially on desktop (if we use this strategy for desktop). On mobile, I think it requires less design work since there is only ever one column of cards, meaning that expanding one doesn't impact an whole row of other cards.

In the meantime, I've implemented this using flex and `overflow-auto` to get a scroll bar when one is needed. Like I mentioned in the issue description, scrollbar isn't a _great_ experience on mobile because it's not very obvious that there's something to scroll there (I don't think the scrollbar is visible). This seems like an OK fix for now though.
