### ISSUE TITLE
Use "remove" instead of trashcan icon in enumerator view

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1189]
User feedback from testing:

> the trash can for removing enumerated entities isn't very obvious, should probably use a word e.g. "remove"

![image](https://user-images.githubusercontent.com/77128518/118726885-8d475700-b7f7-11eb-9247-7381e6ce18e9.png)

We should change that trash-can button to say "Remove", or at least have the trash can icon *plus* the word "Remove".

**Comment by kendrickt** [comment]
Closed by #1182
