### ISSUE TITLE
XML error when you don't submit file to File Upload question

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1210]
I was applying for a program and saw a File Upload question. I skipped the question (by hitting Next without uploading anything) and got this XML error. Ideally we'd get a more user-friendly error message in the UI.

![image](https://user-images.githubusercontent.com/77128518/118866610-c939f500-b8a7-11eb-96ba-d3f7b60c0067.png)

**Comment by natsid** [comment]
Relaying discussion around this from standup today:

We talked about how the `submit` (AKA "Next") button on a file upload block directly uploads to AWS. We think a good plan is to disable the "Next" button until/unless a file is uploaded. If a file is never uploaded, we should provide a "skip" button that allows a user to not upload a file.

**Comment by neel-a-mehta** [comment]
The fix works (adding a Skip button) but we still need to hide or gray out the Upload button until the applicant uploads a file. Until then, the Upload button will still cause an XML error when clicked before a file is uploaded.

**Comment by neel-a-mehta** [comment]
OK, the Upload button now cannot be submitted until a file is uploaded!

![image](https://user-images.githubusercontent.com/77128518/123314514-8939e380-d4df-11eb-9247-6db62ac42a24.png)
