### ISSUE TITLE
Record applicant's language in the downloaded CSV

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1220]
One program admin requested this feature. When an applicant applies for a program, they have to specify a language that they'd like to fill it out in: English or some other language.

The program admin wants this chosen language to be shown in the downloaded CSV somewhere (and, I would assume, in the list of submitted applications too). Can we add a column for "chosen language for this program"?

**Comment by lianne-oy** [comment]
Should be easy per bion - adding to milestone 9

**Comment by hmhsu** [comment]
Reopen for story acceptance.

**Comment by neel-a-mehta** [comment]
It works now!

To test, I created a program that was fully translated into Spanish and used only questions that were translated into Spanish. Then I applied as a guest with Spanish chosen as my language, then again with English. Looks like both my language choices were shown:

![image](https://user-images.githubusercontent.com/77128518/122267531-db4f8900-ce8f-11eb-86fd-389f8ce6e52f.png)

**Comment by neel-a-mehta** [comment]
So everything works when translated!
