### ISSUE TITLE
In applicant view, dropdown questions don't have a "null" (default) state

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1244]
Ideally these dropdowns would have a "null" state like "Choose an option:" before any of the real options show up. This lets the applicant see when they haven't answered the question, instead of defaulting to the first option.

In this screenshot, I would expect to see "Choose an option:" before "abc", "def", and "ghi".

![image](https://user-images.githubusercontent.com/77128518/119186193-5cf0fa00-ba3d-11eb-9360-a268a0ff1876.png)

![image](https://user-images.githubusercontent.com/77128518/119186234-6b3f1600-ba3d-11eb-9ee6-cbc8a3781afc.png)

**Comment by lianne-oy** [comment]
Relatively small - may be able to do per bion

**Comment by WaterLily** [comment]
I'd like to work on this one if I may.

**Comment by neel-a-mehta** [comment]
@WaterLily -- sure, I would just ask on the #engineering channel on Slack! ([Slack joining instructions](https://github.com/seattle-uat/civiform/wiki/Contributing) in case you need them)
