### ISSUE TITLE
If user has already answered questions, pre-fill those questions instead of skipping questions entirely

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1245]
## Background

Currently, we automatically skip questions and blocks that have already been answered by the applicant. For instance, if the applicant answered "What is your home address?" in an earlier form, and they come to a new form that includes the same question, that question would be skipped.

This is in line with the original project vision, though it comes with some drawbacks:

- It's unpredictable: when you start a program, you have no way of knowing ahead of time what questions you'll actually see.
- If two people pull up the same form, they may not see the same questions, given that they might have answered different questions in the past. That might confuse people.
- If you want to edit answers to questions you answered before, you'd miss the question when you're stepping through the form. You'd have to use the Review page to jump to the question (which would be confusing because the question would have never appeared to you before). This kind of jumping around introduces confusing non-linearity to the user journey, and keeping the user journey linear is going to be very important, especially for applicants who aren't very experienced with filling in forms.
- Show/hide logic gets really messy when you're skipping questions.
- Next/back logic gets confusing (can you Back your way into a previously-hidden question?)

## Proposal 

To keep the UX simple and create a simpler mental model for users, the easier alternative is to always show every question and block, even if it's already been answered -- except you prefill every question that's already been answered. This is, incidentally, exactly how [TurboTax does it](https://uxdesign.cc/https-medium-com-ux-ui-analysis-of-turbotax-171c86d80a41) -- show every question for simplicity, but prefill things when possible.

This has several advantages:

- It's more predictable
- It avoids any weirdness around next/back logic and show/hide logic
- It lets the form be purely linear, which is easier to reason about
- It lets applicants check over all the information they put in as they go
- It shows our value proposition more obviously; the user thinks, "wow, look at all this stuff that was prefilled for free for me!"

## Action

For this issue, keep the review page around, and continue to let applicants jump around between questions. However, instead of skipping already-answered questions, just show them, but pre-fill the input fields

Potential UI improvements that can help this change be easier to understand:

- Give pre-filled fields a different color, or some other visual indicator that they're already filled
- Add a big "SKIP" button at the top of the page if the entire block has been pre-filled. This lets the applicant quickly skip over things they've already filled, freeing them from having to scroll down and check every single question before they move on. This would enable a more snappy feeling of filling out the form. (Who doesn't love the feeling of flying through a big form?)

## Notes 

While this move has advantages, it's not exactly what the City had asked for, so we'd probably want to make it a feature we can toggle on/off in code (or at least leave the earlier behavior around in case we want to bring it back).

**Comment by neel-a-mehta** [comment]
cc @natsid @AWBaumann @carolinedanzi in case you had anything to add here

**Comment by neel-a-mehta** [comment]
I think we've done this now

**Comment by ekalstad** [comment]
@ldinhcos -- can you review to see if this is actually closed? Sounds like it's still an issue.

**Comment by ldinhcos** [comment]
This is still an issue.
