### ISSUE TITLE
Merge the confirmation page & account upsell after applicant submits form

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1246]
Right now, when the applicant submits a form, they first see a screen that upsells them to create a new account:

![Screenshot 2021-05-21 2 03 15 PM](https://user-images.githubusercontent.com/77128518/119198396-e1984400-ba4e-11eb-937f-44a0ca7a68ad.png)

Only after that do they see the confirmation code:

![Screenshot 2021-05-21 2 03 23 PM](https://user-images.githubusercontent.com/77128518/119198407-e5c46180-ba4e-11eb-953e-93dc8f4bbb2a.png)

This is a bit confusing, since when the applicant sees the upsell screen, they might not be sure if their application has gone through!

The best solution would be to merge the 2 screens. Show the confirmation code at the top of the screen, then the upsell stuff below it. The pages are pretty light on content, so even merged, they won't be too heavy.

**Comment by lianne-oy** [comment]
Out for review @neel-a-mehta

**Comment by neel-a-mehta** [comment]
Works! 
![image](https://user-images.githubusercontent.com/77128518/121081312-8f735480-c7aa-11eb-9ce0-8d6a974f7cfd.png)

**Comment by natsid** [comment]
Oops - thanks @neel-a-mehta ! Didn't mean to close before story acceptance!
