### ISSUE TITLE
Instead of saying "Create New X", say "Create X" or "New X"

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1249]
UX writing best practices say that "Create New X" is redundant -- you can never create an old thing! So wherever we say "Create New X", we should simplify it to say just "Create X" or "New X".

**Comment by danger-ahead** [comment]
Hi, I can help, please assign me.

**Comment by neel-a-mehta** [comment]
Hi @danger-ahead , want to ask on the #engineering channel on Slack about this issue?
