### ISSUE TITLE
Alphabetize all languages besides English

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1253]
Per #901, we support 7 "Tier 1" languages besides English:

> Traditional Chinese*, Spanish, Vietnamese, Somali, Amharic, Korean, Tagalog

To avoid any sense of "preferring" one over the other, we should alphabetize all the languages except English throughout the UI. So the ordering we use would be:

1. English
1. Amharic
1. Chinese
1. Korean
1. Somali
1. Spanish
1. Tagalog
1. Vietnamese

This would show up throughout the CiviForm admin's translation UI, and in the applicant's UI where they choose a language for the app.

**Comment by Shobha-go** [comment]
Please assign this issue to me, I will work on this task.
