### ISSUE TITLE
Remove a block with nested block throws a server error

### ISSUE THREAD

**Issue by hmhsu** [seattle-uat/civiform#1259]
**Describe the bug**
Removing an enumerator block with existing nested blocks throws an error

**To Reproduce**
1. Create an enumerator question
2. Create a nested enumerator question
3. Add a new program and add both enumerator questions
4. Add a nested repeated block in the nested enumerator block (See picture below)
5. Delete block with a repeated block in it (block 2 in the picture)
6. See server throws an error

**Expected behavior**
The repeated block(s) should be deleted along with the enumerator block.

**Screenshots**
![Screen Shot 2021-05-21 at 10 03 43 PM](https://user-images.githubusercontent.com/2597580/119215167-d1995800-ba80-11eb-8631-f66633ed3962.png)

**Comment by hmhsu** [comment]
cc @kendrickt

**Comment by hmhsu** [comment]
I think one enumerator block with nested repeated block also has this problem.

**Comment by kendrickt** [comment]
This looks good to me. Enumerator blocks have a disabled `Delete Block` button when they have repeated blocks:
![image](https://user-images.githubusercontent.com/12072571/120521288-a0c2f800-c389-11eb-8000-41e24b6467c6.png)

and when they don't have repeated blocks the button is enabled:
![image](https://user-images.githubusercontent.com/12072571/120521381-be905d00-c389-11eb-812d-54dd46f71c3d.png)

And all other blocks have an enabled `Delete Block` button.
