### ISSUE TITLE
Updating an enumerator question breaks Civiform

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1290]
**Describe the bug**
When an enumerator question gets a new draft, its repeated questions do not update their `enumerator_id` references. This means we have active or draft repeated questions referencing inactive enumerators.

**To Reproduce**
1. Create an enumerator question
2. Create repeated questions
3. Create a program that uses the enumerator and repeated questions
4. Publish all programs
5. Update the enumerator question

**Expected behavior**
We expect the new drafts of repeated questions, which have updated references to the new draft of the enumerator question. We expect this effect to chain into nested enumerator questions and their repeated questions.

**Comment by kendrickt** [comment]
# Fix for the future
Trigger new drafts of repeated questions (if the draft doesn't already exist), and update the enumerator id reference to the enumerator draft that was just created. 

This was fixed in #1256 

# Fixing the DB
We broke glass on the production database and manually updated the enumerator references:

> `postgres=> update questions set enumerator_id=162 where enumerator_id=92;`

Alternatively, we could have deleted the new enumerator question and promoted the previous version to active/draft and make the city reapply the updates after the fix.

# Part 2
The problem resurfaced on the week of June 1st. We broke glass again and fixed the enumerator id references. 

#1256 has browser tests that makes checks that the problem shouldn't come back, but it did. Two possibilities:
1. This could have been an artifact of a draft that existed before the #1256 fix was pushed to prod.
2. This may possibly be a problem with database transactions.

We will continue to monitor, in case this is a database transaction problem.

# Rollbacks
The changes we manually applied to the database probably messes up rollbacks for the two versions it affected. @ndmckinley is looking into a way to fix the rollbacks.

**Comment by ndmckinley** [comment]
Also addressed a lingering data cleanliness issue by adding the enumerators that are referred to by the new questions to all the old versions that the old questions are in.

```
INSERT INTO questions_versions
            (questions_id,
             versions_id)
(SELECT DISTINCT q2.id AS questions_id,
                 v1.versions_id
 FROM   questions q1
        JOIN questions q2
          ON q1.enumerator_id = q2.id
        JOIN versions_questions v1
          ON v1.questions_id = q1.id
 WHERE  NOT EXISTS(SELECT 1
                   FROM   versions_questions v2
                   WHERE  v2.versions_id = v1.versions_id
                          AND questions_id = q2.id)); 
```

It has occurred to me that this has produced ANOTHER data cleanliness issue - or the risk of one at least - that a rollback would now create multiple questions with the same name... i will look into that now.

**Comment by ndmckinley** [comment]
Yep, addressed that with
```
UPDATE questions
SET    enumerator_id = 144
WHERE  enumerator_id = 84;

DELETE FROM versions_questions
WHERE  ( questions_id = 84
          OR questions_id = 92 )
       AND ( versions_id = 10
              OR versions_id = 11
              OR versions_id = 12
              OR versions_id = 13
              OR versions_id = 14 ); 
```
got the values to delete from
```
SELECT DISTINCT q1.id          AS old_q,
                q2.id          AS new_q,
                v1.versions_id AS version
FROM   versions_questions v1
       JOIN versions_questions v2
         ON v1.versions_id = v2.versions_id
       JOIN questions q1
         ON v1.questions_id = q1.id
       JOIN questions q2
         ON v2.questions_id = q2.id
WHERE  q1.NAME = q2.NAME
       AND q1.id < q2.id
ORDER  BY version; 
```

**Comment by hmhsu** [comment]
For the record, we ran below SQL on May 21 to address part one of this issue.

```sql
UPDATE  questions
SET     enumerator_id = 144
WHERE   id IN (SELECT   DISTINCT questions_id
               FROM     versions_questions
               WHERE    questions_id IN (SELECT DISTINCT id
                                         FROM   questions
                                         WHERE  enumerator_id = 84)
                 AND    versions_id > 14);
```
