### ISSUE TITLE
CiviForm admin can download a CSV of applicant data for allow-listed questions

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1303]
Decision-makers at the city need a way to analyze demographic data about residents applying for various programs.

- [ ] CiviForm admin can check a checkbox on questions indicating they should be included in the bulk demography export. The checkbox is unchecked by default i.e. questions are not included in the export by default.
- [ ] CifiForm admin can download a CSV that includes all applications for all applicants with an opaque (e.g. hashed) applicant ID including only the data for checked questions

**Comment by neel-a-mehta** [comment]
Note from Elise: this is for demographic data but *also* some of the answers themselves. PII has to be removed, of course. This is so the city can get high-level data on the types of applications coming in for each program.

**Comment by neel-a-mehta** [comment]
From the City, this is an example of the data they'd like to be able to export:


| Applicant ID | CBO | TI Who Assisted | Created Time/Date | Completed Time/Date | Program Applied For  | Income (monthly) | People in household | Language | Ethnicity | Race | Gender | Zip Code | How did you hear about the program? |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 33555 | CISC | Sandra Smith | 5/19/2021 09:00AM | 5/19/2021 10:00AM | ORCA YOUTH OPPORTUNITY |  $1,000.00  | 4 | English | Caucasian | White | Female | 98144 | Seattle.gov |
| 33555 | CISC | Sandra Smith | 5/19/2021 09:00AM | 5/19/2021 10:00AM | Parks Scholarship Program |  $1,000.00  | 4 | English | Caucasian | White | Female | 98144 | Seattle.gov |

**Comment by neel-a-mehta** [comment]
> How rigorously should I read that? We export TI emails, for instance, and not TI groups. We also don't have both creation and completion time, only one of those, iirc.

I think we talked about this over video-call, but just so we have it in writing: don't worry too much about matching this format exactly. Let's just provide all the data we have access to, and optionally make issues to request gathering/storing data that we don't currently have (such as creation time).

**Comment by neel-a-mehta** [comment]
Testing:

- Create new program
- Add some questions: address, date, email
- Edit address Q to be exportable
- Edit date Q to be obfuscated
- Leave email Q as not exportable (default)
- Publish
- Apply as applicant a few times
- Log in as CF Admin again
- Hit Download Exported Data
- Here's the CSV

[demographics-2021-06-14T18_55_14.288873Z.csv](https://github.com/seattle-uat/civiform/files/6650622/demographics-2021-06-14T18_55_14.288873Z.csv)

- Address question data shows up as expected
- See no email data, as expected
- Date is obfuscated, as expected

Approved!
