### ISSUE TITLE
On guest applicant upsell screen, let them Log Out and expire session immediately

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1306]
In #1292 we discuss the importance of expiring guest users' sessions. This is important because many applicants will use CiviForm on public computers as guests, and we don't want future applicants to be able to see their data. #1292 implements automatic expiration after a certain number of hours. Here, we want to let applicants forcibly expire their sessions when they know they're done.

For this, add a 3rd button to the upsell page that guests see after they fill in an application. We already show them a button to continue as guest and a button to create an account. Add a 3rd button that lets them log out and clear their session, indicating they're done working with CiviForm on this computer.

From @natsid : 

> The new solution is to add a third button to the "upsell screen" (which is soon to be combined with the confirmation screen). The third button will say something along the lines of "I'm all done!" and will essentially be a logout button.
> The other two buttons will have the same behavior as today: signin/create account and "not right now / fill out another app" which would take you to the program list page.

**Comment by natsid** [comment]
Reopening this for story acceptance review.

**Comment by neel-a-mehta** [comment]
This screen appears:

![image](https://user-images.githubusercontent.com/77128518/121262224-c4060f80-c881-11eb-808c-4fae1de643e5.png)

And when clicked, it logs the user out and goes back to the login form. Great!

Wording above might need a little work, since it doesn't explain the logout option at all. But I'll make a different issue for that.
