### ISSUE TITLE
Let CiviForm admins specify questions as optional or required

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1307]
Spinoff of #1001 . We want to let CiviForm admins, when building program forms, specify individual questions as Required or Optional. Don't have any fancy logic here -- just store a simple true/false flag of whether or not the question is required.

Tasks:
1. Make all questions capable of recording a `visited but unanswered` state. Namely, the file upload question needs this.
2. Create a `bool optional` field in `ProgramQuestionDefinition` and let admins set that field on questions in blocks.
3. Update all `isComplete` methods to use the new `bool optional` field.

**Comment by kendrickt** [comment]
With this feature enabled we'll have five states for each answer:
1. unvisited
2. visited but unanswered in the past (for optional questions)
3. visited and unanswered in current program (for optional questions)
4. answered in the past
5. answered in current program

How will `visited but unanswered` be treated in determining whether blocks are complete? 

Proposal: treat `visited and unanswered in previous programs` as incomplete, and `visited and unanswered in current program` as complete.

**Comment by neel-a-mehta** [comment]
> Proposal: treat `visited and unanswered in previous programs` as incomplete, and `visited and unanswered in current program` as complete.

I'm good with this.

**Comment by lianne-oy** [comment]
Ensuring all question types are treated consistently but will not turn on before fellowship ends b/c has potential to create bugs; better for next team to turn on.

**Comment by neel-a-mehta** [comment]
#1452 built this feature but hid it behind a feature flag. A future team will want to enable the feature and check for bugs or unintended behavior. Leaving open until then.

**Comment by neel-a-mehta** [comment]
#1423 does the applicant-facing UX for this.

**Comment by kendrickt** [comment]
Once #1417 is done for required questions, we can move on to optional questions:

**Comment by kendrickt** [comment]
For enumerator and multi-select questions, required (default) means:
* enumerator questions need at least one repeated entity
* multi select questions must have at least one selection

**Comment by leonwong** [comment]
Just capturing what we discussed in standup - next steps here are to figure out what's broken/missing so we can discuss priority in triage and farm out more focused tasks to the rest of the team. From other discussions, some combination of the following might be issues:

- Client-side optional/required validation not aligned with server-side 
- No indication to the applicant which questions are required vs. optional
- Admin controls over whether questions are optional/required are missing

I believe some of this code is written (e.g., see #1550) but not merged since the e2e wasn't complete, so it might be helpful to assess where we stand both with and without this PR merged.

**Comment by baipai** [comment]
Also relative to #1405 and #1407.

**Comment by lindsayzad** [comment]
Other related issues: #1423 .  Opened

Before checking in #1550, we should have new browser tests that cover
1. A new browser test that includes all types of questions (name, address, checkbox, enumerator, etc) where all are optional, all are left empty, and the form can still be submitted
2. An optional question that was visited but unanswered in a previous program that still pops up in the following program

Once we verify these two situations, we should be able to confidently flip the feature flag and merge #1550
