### ISSUE TITLE
Browser test flake - failed program/question creation

### ISSUE THREAD

**Issue by hmhsu** [seattle-uat/civiform#1309]
**Describe the bug**
The latest attempt to deflake browser test #1305  didn't fully fix our prod promotion. We have issue when we create a new question or program, somehow the browser test still stays on the create form page.

**Error message**
Program creation:
```
FAIL browser: chromium src/admin_program_translation.test.ts (48.774 s)
  ● Admin can manage translations › create a question and add translations

    expect(received).toEqual(expected) // deep equality

    Expected: "All programs"
    Received: "New program information"

      15 |
      16 |   async expectAdminProgramsPage() {
    > 17 |     expect(await this.page.innerText('h1')).toEqual('All programs');
         |                                             ^
      18 |   }
      19 |
      20 |   async expectProgramExist(programName: string, description: string) {

      at AdminPrograms.<anonymous> (src/support/admin_programs.ts:17:45)
      at step (src/support/admin_programs.ts:33:23)
      at Object.next (src/support/admin_programs.ts:14:53)
      at fulfilled (src/support/admin_programs.ts:5:58)
```
Question creation:
```
FAIL browser: chromium src/admin_program_creation.test.ts
  ● Create program with enumerator and repeated questions › create program with enumerator and repeated questions

    expect(received).toEqual(expected) // deep equality

    Expected: "All Questions"
    Received: "New address question"

      16 |
      17 |   async expectAdminQuestionsPage() {
    > 18 |     expect(await this.page.innerText('h1')).toEqual('All Questions');
         |                                             ^
      19 |   }
      20 |
      21 |   async fillInQuestionBasics(questionName: string,

      at AdminQuestions.<anonymous> (src/support/admin_questions.ts:18:45)
      at step (src/support/admin_questions.ts:33:23)
      at Object.next (src/support/admin_questions.ts:14:53)
      at fulfilled (src/support/admin_questions.ts:5:58)
```

See full error message here https://github.com/seattle-uat/civiform/runs/2765182536?check_suite_focus=true

**Expected behavior**
The tests pass without errors, i.e. the creation succeeds and returns back to program/question list page.

**Additional context**
We recently found out that sometimes page may not be fully loaded (especially javascript) before the browser tests start interacting with the page. This *may* be also caused by such timing issue and adding additional wait guard *may* solve it. More investigation needed though.

**Comment by hmhsu** [comment]
This is still relevant. The issue still happens from time to time today.

**Comment by leonwong** [comment]
Sadly, prober job still seems flaky around navigation from address question to the main questions page even after my last PR... Will continue digging to come up with another theory....

**Comment by leonwong** [comment]
Seeing some evidence that this might be an underlying playwright flakiness (perhaps similar to https://github.com/microsoft/playwright/issues/5460). In the example below, during radio button question creation, the newly created input element is visible, but the fill operation to enter text fails. The behavior is non-deterministic, but certain spots in our tests seem particularly prone.

  pw:api <= page.click succeeded +0ms
  pw:api => page.isVisible started +0ms
  pw:api   checking visibility of ":nth-match(#question-settings div.flex-row, 1) input" +2ms
  pw:api <= page.isVisible succeeded +2ms
  pw:api => page.fill started +0ms
  pw:api waiting for selector ":nth-match(#question-settings div.flex-row, 1) input" +1ms
  pw:api   "load" event fired +26ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "networkidle" event fired +503ms
  pw:api <= page.fill failed +3s

In case it helps w/future debugging efforts, turning on debug logging and running locally seems to repro issues a bit more reliably.

**Comment by leonwong** [comment]
Figured out the root cause. PR in progress.
