### ISSUE TITLE
Error thrown when program admin tries to download PDF of application

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1313]
I created a program that asks for a file upload. I had an applicant go through and add a file, then submitted. When I went in as a program admin to download a pdf of their submission, I got an error. 

![image](https://user-images.githubusercontent.com/77128518/121082380-02c99600-c7ac-11eb-88fe-5096f83b97e2.png)

Not sure if this is because of my file upload or if PDF download doesn't work across the board.

**Comment by ndmckinley** [comment]
Because of PDF download not working - but it should be hidden already...
