### ISSUE TITLE
Let CiviForm admin download CSV showing applicants' demographics and which programs they applied to, for open data portal

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1337]
The City of Seattle wants to create an open dataset of applicants' demographics and which city programs they've applied for. This data will be uploaded to the City's open data portal (https://data.seattle.gov/), where CBOs, researchers, city officials, and civil servants nationwide will be able to use it to improve the services offered to residents and find new residents to advertise benefit programs to.

Like in #1303, we should let the CiviForm admin download a CSV like this. The City will take care of posting it to the portal every so often.

What the data export should include:

> De-identified data (only return if there are more than 5 people per zip code in each category): race, ethnicity, zip code, program, age?

(The open data portal will take care of hiding data if there are less than 5 people in a search result, aka k-anonymity. We just have to give a CSV to the City.)

**Comment by baipai** [comment]
Is this for CiviForm admin or program admin?

**Comment by neel-a-mehta** [comment]
This is for the CiviForm admin only

**Comment by bion** [comment]
this is done
