### ISSUE TITLE
CiviForm admins should not have access to raw applications

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1357]
When I logged in as a CiviForm admin on staging, I saw links to view individual applications and download CSVs with them. The CiviForm admin should be able to download anonymized application data (#1303), but not individual-level, non-anonymized data (which they can currently see). The non-anonymized data should be available *only* to the approved program admin for a given program.

![Screenshot 2021-06-14 11 51 21 AM](https://user-images.githubusercontent.com/77128518/121945258-93125880-cd21-11eb-8d47-2e15584c8d1e.png)

**Comment by leonwong** [comment]
@elisekalstad to figure out if this is still an issue and close if not.

**Comment by leonwong** [comment]
Assigned to @elisekalstad to confirm whether this is still an issue (and if so whether it's important to fix). She thought it may have already been addressed.
