### ISSUE TITLE
Figure out applicant UX for required vs. optional questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1404]
Most questions in CiviForm will be required (that will be the default), but some will be optional. What should that look like on the applicant side, both in the core application flow (as you're filling in questions) and on the application preview/review pages? 

One idea is to use the familiar red asterisk to mark required questions, or we could just put `(optional)` next to optional questions since they're less common.

Let's figure out that UX and then get it implemented (to come in a future issue).

**Comment by neel-a-mehta** [comment]
In the short run at least we can do:

- Put an asterisk next to required questions
- Put `(optional)` next to optional questions

This might be a lot, but it's better to overcommunicate, at least for now.

Later on we should try to get proper mocks of how this looks (e.g. what color is the asterisk?)

**Comment by elisekalstad** [comment]
I have a hard time on the CiviForm Admin view knowing which questions are required or not required--even when creating a new question type, I'm not sure which are required until I test out submitting an application. Is there a way to flag that on the Admin side? That way I can add an asterisk to the question text for users/residents to see.

**Comment by baipai** [comment]
@elisekalstad 
The setting was there originally for the admin side but you are right, it is gone now. And I believe the users/residents side’s UI part hasn't been built for the development side if I am not wrong. 

The required and optional question setting was originally under the question bank, which is when the admin manages the program questions. If the question is optional then the admin will turn on the setting and for the users/residents side, they will see “optional” text next to the question. For the required question, the users will see an asterisk.

Below is an example of what the setting looks like for the admin side, I will catch up with the new engineers and update once I have more information.
<img width="114" alt="Screen Shot 2021-07-24 at 4 37 50 PM" src="https://user-images.githubusercontent.com/11348330/126863181-ad38ad5c-be76-4363-8449-caa5301cb6ec.png">

**Comment by baipai** [comment]
@elisekalstad Here is the response from the engineer: 
"This was hidden behind a feature flag. There's a PR #1550 available to turn it back on, but we're leaving that up to the active team to decide when they're ready to merge it in."
