### ISSUE TITLE
Recruiting/scheduling and prep including script(s) for user testing

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#141]

**Comment by lianne-oy** [comment]
Follow up w/ Anna - and create continuity for when Anna rolls off at end of March.

**Comment by lianne-oy** [comment]
This is still on my radar to support recruiting aspect for M4 (linked to #140 )

**Comment by anafreeze** [comment]
Research plan and discussion guide template is ready. Waiting on scheduling and more detailed prototype.
