### ISSUE TITLE
All question types have the same notion of "answered" and are required

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1417]
**Is your feature request related to a problem? Please describe.**

We have five states for each applicant question:
1. unanswered
1. visited but unanswered in the past
1. visited but unanswered in the current program
1. answered in the past
1. answered in the current program

Right now, "is answered" means either:
1. it was seen by the applicant and left blank
2. a real answer was provided.

We need to be clearer and more intentional with "is answered", vs "is visited", vs "is complete", with respect to required vs optional questions.

**Describe the solution you'd like**
We need consistent behavior for "required" questions. And all questions should be by default required.

"is answered" should just be that a real answer was provided, and null values shouldn't be stored.

**Additional context**
`[1, 2]` should be "incomplete" from a block's perspective.

`[3, 4, 5]` should be "complete" from a block's perspective.

**Done when**
All question types behave the same:
* everything is required
* no null or empty values are stored in applicant data
* "is answered" for all questions returns true if an actual answer is provided by applicant, not if it was skipped, which shouldn't even be possible.

**Comment by kendrickt** [comment]
Block#isComplete only used in #isCompleteWithoutErrors

Block#isCompleteWithoutErrors is used in 
* ApplicantProgramReviewController#generateParamsBuilder
* ReadOnlyApplicantProgramServiceImpl#getInProgressBlocks

ReadOnlyApplicantProgramServiceImpl#getInProgressBlocks is used in
* #getInProgressBlockAfter
* #getFirstIncompleteBlock

PROPOSED CHANGES:

ApplicantProgramReviewController#generateParamsBuilder -> needs to change to handle ignored optional questions

ReadOnlyApplicantProgramServiceImpl#getInProgressBlocks -> no change, beacuse "in progress" means any block that is:
* incomplete
* has errors
* completed in this program
This is fine with "optional" since we want to show all incomplete optional questions which haven't been "visited" in the current program.

ReadOnlyApplicantProgramServiceImpl#getInProgressBlockAfter -> no change

ReadOnlyApplicantProgramServiceImpl#getFirstIncompleteBlock -> change to skip questions "visited" in the current program.

**Comment by lianne-oy** [comment]
In progress

**Comment by kendrickt** [comment]
For enumerator and multi-select questions, required (default) means:
* enumerator questions need at least one repeated entity
* multi select questions must have at least one selection
