### ISSUE TITLE
JS question validation only validates required questions, or attempted optional questions.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1418]
**Is your feature request related to a problem? Please describe.**
If a question is optional and I leave it blank, I should not see or be blocked by validation errors.

**Describe the solution you'd like**
JS question validation only applies to:
1. all required questions
2. optional questions with at least one field with a value

**Additional context**
#1416 introduces a class which can be used by js validation.

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by lianne-oy** [comment]
In progress -
