### ISSUE TITLE
Add borders to "Download all (CSV)" button in Internet Explorer

### ISSUE THREAD

**Issue by ialv44** [seattle-uat/civiform#1420]
**Is your feature request related to a problem? Please describe.**
"download CSV" button has no borders in Internet Explorer

**Describe the solution you'd like**
To add borders to the "Download all (CSV)" button to be readily spotted/identified by program admins

**Additional context**
![image](https://user-images.githubusercontent.com/75772797/122947687-f93d5200-d397-11eb-8a02-b9c3f88063eb.png)

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by neel-a-mehta** [comment]
We don't officially support Internet Explorer, so we should focus on getting #512 done, and then we can close this one out.
