### ISSUE TITLE
Make "Trusted Intermediary Dashboard" link more prominent in TI interface 

### ISSUE THREAD

**Issue by ialv44** [seattle-uat/civiform#1421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
![image](https://user-images.githubusercontent.com/75772797/122974551-13832a00-d3b0-11eb-9199-057b958436d7.png)

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by neel-a-mehta** [comment]
In other words: the link to the "Trusted Intermediary dashboard" in the TI view is easy to miss since it's so small and visually not prominent. 

Instead, perhaps make a blue, full-width banner that takes up the top of the page.

**Comment by elisekalstad** [comment]
Done per: https://github.com/seattle-uat/civiform/issues/1742
