### ISSUE TITLE
block navigation with enumerators is not right

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1431]
**Describe the bug**
Sometimes, the repeated blocks for a repeated entity are skipped entirely.

**To Reproduce**
1. Go to staging
2. Login as guest
3. Apply for the "ete enumerator program"
4. First block: just answer the name question
5. Second block: provide two repeated entities. I named them "aaa" and "bbb"
6. Third block: answer with any name for "aaa"
7. Fourth block: don't add any repeated entities for jobs of "aaa"
8. Now you're in the review page.

**Expected behavior**
The applicant should be taken to 5th and 6th blocks to answer name and jobs for repeated entity "bbb".

**Comment by lianne-oy** [comment]
Prioritize fixing in next week

**Comment by kendrickt** [comment]
This is fixed because as of right now, all questions are required, including enumerator questions, so you cannot do step 7 in the repro steps.

PR #1451 makes all questions required.
