### ISSUE TITLE
In number input, entering `e`, `-`, or `+` wipes out the input field

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1433]
In #1413, we fixed #1391, which caused an error when the user entered a value that ends in `.0` or `.00` (etc.) in a numeric input field.

I was just testing out the new numeric input fields. The desired behavior, it appears, is that any character besides a digit will be "banned" from input. 

If I type | Then I see
--- | ---
`123` | `123`
`abc123` | `123`
`123abc` | `123`
`12!@#$%^&*()3` | `123`
`12[]3` | `123`

These all behave as expected. But certain math-y symbols cause the entire input field to be wiped out!

If I type | Then I see
--- | ---
`12d3` | `123`
`12e3` | `3`
`12+3` | `3`
`12-3` | `3`

In the case of `e`, `+`, or `-`, I would expect those inputs to be silently banned and the numbers in the field to stick around... but instead the numbers I've already entered vanish as soon as I press the offending keys!

My guess is that it has something to do with the way we parse numbers: `-` is used to label negative numbers, `+` is used to coerce  values into JavaScript, `e` is used to describe powers of ten (`5e3 === 5000`). We may need to have a more sophisticated parsing method.

**Comment by shubha-rajan** [comment]
Hi! I'd like to work on this issue. I think I have a fix for it. Will open a PR shortly.
