### ISSUE TITLE
Let TIs and applicants work on applications together

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1436]
We've heard that TIs (CBOs) like to train applicants to apply for programs on their own. They want to split the work, so applicants can slowly start picking up more and more of the application, until they're self-sufficient. Younger applicants, in particular, tend to be keen to learn to apply by themselves.

So let applicants and TIs work together, either in real-time or asynchronously. Share the state of an application across the two of them.

**Comment by mayamcgrory** [comment]
I would like to assign myself to this issue. Thank you!
