### ISSUE TITLE
Surface eligibility rules on application preview page

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1449]
#970 discusses how we want to add eligibility criteria for programs. #973 shows the UI where admins can specify eligibility rules.

For this, we want to show eligibility rules on the application preview page (and possibly even on the applicant homepage). This just summarizes the eligibility logic, e.g. "You need to meet all these criteria: ...".

If we already know that an applicant is ineligible given their past answers (see #1450), we can show that information on this page directly.

**Comment by baipai** [comment]
Assigned for ux design part.
