### ISSUE TITLE
Make it easier for CiviForm admin to find newly-created program

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1481]
When a CiviForm admin creates a new program, their new program goes way to the bottom of the list of programs (or sometimes ends up randomly in the middle of the list). It's quite likely that the admin's next goal is to edit the new program, so having to hunt and find it would be tedious.

Potential improvements:

- Offer a way to sort programs (#941) -- and, by default, sort with the newest or most recently edited programs on top.
- Show a success message once the new program has been created. And in that success message, placed at the top of the page, add a quick link to edit the newly-created program.

Ideally we'd do both. Focus on the latter here, since the former has its own issue already.

**Comment by kristinyim** [comment]
Duplicate with https://github.com/seattle-uat/civiform/issues/1238 so am closing.
