### ISSUE TITLE
Let applicants sign up to get SMS notifications

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1495]
We have functionality in place to send applicants email notifications, such as when they submit applications (I think). In #974, we recommend emailing them when there are new programs available.

But not everyone has an email or checks it regularly. Offer to let applicants put their phone number on their profile and opt in to SMS updates. If they provide a phone number, we can SMS them in addition to emailing them with updates.

**Comment by rasmi** [comment]
Re-filed as #4850.
