### ISSUE TITLE
Create open data portal to show aggregated stats across programs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1498]
#1337 lets CiviForm admins export demographic and other aggregate data to put on the City's open data portal. But it might be useful to show overall (coarse) stats for programs right on CiviForm itself. We can just have a "Data" tab that shows the number of applications to each program, with perhaps a little more high-level demographic data.

**Comment by baipai** [comment]
Is this for CiviForm admin or program admin?

**Comment by neel-a-mehta** [comment]
This should be a publicly-visible page on the site (perhaps put a link in the footer to this page).
