### ISSUE TITLE
Let CiviForm admins specify new languages directly inside CiviForm

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1504]
Currently, we support Seattle's Tier 1 languages (#901). If a city wants to add support for more languages, their engineering staff has to go in and change some configuration files.

This isn't a bad solution, but it would be even easier for CiviForm admins if we could let them add languages directly within the UI. Perhaps add a  "Configuration" tab in the CiviForm Admin view, where they can add languages (among potential other changes in settings).

**Comment by baipai** [comment]
This needs to be discussed more with engineers and see how that works out, because I think under the current system, there are only a few things that can be done. Then it may be a totally different story then the view now. :)
