### ISSUE TITLE
Add styling and Copy button to deep-link section on CiviForm admin page

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1526]
The CiviForm admin's homepage shows the deep-links to each program:

![image](https://user-images.githubusercontent.com/77128518/123844383-f6cf8080-d8e0-11eb-8784-3c6728fbf8f5.png)

To make this easier to use and more salient, we should:

- Add some more styling here
- Add a "Copy" button that, when clicked, copies the deep-link to the user's clipboard (easy to do with JavaScript)

**Comment by UXDESIGNNAM** [comment]
Hi Neel, I would like to be assigned to this task. Not sure how I can add myself.

**Comment by holly-r-li** [comment]
Hi Namrataa, just assigned to you!
