### ISSUE TITLE
Admin can create simple predicates for blocks

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#1532]
This is the simple case, branched from #322 

**Describe the solution you'd like**
As a CiviForm admin, I should be able to conditionally show or hide a block based on an applicant's answers to previous questions. I want to...

1. Hide a block if an answer fits specific criteria that I define
2. Show a block if an answer fits specific criteria that I define

**Additional context**
If a block is hidden, it should not show up in the summary view nor in their application submission

**Done when**
An admin can add a simple (one-condition) predicate to a block. An applicant sees a different next block based on their answer to the question the condition is based on.

**Comment by neel-a-mehta** [comment]
Testing...

![image](https://user-images.githubusercontent.com/77128518/124037394-7e92b900-d9cd-11eb-8794-3f10eadaf6b1.png)

![image](https://user-images.githubusercontent.com/77128518/124037442-95391000-d9cd-11eb-9150-d4873a9c48e0.png)

![image](https://user-images.githubusercontent.com/77128518/124037487-a5e98600-d9cd-11eb-87e3-d77f31ccb8cd.png)

![image](https://user-images.githubusercontent.com/77128518/124037523-b3067500-d9cd-11eb-9509-2ce9b896063a.png)

![image](https://user-images.githubusercontent.com/77128518/124037543-b8fc5600-d9cd-11eb-9656-120896169772.png)

![image](https://user-images.githubusercontent.com/77128518/124037590-c87b9f00-d9cd-11eb-9415-31cec3d85f4f.png)

![image](https://user-images.githubusercontent.com/77128518/124037604-cfa2ad00-d9cd-11eb-8685-2697dc5d6cbe.png)

**Comment by neel-a-mehta** [comment]
This works as I expected; adding predicate logic works great, and blocks are properly shown and hidden. Great work!
