### ISSUE TITLE
Static question type not visible on published forms

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1555]
**Describe the bug**
The static question type does not display on the published forms. I am able to create a static question (i.e. with our Privacy Statement on it) and publish it to a program. But when residents/TIs open the form, they don't see any text. The form "skips" over the static text and goes straight to the next section of questions.

**To Reproduce**
1. Create a static question (i.e. text from the privacy statement)
2. Drag the question onto a form (in Admin view)
3. Publish form (in Admin view)
4. Login as a user/resident and start form (i.e. the Seattle Preschool Program)
5. Static text will not appear

**Expected behavior**
I would expect the static text to appear.

**Screenshots**
Attached

**Desktop (please complete the following information):**
Chrome
[Static Question Issue.docx](https://github.com/seattle-uat/civiform/files/6851715/Static.Question.Issue.docx)

**Comment by elisekalstad** [comment]
[Static Question Issue.pdf](https://github.com/seattle-uat/civiform/files/6887168/Static.Question.Issue.pdf)

**Comment by ettengererin** [comment]
getInProgressBlocks() seems like a safe place to add logic for showing static questions. We can check if the block has one and only one question that is static and if so, show that block. Static questions isAnswered() always returns true, so the user should still be able to progress in the flow without getting stuck.

https://github.com/seattle-uat/civiform/blob/67d108af88d5877febb42e2b55c1d59a4e07726c/universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L65

**Comment by lindsayzad** [comment]
We have good working code for this with unit tests.  Need clarity on whether blocks that have previously answered questions and static questions should always be shown as well, or only block with purely static questions.  After that is answered we can check in a PR.
browser-test that covers this is still TBD as well

**Comment by ettengererin** [comment]
We need help from @elisekalstad on how to handle the following cases. We think we know what to do for case 1 and 2, but 3 is still unanswered.

1. Screen with **only** static questions --> always show this screen including the static questions
2. Screen with 1 or more static questions and 1 or more **incomplete** questions --> always show this screen including the static questions
3. Screen with 1 or more static questions and 1 or more **complete** questions --> ???

**Comment by elisekalstad** [comment]
@ettengererin -- Is this just on the "Review" page? If so, I agree on #1 & 2, #3 don't show static text:

Screen with only static questions --> **always show this screen including the static questions**
Screen with 1 or more static questions and 1 or more incomplete questions --> **always show this screen including the static questions**
Screen with 1 or more static questions and 1 or more complete questions --> **don't show the static questions** (just thinking that it would be a A LOT of text on the review page that might not be needed context if the user already completed the questions)

**Comment by ettengererin** [comment]
@elisekalstad Thanks for your response!

The behavior on the "Review" page and the behavior throughout the application flow are two different things. 


I am describing the behavior **throughout the application flow**. I think I need to clarify a bit -- we will never be hiding **questions**, we will only be hiding **screens**. 

What are your thoughts for the above cases for the application flow? 
- Specifically, we need to know what to do when there is a Screen with 1 or more static questions and 1 or more complete questions. Should we show this screen or hide this screen? 
- In this case, the application has already seen and filled out the answerable questions. However, they haven't necessarily seen the static question, so if you'd like to ensure that they ALWAYS see the static question, we should show this screen.

**Comment by elisekalstad** [comment]
Ohh! Got it! In that case, static text should always been visible, even if the questions are completed.

**Comment by ettengererin** [comment]
Great, thank you so much!
