### ISSUE TITLE
Not able to create an account after completing application as guest

### ISSUE THREAD

**Issue by leonwong** [seattle-uat/civiform#1568]
**Describe the bug**
Error entering email and password 

**To Reproduce**
Fill out ORCA application as guest
After submitting application, follow link to create an account
Enter valid email and password

**Expected behavior**
Account creation to succeed, but it says Invalid username or password. 

**Screenshots**
![IMG_4020](https://user-images.githubusercontent.com/926911/128916490-ba1c2d1d-d054-4613-898f-411e445aeb45.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: iOS 14.7.1
 - Browser: safari
 - Version: latest

**Additional context**
N/A

**Comment by leonwong** [comment]
Looks like the problem is that the page it navigates to is a login page and does not have an account creation option.

**Comment by dkatzz** [comment]
Reached out to the city and they fixed this link.

**Comment by ettengererin** [comment]
Should we go ahead and close this issue if it's fixed by the city?

**Comment by dkatzz** [comment]
Yes, good call! Closing.
