### ISSUE TITLE
Entering symbols like $ or . into ORCA application monthly income field clears numeric content

### ISSUE THREAD

**Issue by leonwong** [seattle-uat/civiform#1573]
**Describe the bug**
More a usability question than a bug, but guessing that some people might think to enter income with currency symbol and decimal point, e.g., $1234.56

**To Reproduce**
Type a number into ORCA application monthly income field.
Press $ or . several times
First time, the symbol doesn't get entered, and the next time the number disappears from the field.

**Expected behavior**
Allow currency symbols, or at least don't clear the numbers that have been entered.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: iOS 14.7.1
 - Browser: safari
 - Version: latest

**Additional context**
N/A

**Comment by lindsayzad** [comment]
Related to #1433

**Comment by lindsayzad** [comment]
Duplicate; closing as this is now obsolete, replaced by issue #1623
