### ISSUE TITLE
Admin should be able to download all applications, regardless of version

### ISSUE THREAD

**Issue by dkatzz** [seattle-uat/civiform#1582]
**Is your feature request related to a problem? Please describe.**
In the admin view, each version appears with a link to the applications. The user has to scroll to the bottom to see the most recent version and if they click download at the top, it isn't clear what version is being downloaded. https://github.com/seattle-uat/civiform/issues/1560 will work to address seeing the latest version only, but it would also be ideal if the admin could download all applications.

**Describe the solution you'd like**
Admin is able to download ALL applications, regardless of form version.

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?
The admin is able to download ALL applications, regardless of form version.

**Comment by kristinyim** [comment]
Solved by #1990! Closing.
