### ISSUE TITLE
Applicants who create a new user account are routed to Utilities Page 

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1585]
**Describe the bug**
If a new applicant creates a user name and password, verifies their account via email, and then logs in, the applicant is routed directly to the utilities portal (instead of back to CiviForm)

**To Reproduce**
1. Go to Civiform.seattle.gov
2. Click on '.Create New Account'
3. Complete the fields required (username, password, name, email)
4. Activate account via email
5. (goes to link to enter user name and password)
6. Automatically reroute to utilities portal: https://myutilities.seattle.gov/eportal/#/accountlookup/default

**Expected behavior**
If an applicant came to CiviForm to create a new account, would expect them to be re-routed BACK to Civiform once the account is created.
![Routed to Utilities](https://user-images.githubusercontent.com/86082659/129816942-cd839b54-9a0e-4131-8fa8-fe4260da5d5e.JPG)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dkatzz** [comment]
Reached out to Vinay and this will be fixed in the next prod deployment

**Comment by shanemc-goog** [comment]
It's been a few months, is this working correctly now?

**Comment by elisekalstad** [comment]
Thanks, Shane. The IDCS migration was slated to go live this week. Unfortunately, today’s update from John Yeung is that there is a delay with security and it’s slated to go live on Monday.
________________________________

**Comment by dkatzz** [comment]
Just tested this and doesn't seem to be live yet - any word from John?

**Comment by elisekalstad** [comment]
I’ll ask! I haven’t heard anything this week.

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>

**Comment by elisekalstad** [comment]
Update: This will be resolved with a new version of SSO that will go live on Monday, 11/15. John and Vinay promise :) @dkatzz Are you able to check the URL for logout? It should call **https://login.seattle.gov/#/logout?appName=CiviForm** but won't work until Monday.

**Comment by dkatzz** [comment]
Thanks for the update, Elise! Should I be checking that normal logout from within civiform calls that URL or be checking a different flow? I'm not seeing that be called right now, but maybe it's paired with Monday's go live? Let me know and I can take another look. Thanks!

**Comment by elisekalstad** [comment]
Thanks, Danielle!
It should be paired with Monday’s go-live. Thanks,
Elise

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>

**Comment by elisekalstad** [comment]
Hi @leonwong -- The IDCS SSO migration was complete. Are you able to update the following?

The link https://login.seattle.gov/#/registration should be updated to **https://login.seattle.gov/#/registration?appName=CiviForm**

**Comment by leonwong** [comment]
Fixed
