### ISSUE TITLE
When creating a dropdown question, all progress is wiped if you leave a field blank and click "submit".

### ISSUE THREAD

**Issue by ettengererin** [seattle-uat/civiform#1587]
**Describe the bug**
When creating a dropdown question, I will create a question with a few dropdown answer options. If I leave an option field blank and click "create", the creation will fail with an error "Multi option questions cannot have a blank option" (this is good) BUT it will also wipe out all the option fields I did fill out. This is frustrating as an admin because I wish my populated fields would still be populated. However, now I need to go fill out all my answer options again. 

This is extra annoying for long dropdowns -- for example, a dropdown of all the public schools in Seattle. If I accidentally leave an option field blank and submit, then I have to re-enter 100+ options.

**To Reproduce**
1. Go to Admins Questions tabs
2. Create a new Dropdown question
3. Fill out all fields. 
4. Add an answer option and fill it out.
5. Add another answer option and leave it blank.
4. Hit submit
5. All answer options will be empty fields will be empty :(

**Expected behavior**
Same error message should be shown, and previously populated answer options to still be populated. User should just get a chance to fill out or delete the empty answer option.

**Screenshots**
![image](https://user-images.githubusercontent.com/86738827/129976029-f22c5b4a-f07e-477c-bf15-afe15cd04536.png)

![image](https://user-images.githubusercontent.com/86738827/129976143-bc1dd6ae-4836-4f62-9ed3-0d5d456f4c28.png)

**Comment by elisekalstad** [comment]
My bad for not including additional user cases! Here is one other one:

Steps:
1) login as CiviForm Admin, 
2) Create a new question, for example, an dropdown question for an enumerator
3) Forget to do a step (i.e. adding in "$this" on enumerator fields) 
4) Try to save the new question
5) Get an error 
6) All dropdown options are then wiped

Context:
It's really just user error--I forget to add a required component when building a new question. But the impact of the error is that I have to start over entering in options. On the good side--it's forced me to do better documentation. On the frustrating side--a silly error causes me to start completely over and sometimes the list of options is LONG (like the Seattle Public Schools, that one hurt).
