### ISSUE TITLE
Draft applications show up in admin application view/csv

### ISSUE THREAD

**Issue by ettengererin** [seattle-uat/civiform#1603]
**Describe the bug**
Tanya Test from Civiform UX reported the following: She created a draft of an application and did NOT submit it. Rosa reported that she was able to see Tanya's application in her admin view, and that fields of her application were incomplete.

Rosa did **not** receive an email confirming Tanya's application submission. So, it seems like when an applicant creates a draft application, Civiform knows that their application is incomplete, but it still puts their draft app in the the application/csv view.

This is confusing for an admin because they think this applicant made mistakes in their applications. This is problematic for the applicant because they may not want the city to see her application if she has not submitted it.

**Expected behavior**
Draft applications should not appear in admin application.

**Additional context**

**Comment by lindsayzad** [comment]
Was able to reproduce this issue in test, will look into the code of what's causing this
