### ISSUE TITLE
Link in alert email doesn't route to specific application

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1607]
**Describe the bug**
A program admin receives an email alert when there is a new application for their program. The email includes a link for the admin to "view the application". The link takes the program admin to a page with ALL form versions. And NOT to the resident's specific application.

**To Reproduce**
1. Open the "New Application" email alert from Outlook
2. Click on link to "view the application"
3. User is directed to the civiform page to view ALL applications

**Expected behavior**
Would expect the direct URL in the body of the email to route program admins direction to that specific application

**Screenshots**
Need to review/request from a program admin, I can't replicate the issue.

![Email link issue](https://user-images.githubusercontent.com/86082659/131415284-87c016ba-9efb-4f48-bbce-be5d4ad2627d.jpg)

**Comment by leonwong** [comment]
@elisekalstad as far as I can tell this is the correct URL to route to the application view, and the code looks correct as well. Could you send me an example email? Unfortunately, emailing doesn't work in our development environment so it's a bit hard to test. Thanks!

**Comment by elisekalstad** [comment]
Sounds like this may have just been a browser issue. Closing!
