### ISSUE TITLE
Date formatting in CSV export (program admin view)

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1611]
**Describe the bug**
Program admins need to export the full CSV of all applicants' information. There are a few "date" question types that are displaying as really, really long numbers. Is there a way to format the CVS export for the "date" question type to show in a date format?

**To Reproduce**
1. Login as a Program Admin
2. Export all applications in a CSV
3. Scroll over in the excel to view a "date" question type and see the applicant's answer
4. Data is in a "numberic" format, it needs to be in a "date" format to be useable for the program admin.
![Date of signature not in date format](https://user-images.githubusercontent.com/86082659/132913205-ecd320f4-870f-4529-9a59-9008c301f019.png)

**Expected behavior**
The "date" question type would display as dd/mm/yyyy (or something similar) in the CSV export

**Screenshots**
Attached

**Comment by dkatzz** [comment]
@elisekalstad, could you confirm if having the date format be "MM/dd/yyyy" is good? So it would be exported as "09/13/2021". Or would you prefer "yyyy-MM-dd' or some other format? Thanks!

**Comment by elisekalstad** [comment]
Hi Danielle,
Yes, the format mm/dd/yyyy is preferred. Thank you!

-Elise

[Title: City of Seattle logo]Elise Kalstad
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
   Facebook<https://protect2.fireeye.com/v1/url?k=daf2de2b-8569e719-daf2f69b-8697e44c76c2-ac8cbbaf40b6a748&q=1&e=a18b8788-8c55-40b3-b962-7521a34eb6bf&u=https%3A%2F%2Fwww.facebook.com%2Fseattlemayorsoffice%2F> | Twitter<https://twitter.com/CityofSeattle> | Subscribe to Mayor Durkan's E-Newsletter<http://wwwqa.seattle.gov/mayor/subscribe>

**Comment by elisekalstad** [comment]
Hi @dkatzz -- Any chance you could take a look? Jen with Human Service Department (one of the program admins for UDP) mentioned the export for date of birth and date form was signed is still showing as a long decimal. I can try to wrangle a screenshot of it, if that's helpful.

**Comment by elisekalstad** [comment]
Thank you!!

[Title: City of Seattle logo]Elise Kalstad
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
   Facebook<https://protect2.fireeye.com/v1/url?k=daf2de2b-8569e719-daf2f69b-8697e44c76c2-ac8cbbaf40b6a748&q=1&e=a18b8788-8c55-40b3-b962-7521a34eb6bf&u=https%3A%2F%2Fwww.facebook.com%2Fseattlemayorsoffice%2F> | Twitter<https://twitter.com/CityofSeattle> | Subscribe to Mayor Durkan's E-Newsletter<http://wwwqa.seattle.gov/mayor/subscribe>
