### ISSUE TITLE
Ability to format text (to highlight and bold text for emphasis)

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1615]
**Is your feature request related to a problem? Please describe.**
Residents can easily glaze over important text on forms if it isn't highlighted or in bold.

**Describe the solution you'd like**
The ability to make text (such as in static question types or other question types) bold or a different color.

**Comment by leonwong** [comment]
Recapping standup discussion - we already have URL formatting in civiform (turns URLs into hyperlinks), and could use something like a subset of html or markdown syntax to implement this feature. Main challenge is making markup easy while avoiding unintended parsing of text content as markup.

This is a nice to have that would be useful for UDP.

**Comment by baipai** [comment]
I think this is also relative to #888 ?

**Comment by elisekalstad** [comment]
Oh yes! Thanks Bai—it’s definitely the same one. I’ll remove mine and flag #888.

Thanks,
Elise

[Title: City of Seattle logo]Elise Kalstad
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
   Facebook<https://protect2.fireeye.com/v1/url?k=daf2de2b-8569e719-daf2f69b-8697e44c76c2-ac8cbbaf40b6a748&q=1&e=a18b8788-8c55-40b3-b962-7521a34eb6bf&u=https%3A%2F%2Fwww.facebook.com%2Fseattlemayorsoffice%2F> | Twitter<https://twitter.com/CityofSeattle> | Subscribe to Mayor Durkan's E-Newsletter<http://wwwqa.seattle.gov/mayor/subscribe>

**Comment by kristinyim** [comment]
Same as #888 so closing
