### ISSUE TITLE
Demographic CSV export includes draft applications (not yet submitted)

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1618]
**Describe the bug**
I logged into the admin portal as the CiviForm Administrator. I downloaded the CSV with all demographic information. The CSV includes applications that were only in "draft" state and not yet submitted. In order to have accurate reporting, I'd like to be able to only see information from applications that were 'submitted"

**To Reproduce**
1. Login via Admin Role (CiviForm Admin)
2. Scroll down to "Download exported CVS"
3. Open the download
4. See rows that include blank fields

**Expected behavior**
Exports should filter out any applications that were never actually "submitted"

**Screenshots**
Attached--shows an example where I never clicked "submit" but a submit date is still assigned AND it shows up in the excel export.

![Demographic CSV Export](https://user-images.githubusercontent.com/86082659/133337549-b0772e47-39b2-4bdc-b858-ad55f50be994.JPG)

**Comment by bion** [comment]
I think the intention here was so that one could see who isn't making it all the way through the application process, for analytics purposes. Is that no longer a goal?

**Comment by elisekalstad** [comment]
Ohhh! Interesting! I didn’t realize that, but that actually makes a lot of sense. What’s the best way to be able to tell if the application was ultimately submitted?

One idea: the submitted applications could have a “submitted date” while those that are just in draft state would have a blank cell. The current export contains a “submitted date” regardless of whether it was actually submitted.


[Title: City of Seattle logo]Elise Kalstad
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
   Facebook<https://protect2.fireeye.com/v1/url?k=daf2de2b-8569e719-daf2f69b-8697e44c76c2-ac8cbbaf40b6a748&q=1&e=a18b8788-8c55-40b3-b962-7521a34eb6bf&u=https%3A%2F%2Fwww.facebook.com%2Fseattlemayorsoffice%2F> | Twitter<https://twitter.com/CityofSeattle> | Subscribe to Mayor Durkan's E-Newsletter<http://wwwqa.seattle.gov/mayor/subscribe>

**Comment by leonwong** [comment]
Recapping standup discussion: proposal is to implement Elise's suggestion of using the submitted date to differentiate between submitted and draft applications.

**Comment by ettengererin** [comment]
This issue should be mostly resolved when we have a prod deployment. Lindsay submitted this PR (https://github.com/seattle-uat/civiform/pull/1606) which removes draft applications from CSV download. This should clear up confusion.

We still want to be able to download draft applications sometimes, however, so that we can identify when folks are dropping off the application. I added a feature request here - https://github.com/seattle-uat/civiform/issues/1620.
