### ISSUE TITLE
Entering a decimal in a number question type erases the next number

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1623]
**Describe the bug**
On the UDP form, we ask residents to enter in their monthly income. If the resident types a decimal point, the decimal point will be erased when the next digit is entered. It can lead to a resident accidentally submitting a form with monthly income of 10000 instead of 1000.

**To Reproduce**
1. Go to TEST UDP program application
2. Enter monthly income
3. Use a decimal point
4. Next number typed will not appear
5. Decimal point will be erased

**Expected behavior**
Decimal points should not erase numbers nor disappear.'

**Screenshots**
Attached
![Decimal erasing](https://user-images.githubusercontent.com/86082659/134432510-d9c755a8-cec0-4321-8b56-847451eb74d7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lindsayzad** [comment]
This is related to #1573 and #1433 ; see those issues for further context

**Comment by shanemc-goog** [comment]
Currently the number field is required to be an Integer and is massaged to be or it's erased.

I'm not sure why the '.' is retained, but when the first decimal is typed the double is massaged into an int and replaces the field content.

JS validation:
https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java#L212

**Comment by elisekalstad** [comment]
@shanemc-goog -- Hi Shane--the UDP team is curious about the lift on this one. Is this something that could be fixed soon? Just wondering what I can report back to them. Thank you!!!

**Comment by shanemc-goog** [comment]
We'll address this issue by implementing the Currency type (go/uat-question-requirements) as tracked in https://github.com/seattle-uat/civiform/issues/450

**Comment by shanemc-goog** [comment]
We shouldn't separately figure out why you can type a decimal-point into the existing Number field as its extraneous and I believe the current validation code is designed to not allow it.
