### ISSUE TITLE
Handle exporting multiple values for CSV export

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#164]
Notes:
https://www.inogic.com/blog/2017/11/import-data-with-multi-select-option-set-values-in-dynamics-365-v9/#:~:text=To%20import%20the%20records%20with,%E2%80%9C%3B%E2%80%9D%20as%20the%20separator.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by neel-a-mehta** [comment]
The semicolon approach for repeated fields makes a lot of sense!

**Comment by neel-a-mehta** [comment]
Closely related to #187

**Comment by lianne-oy** [comment]
M1 Review - No engineering tasks for this in M2; however, we should know direction for this decision by M2.

**Comment by neel-a-mehta** [comment]
This has been handled in the CSV/PDF export requirements doc. https://docs.google.com/document/d/1zhs65i5PzxfkiZXPniPAxEDD257Iz4IP1JfxHY36hR8/edit?resourcekey=0-ByzGbFZlzPNxZTxRQCbVDQ#heading=h.blu27libo39e
