### ISSUE TITLE
Error validation shows on optional question if empty and required question has error

### ISSUE THREAD

**Issue by dkatzz** [seattle-uat/civiform#1652]
**Describe the bug**
On a program block where there is an optional and required question, if the user makes a mistake on the required question and clicks next, error validation will show on both questions (even though the optional one is blank). It is kind of confusing and makes it seem like the optional question is required. https://github.com/seattle-uat/civiform/issues/1423 would be helpful in making this more clear, but maybe error validation should only show for optional questions if they've started filling them.

**To Reproduce**
1. Create a program with a block that has an optional and required question
2. When filling out the page as an applicant, click next without filling out the questions
3. See error validation on both the required and optional question

**Expected behavior**
I think error validation should only show for optional questions if they've started filling them.

**Screenshots**
Uploaded

**Comment by shanemc-goog** [comment]
There's a test for this that is currently commented out awaiting the fix.

https://github.com/seattle-uat/civiform/blob/main/browser-test/src/address.test.ts#L236

**Comment by dkatzz** [comment]
Impacting program that isn't yet in production - https://civiform.seattle.gov/programs/electricity-bill-assistance-program-ebap
