### ISSUE TITLE
Program Admin unable to get access to completed applications

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1665]
**Describe the bug**
Thor is a program admin for the UDP program. He is signed up to receive email notifications when there is a new application. When he clicks on the link to open the application though, he gets a 403 Forbidden Error.

He is also unable to view the UDP program by logging in as an admin. 

I tried to remove his email from the list of program admins and re-add him. No luck.

He IS able to view everything on the TEST_Program. The only difference there is that his email is Thor.Peterson@seattle.gov vs. no capitalization thor.peterson@seattle.gov. I tried his email with capitalization and it saved without capitalization.

**To Reproduce**
1. Thor receives an email notification about a new applicant 
2. Click on the link to the application
3. See 403 Forbidden Error

4. Log in as an "Admin"
5. Unable to see the UDP program in the program list

6. CiviForm Admin adds Thor's email address (Thor.Peterson@seattle.gov)
7. Select Save
8. See that email reverts to thor.peterson@seattle.gov

**Expected behavior**
Thor should be able to view applications from the emailed link.
Thor should be able to view the UDP program when logging in as an "Admin".
![Program Admin - Error](https://user-images.githubusercontent.com/86082659/139720150-85bfe22f-80ac-46cb-ad80-5c0e5ecd4567.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ettengererin** [comment]
This bug is being tracked in https://github.com/seattle-uat/civiform/issues/1612
