### ISSUE TITLE
Error when submitting UDP application

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1676]
**Describe the bug**
A resident emailed to say that they receive an error message when submitting the final application. I attached the error message (ID: 7lhmip3h7)

**To Reproduce**
1. Complete the required fields of the form
2. Complete the final questions for "Name" and "Date of signature"
3. Select "Next"

**Screenshots**
Attached

![Error_UDP](https://user-images.githubusercontent.com/86082659/140593069-b801cd11-3d79-4f76-be64-abb7f4664967.JPG)

**Comment by lindsayzad** [comment]
Currently blocked on this; no permission to view AWS logs.  Elise is following up with the city on expanded permissions, and I reached out to Indira to see if she could take a look for any related logs.

**Comment by bion** [comment]
this has been resolved
