### ISSUE TITLE
Write terraform code for provisioning Azure deployment

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1689]
Terraform automation scripts should:

- [x] provisions application servers
- [ ] provisions load balancer for application servers
- [x] provisions database
- [ ] configures database backups
- [ ] enables cloud file storage interop
- [ ] enables email sending interop
- [ ] configures autoscaling for application servers

**Comment by goldblatt** [comment]
I think this is pretty out of date, but will close as i think it's completed
