### ISSUE TITLE
Name validation only uses the status of the last question.

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1693]
https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts#L383

The returned status is overwritten each loop.

**Comment by shanemc-goog** [comment]
See #1694 for how to test

**Comment by shanemc-goog** [comment]
Related example for fixing up these kinds of test #1668

**Comment by tjbanghart** [comment]
I can take this one!
