### ISSUE TITLE
New Program Visibility setting is required but optional in the UI

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1698]
**Describe the bug**
When making a new Program you can select between having it be Hidden of Public, but neither is selected by default and the UI doesn't require one be selected

If you submit without selecting one, a generic BE error is issued to the FE

**To Reproduce**
1. Create a new Program without selecting either Hidden or Public and submit

**Screenshots**
![displaymode](https://user-images.githubusercontent.com/90928876/141595290-bf7018b0-c42c-40c0-a2bf-0d6826c10efc.png)

**Comment by zaralouis-sf** [comment]
I'm going to work on this as a starter bug.
