### ISSUE TITLE
Resident experiencing erroneous account

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1714]
**Describe the bug**
I received an email from a resident trying to login to CiviForm to apply for the Parks Childcare Scholarship program. The resident's account showed as "Husband, Jack" in the top right. The resident tried to log out and back in again and the name did not change. The resident is not named Jack Husband. Screenshot included.

**To Reproduce**
1. Log in with account
2. Select "Parks Childcare Scholarships" program
2. View name in top right as "Husband, Jack"
3. Log out
4. Log in again
5. Still says "Husband, Jack" in top right

**Expected behavior**
Residents account name should apprear.

**Screenshots**
attached
![Error -- account name](https://user-images.githubusercontent.com/86082659/142954479-75ee6d1c-0091-424f-abbc-c30da5094057.jpg)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bion** [comment]
@elisekalstad there's no test data or anything in our code that would present that name -- the name is provided by IDCS. I recommend getting their email address and asking the IDCS team what names are associated with that address.

**Comment by elisekalstad** [comment]
@bion -- Will do! Thanks for the direction.

**Comment by elisekalstad** [comment]
Submitted incident #: 5263710 to John Yeung's team for Identity Management vis Oracle.

**Comment by bion** [comment]
this has been resolved
