### ISSUE TITLE
Terraform: Account for resources/names than can only be setup once

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1717]
In Azure db names (as well app name, storage account name) are global in Azure, so any attempt to create a db again will fail the terraform action.

In prod though this may show up at initial setup where the entire environment may be created and destroy.

In dev this shows up if there's shared configs for individual testing.  An easy approach is having a per user id in the name.

Similar to prod devs will likely want to do complete resetups, unclear the solution here.

```
Error: creating PostgreSQL Server "civiform-db" (Resource Group "myTFResourceGroup"): postgresql.ServersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="ServerNameAlreadyExists" 

Message="Specified server name 'civiform-db' is already used. Please use a different name and try again."
│ 
│   with azurerm_postgresql_server.civiform,
│   on main.tf line 200, in resource "azurerm_postgresql_server" "civiform":
│  200: resource "azurerm_postgresql_server" "civiform" {
```

**Comment by goldblatt** [comment]
i think this should be fixed with the random_pet id i added
