### ISSUE TITLE
Terraform: Parameterize hard coded names

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1718]
Create an isolated source for hard coded names that can be updated independent of the generalized Terraform configuration.

EG

```
variable "location" {
  type        = string
  description = "Azure Resource Region Location"
}

```

.tfvars file:
```
location    = "eastus"
```

**Comment by goldblatt** [comment]
hmm in https://github.com/seattle-uat/civiform/commit/d665200b3ce8fdb82967ae036581677cb63dc826 shubha put the tfvars in the gitingore, and from some searching it seems like people often put the .tfvars file into their gitignores as they can contain secrets/passwords. let me check with her real quick about this!
