### ISSUE TITLE
Set up global Staging environment

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1721]
To be owned by Google, shared across all deployments.  Used by SWEs for testing Civiform releases and debugging 'in prod'.

Specific task:

ROC fellows, with assistance from DOW (most likely Shane atm), set up a staging environment using Google's Azure account, with Azure AD and a Google.org-owned LoginRadius account to serve as the mainline project staging environment for now. The domain will be azure-staging.civiform.dev. The mainline github repo will automatically deploy new builds to it as part of CI.

**Comment by goldblatt** [comment]
a lot of this is doen but we should probably break these down into smaller tasks

**Comment by goldblatt** [comment]
made #2109 and #2108 to specify and closing this
