### ISSUE TITLE
Changing grey help text in enumerated question type

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1729]
**Describe the bug**
Parks program staff mentioned that it's confusing to know what to enter for the enumerated fields. They suggested the following:

Update the grey help text from "Nickname for Name" to "First name or nickname for Adult #1

Is it possible to 1) update the grey, in-box help text? or 2) have that text customizable? Similar to the repeated entity type.

**Screenshots**
Attached
[Distinguish names on enumerators.pdf](https://github.com/seattle-uat/civiform/files/7635679/Distinguish.names.on.enumerators.pdf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elisekalstad** [comment]
@leonwong Can we re-open this one and chat on Wednesday? It would help to clarify if the text was just changed from "Nickname for ____" TO "First name".

There is confusion on why we ask for a nickname. When we really just want a first name to begin with. 

Can we plop a text change into the last cycle?

**Comment by leonwong** [comment]
Let's definitely discuss. The reason for the current design is that the repeated entity isn't always a person. For example, enumerated questions could be for jobs, financial accounts, utility accounts, etc. It's also a little hard to have a consistent mapping of the entity nickname to questions that we ask about the entity (e.g., tying nickname for a person to first name) across different entity types.

I definitely agree that the wording/experience is confusing for both admins and applicants. Maybe we can start by making the situation a little easier with tweaks to the design/language, and then I think there's a deeper set of UX renovations that are worth planning for the long-term.

**Comment by leonwong** [comment]
Decision: change entity prompt to Parent/Guardian/Adult instead of Name, and change the prompt to "name" so the overall help text reads "Parent/Guardian/Adult name"
