### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1730]
**Describe the bug**
I logged in as the CiviForm Admin and tried to download the CSV of all applications. I received a 504 Gateway Time-out alert after a few minutes. 

**To Reproduce**
1. Login as CiviForm admin
2. Click on "Exported CSV"
3. See error, attached

**Expected behavior**
CSV should download after a few minutes

**Screenshots**
Attached

**Desktop (please complete the following information):**

**Additional context**
I'm logged into VPN, no other instances of CiviForm are open, my computer should have capacity to download a large excel document, and I'm using Chrome.
![Demographics export timeout](https://user-images.githubusercontent.com/86082659/144319276-01249b42-0b4f-40ec-9566-ba30eb327ff0.JPG)

**Comment by shanemc-goog** [comment]
Using a local setup with a 1 Name question Program, and a code hack to submit an application many times.

896 record in ~18s.    .2s / record

2922 records in 46s      .015s / record

Adding logging shows reading the data from the DB isn't the issue for this example.  That takes .04s.  It's construction the CSV in ExportService that takes all the time.

**Comment by shanemc-goog** [comment]
The two main methods that take a lot of time are

applicantService.getReadOnlyApplicantProgramService at about 0.008s each

csvExporter.export at about 0.0025s each

so abut 0.01s for each record in this contrived example of 1 question.

**Comment by shanemc-goog** [comment]
following it further [programService.getProgramDefinition](https://github.com/seattle-uat/civiform/blob/eec281490e869720c262885a81240aff51f41d00/universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java#L117) is the main time consumer

Which then does an lookupProgram call on each ID which then looks up the individual Program in the DB.

We likely need to look up the program IDs in bulk, or via a join with the original data.  Doing one off DB lookups is inefficient even with the best index.

**Comment by shanemc-goog** [comment]
I've moved the engineer part of this User Issue to #1747

**Comment by shanemc-goog** [comment]
Elise confirmed this is working now with #1747 closed.
