### ISSUE TITLE
Adding Application ID to CSV Export

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1735]
**Describe the bug**
Are you able to add the **Applicant** ID to the CSV export for the Program Admin role? Program admins currently export the CSV but have a hard time identifying if an applicant applied multiple times to the same program. It would help if there is a unique identifier for each applicant (applicant ID) along with the **Application** ID (which already exists).

**To Reproduce**
1. Login as Program Admin
2. Click on "Applications"
3. Download the CSV for all application
4. See that the export includes "ID" (Application ID) but does not have a column for Applicant ID

**Expected behavior**
An additional column in the CSV export of "Applicant ID"

**Screenshots**
Screenshot of the desired naming conventions and additional column.

![Applicant AND Application ID](https://user-images.githubusercontent.com/86082659/145130491-598cd4a5-b8cb-4e95-afe4-7900a5b4c458.JPG)

**Comment by elisekalstad** [comment]
@bion @dkatzz @shanemc-goog -- is there any chance one of you has capacity to tackle this one? It's a must-have for the UDP program in order to identify when there are multiple applications submitted for the same person. We're hoping to go-live with a revised UDP form on Monday. I know that's a big ask, but thought I'd see if it might be possible.

**Comment by bion** [comment]
@elisekalstad We'll take a look and let you know tomorrow if we'll have that in by Monday.

**Comment by bion** [comment]
@elisekalstad the download includes the submitter's email address, is that adequate for the short term?

**Comment by bion** [comment]
It's imperfect, since a trusted intermediary could submit on behalf of an applicant, and if that same applicant also submitted an application for the same program there would be a different submitter email for the two applications for the same applicant.

Just thinking of options if implementing this takes longer than a day.
