### ISSUE TITLE
Ensure consistent program info

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1736]
Ensure consistent program information up-front for the user. This likely is within the Affordable Seattle landing page:

Must include:
Eligibility requirements (in save units across programs, i.e. MONTHLY income (vs. annual income), HOUSEHOLD size (vs. family size), 
Estimated time to apply
Avg. savings
Total cost after savings is applied

**Comment by kristinyim** [comment]
I believe from our conversation that this is going to be resolved by the Seattle team internally so I'll be closing it for now. Feel free to re-open if that is not correct or something changes!
