### ISSUE TITLE
Build API connections for portability of data across applications

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1744]
Include API integrations for live data feeds.

**Comment by kristinyim** [comment]
Rochester has requested a similar solution to connect CiviForm to their tools/processes (like automation) and has noted this a high priority

**Comment by bion** [comment]
self-assigning for the initial portion of this: drafting a design document

**Comment by bion** [comment]
@elisekalstad this is available in the next release

**Comment by bion** [comment]
docs for how to use: https://docs.civiform.us/it-manual/api-integration
