### ISSUE TITLE
Unable to Add Program Admins

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1755]
**Describe the bug**
I'd like to add Program Admins to a new, test program "Emergency Electricity Bill Assistance Program". I tried to add Rhonda and Lani as admins and received an error message. I'm logged into VPN, I used the correct conventions (i.e. upper-case first letters). Is there something else I need to enable in order to add admins?

**To Reproduce**
1. Connect to VPN
2. Log in a Admin
3. Click on "Manage Admins"
4. Click on "Add Admin"
5. Enter the email address
2. Click "Save'
4. See error **"___@seattle.gov does not have an admin account and cannot be added as a Program Admin"**

**Screenshots**
Error attached

![Admin Error](https://user-images.githubusercontent.com/86082659/146821338-759a082a-10bb-400f-b262-b95f57848f44.png)

**Comment by elisekalstad** [comment]
> 

It's working great now! Thanks for following up!

**Comment by elisekalstad** [comment]
Hi @bion It's back to not working... I tried adding Lani and Rhonda again, and I'm getting the same error. I'm not sure if this is a Seattle IT issue or possible application issue. Any ideas?

**Comment by bion** [comment]
There haven't been any changes on the CiviForm side related to this since when it was reported to be working. Any chance it's a email case problem again?

**Comment by elisekalstad** [comment]
Thanks, Bion! I’m checking with the Active Directory team now to see what could be causing it. The case sensitivity doesn’t seem to be it (I tried ***@***.******@***.***> and ***@***.******@***.***> and had the same error). The consistent thread in all issues is that these users have multiple City accounts (Cassie has had 2 City accounts, for example). So I’m thinking there might be a disconnect between the old email address and new one (although they should have the same name).

Thanks for checking in,
Elise

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>

**Comment by bion** [comment]
Looks like GitHub redacted the email addresses in your message. You mention they've had/have multiple email addresses. Is it possible the one they're logging into CiviForm with is different from the one you're using to add them as program admins?

**Comment by elisekalstad** [comment]
@bion , Thanks for taking a look. I tried all of their prior/current email addresses (really just adds a "2" to the end of the name when they have a new email address, if they move departments or something). 

@shanemc-goog , Any chance your work with auth/identity will help with the staff account validation? I have staff who currently aren't able to download applications out of CiviForm.

**Comment by shanemc-goog** [comment]
Bion will know better since he's familiar with my work and this issue.

If an admin _can_ login, then I don't think my change will help beyond that, but the issue I'm fixing should help with some unexpected oddities around identifying users with email addresses.

**Comment by elisekalstad** [comment]
Resolution: System works great! CiviForm Admin needs to ask program admins to login once. And then add them to have access to the correct program.
