### ISSUE TITLE
Continuous Integration failing

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#1756]
CI Is failing, which will prevent any further changes or ability to reliably deploy

**Describe the bug**
 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: unexpected status: 502 Bad Gateway

We started to see CI failures unrelated to any changes in the Repo

To prove this out see this rerun of main [which fails](https://github.com/seattle-uat/civiform/runs/4588435446?check_suite_focus=true), where the [previous run succeeded](https://github.com/seattle-uat/civiform/actions/runs/1588521138/attempts/2).

**Comment by bion** [comment]
Docker hub is down: https://status.docker.com/pages/history/533c6539221ae15e3f000031
