### ISSUE TITLE
Set up Seattle deployment code out of main repo

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1760]
The main civiform repo should not contain deployment or infrastructure code that is specific to a single deployment. To get there, that means moving Seattle-specific ops code to github.com/seattle-uat/civiform-deploy.

Tasks:
- [x] cloudformation code in `infra/`
- [x] bin/check-cfn-change script
- [x] cloudformation github action section from pr.yaml
- [x] bin/breakglass-db-access
- [x] bin/deploy-staging and bin/deploy-prod
- [x] bin/refresh-secrets
- [x] write a script to pull prod image from ducker hub and upload to Seattle's ECR
- [x] add AWS secrets to civiform-deploy repo
- [x] create an action in civiform-deploy repo that deploys to staging and runs probers, and runs on a timer
- [x] add status badge for Seattle's staging deploy and probe to civiform repo README
- [x] remove `infra/` and seattle-related code in `cloud/` from civiform repo
- [x] remove Seattle AWS credentials from civiform repo

**Comment by dkatzz** [comment]
https://github.com/seattle-uat/civiform-deploy/pull/1 with a few of the changes

**Comment by dkatzz** [comment]
https://github.com/seattle-uat/civiform-deploy/pull/2 for github actions (blocked on getting credentials)

**Comment by dkatzz** [comment]
https://github.com/seattle-uat/civiform-deploy/pull/3 is for writing a script to pull prod image from docker hub and upload to Seattle's ECR (blocked on getting credentials)

**Comment by bion** [comment]
@gwendolyngoetz adding you as also working on this. Let me know if you'd like to pair/collaborate!
