### ISSUE TITLE
Add provisioning for Azure Blob Storage in Terraform configs

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#1772]
**Is your feature request related to a problem? Please describe.**
Provision an Azure Blob Storage account and container, make sure it can only be reached from within the same VNET as the application (using a private link), and set the appropriate environment variables in the application config to allow the application to connect to the storage instance.

**Comment by goldblatt** [comment]
so this is a lil more complex than expected, see https://github.com/hashicorp/terraform-provider-azurerm/issues/2977 still trying to get it to work and understand what is happening
