### ISSUE TITLE
Configure Azure load balancing in Terraform

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#1775]
This might be handled by App Service, need to investigate further.

**Comment by zaralouis-sf** [comment]
I wonder if this is what we want: https://docs.microsoft.com/en-us/azure/application-gateway/features#autoscaling

**Comment by zaralouis-sf** [comment]
I feel like I'm getting mixed signals on whether this is handled by App Services

**Comment by goldblatt** [comment]
saw this stackoverflow https://stackoverflow.com/questions/49651539/how-azure-load-balances-scaled-out-app-service-plan so seems like it load balances but maybe we need to autoscale? https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting will discuss with shubha and you offline!
