### ISSUE TITLE
Confirm Azure storage durability policy

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#1776]
Configure settings for storage durability in Terraform

**Comment by goldblatt** [comment]
the file storage is LRS (or copied three times within a single phyusical location in the primary region); this can be configured via the terraform `resource "azurerm_storage_account" "files_storage_account"`

**Comment by goldblatt** [comment]
the postgres server is backed up 7 days by default but could be up to 30; full back up once a week and incremental backups twice a day.

**Comment by goldblatt** [comment]
file storage has back ups for 30days but could configre https://github.com/seattle-uat/civiform/pull/2271
