### ISSUE TITLE
Configure Azure PostregSQL automatic backups / snapshots

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#1777]
This is done in the Terraform configs

**Comment by goldblatt** [comment]
we have a week long automatic back log (but civic entities could store it up to a month) if needed we could set up the azure vault which would store the data for a bit longer. details here  https://docs.microsoft.com/en-us/azure/postgresql/concepts-backup?WT.mc_id=Portal-Microsoft_Azure_Support
