### ISSUE TITLE
Investigate solution for shared terraform state

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#1785]
In production, multiple people may need to make changes to the terraform configuration, which would require the state(by default stored in a local `terraform.tfstate` file) to be synchronized. The solution terraform offers is setting a remote backend: https://www.terraform.io/language/state/remote

Example for Azure: https://www.terraform.io/language/settings/backends/azurerm

**Comment by goldblatt** [comment]
this is blocked by needing a longer living azure instance to share state
