### ISSUE TITLE
Create template 'deploy' repository, + separate fork repositories for both Seattle & ROC

### ISSUE THREAD

**Issue by sussman** [seattle-uat/civiform#1787]
All Terraform config files should live _outside_ of the main CiviForm code repository.
Per the design for a 'federated' system:

- Create a 'template deploy' repository full of Terraform configs and general scripts
- Fork this repository into one that is **explicitly owned by ROC IT**
- Have ROC IT fill in their own Terraform values in their own repository.

Presumably the main code repository will need to include this 'deploy' repository as a submodule during checkout.

**Comment by sussman** [comment]
Based on the federated workplan:  fork seattle-uat/civiform-deploy to rochester/civiform-deploy -- then use that fork to deploy ROC.  Seattle upgrade will happen later and be more complex.

**Comment by sussman** [comment]
Assigning to Bion:  please create a standalone config repos, so that both Seattle and ROC can fork it!  If you want to make it a git submodule, that's cool.

**Comment by goldblatt** [comment]
We ended up doing a template repo within our main repo with terraform configs and then we also have a seperate deploy rrepo that checks out the relevant paths on the main repo and handles the deploy. closing this since the intention of the bug is done
