### ISSUE TITLE
Configure admin authentication to point to ROC Active Directory

### ISSUE THREAD

**Issue by sussman** [seattle-uat/civiform#1802]
Ensure that ROC admins can be authenticated against AD

**Comment by goldblatt** [comment]
so spent a while trying to set up this for staging, looks like our application asks for something call 'allatclaims' which doesn't seem to exist on the resource in staging. not super clear what that allatclaims is maybe @bion has some context. i added an api scope with 'allatclaims' and updated the manifest but couldn't get it to work by EOD. Also FWIW i think a lot of this stuff has to be done in the portal as i don't see anything in the docs https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service that reference active_directory outside of these too maybe @shubha-rajan can sanity check me though!

**Comment by goldblatt** [comment]
you can see the error on the staging instance if you log in as an admin with your google account :

Message: AADSTS650053: The application 'sgtest-full-mammal' asked for scope 'allatclaims' that doesn't exist on the resource 'xxxxxx'. Contact the app vendor.

**Comment by goldblatt** [comment]
for staging: https://github.com/seattle-uat/civiform/pull/1857 there is a readme here that should explain how roc will do this
