### ISSUE TITLE
migrate ROC program from test instance to prod

### ISSUE THREAD

**Issue by sussman** [seattle-uat/civiform#1808]
Once the ROC instance is launched in production, we need to "copy over" the carefully-designed program questions and forms from an internal dev server to the real production system.  Presumably we'd just do a SQL dump & load of some sort.

**Comment by sussman** [comment]
Seems like we already have some scripts that kind of do this -- dumping SQL data out of production AWS and into a dev instance.  We'd need to create new scripts that (1) aren't specific to AWS/GCP/Azure, just SQL in general, (2) go from any instance to any other instance.

**Comment by goldblatt** [comment]
wrote the pg_restore command to set this up and if we need to delete the tables do the connect to database and run the following commands in this order to delete the data from the database ``` DELETE FROM applications;
DELETE FROM applicants;
DELETE FROM accounts;
DELETE FROM programs;
DELETE FROM questions;
DELETE FROM ti_organizations;
DELETE FROM versions;
DELETE FROM versions_programs;
DELETE FROM versions_questions;```
