### ISSUE TITLE
Logging in to Seattle IDCS redirecting to "please contact support" page

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1824]
**Describe the bug**
I tried to login as a resident with my user name and password. I receive a message to re-login and try again. When I select "return to login page" I am directed back to the login page. But when I re-enter my user name and password, I get the error message again to re-login and try again.

**To Reproduce**
1. Go to https://civiform.seattle.gov/programs/testing_genericprogram
2. Click on "login"
3. Enter username and password (username = elisekalstad)
4. See the new error message "Please re-login and try again"
5. Click "Return to login page"
6. Click on "login"
7. Enter username and password
8. See the error message again "Please re-login and try again"
9. and repeat the cycle over and over :( 

**Expected behavior**
I would expect to be logged out of civiform when selecting "Return to login page" so that my account credentials open access to the CiviForm application. I wouldn't expect to see the cycle of "please re-login" over and over.

**Screenshots**
Attached

[Login doom spiral.pdf](https://github.com/seattle-uat/civiform/files/7893557/Login.doom.spiral.pdf)

**Comment by shanemc-goog** [comment]
Elise can you confirm a few things.

1. Has the account has been verified before and recently?  ( I assume you've used the account for a while but want to check). Were there any other changes to your account recently?

2. Do you have the issue in Staging?

**Comment by shanemc-goog** [comment]
FWIW I don't have the issue with my personal city account.

For debugging: the logout page in the PDF is the "Unverified account" one we created to detect the placeholder account in #1771

**Comment by elisekalstad** [comment]
Hi @shanemc-goog ! Thanks for taking a look. 
1. Yes, it's the same account I've used for testing forms for the past 6 months. I don't believe there have been changes to the account recently. 
2. I tested it in staging and I don't have the issue there .
3. FWIW I see now how dramatic my bug title is... "doom spiral...lol (eye roll)

**Comment by shanemc-goog** [comment]
Thanks Elise.

Can you either let us know what date/time the reported event was, or reproduce it and tell us? 

Having a concrete time touchpoint will help

**Comment by elisekalstad** [comment]
@shanemc-goog  Yes! I just did it. So timestamp at 10:51 am PT.

Thanks for changing the title @bion  :) Much better!

**Comment by shanemc-goog** [comment]
The issue looks to be that the placeholder email address can be present while a user is also authenticated between the states of requesting a password reset and doing the reset.

The original issue fix assumed that the placeholder was only used during account creation when a user, now, can't be authenticated.

The fix for users in this state is to finish the password reset flow.

The long term fix is to finish #1793 which is a priority.

**Comment by bion** [comment]
@elisekalstad is anyone still experiencing this bug?

**Comment by elisekalstad** [comment]
I haven’t heard of any others. And the fix of using the direct link to reset my password worked for me! I haven’t had any other problems and haven’t received any other issues from residents related to this.

Close it for now? What do you think?

-Elise

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>

**Comment by bion** [comment]
Yep, let's close for now.
