### ISSUE TITLE
Applicant changing answer connected to visibility condition issue

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1886]
Visibility condition bug reported by Brenda where changing an answer connected with a visibility condition and trying to go back results in errors.

Steps to reproduce:
- Set a visibility condition for a screen 
- From the applicant side, go through the form to get to the conditional screen 
- Enter data on conditional screen 
- Go back and change the original condition
- Conditional screen continues to show and has the data in it  
- If you delete the data and try to proceed it does not work if the form requires the data.  

Solution: CiviForm should delete the data entered in a conditional screen if the applicant changes the visibility condition field; sllow applicant to continue in the form.

Screenshot attached:
<img width="1186" alt="Visibility condition issue" src="https://user-images.githubusercontent.com/11811064/152847670-6b9739ba-1f90-4f68-962c-95f5a010e993.png">

**Comment by kmcnellis** [comment]
Tested with non-enumerated screens, and the bug does not appear.  It seems isolated to the enumerated questions w/ visibility conditions

**Comment by kmcnellis** [comment]
The bug also does not show up for standard questions inside an enumeration - seems to specifically be enumerations within enumerations
