### ISSUE TITLE
Export Value Defaulting to "No Export" in New Version of Question

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1889]
From Brenda: When creating a "new version" of a question, it should use the previously selected export value. Right now it just defaults back to "No export" no matter what was selected.

From Gloria: I see this as a bug and the solution being to carry over the previously selected export value into the "new version," but open to discussion if others see defaulting to "no export" as a good thing.

**Comment by clouser2** [comment]
I can look at this tomorrow. I'm going to proceed with the approach mentioned in the initial comment where we'll carry over the previously selected value for export.

**Comment by clouser2** [comment]
I wasn't able to reproduce the originally described issue. I did the following:

1) Created a new test question and test program referencing it. Published all programs
2) Navigated to the questions view and clicked "New Version"
3) Selected a different option for the export value and saved
4) Viewed the new version and observed that my selection was persisted

That said, I did notice that we don't persist the export value when creating an entirely new question. If the new question is edited before being published, we do persist the export setting in that case. I'm going to fix that issue while here.

@glorialiou If you can still reproduce the originally described issue, please let me know.
