### ISSUE TITLE
Fields with numbers - use dropdown instead of up/down arrow

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1900]
Number UI (up/down arrow) is confusing and has a small touch target. This can occur both for admins (e.g. when trying to set minimum/required # of choices) and for applicants (e.g. when trying to select how many dependents they have).

**Comment by rahaghas** [comment]
Agree with removing the up/down arrow but don't see a need for incorporating a dropdown for number fields. Users should be able to accessibly enter a number without the use of a dropdown.

**Comment by th174** [comment]
GOV.UK recommends against using `<input type="number"/>`, because it comes with various accessibility issues. Instead, it recommends this: `<input type="text" inputmode="numeric" pattern="[0-9]*">`

https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

Thoughts?

**Comment by clouser2** [comment]
Removing the stepper styling can be achieved with some custom CSS (https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp). Note that Tailwind doesn't have any easy-to-use selector for disabling these controls right now.

I'm certainly open to the pattern of using inputmode="numeric". One note is that it appears that all of the accessibility issues from the article are marked fixed as of now. I believe the remaining benefits described in that article would be:
  * Browsers discarding non-number input
  * Scrolling would no longer increment the number

I don't think there's an easy decision here without tradeoffs. One could argue that scrolling to increment could be a benefit in use cases where the number field actually represents a number.

My inclination right now would be to start by visually removing the stepper control as @rahaghas described above. I'll defer to others as to whether we want to switch to `type="text" inputmode="numberic"`.

**Comment by clouser2** [comment]
Spoke with @rahaghas, who mentioned that `type="text" inputmode="numeric"` would likely be preferable from a UX perspective as well. As such, I'll likely revert the stepper change and instead convert all `type=number` fields to follow this pattern.

Estimated effort: <1 hour.

**Comment by clouser2** [comment]
Updated estimate: 1 day

We have several parts of the code that assume that we've rendered form values with `input[type="number"]` and don't perform proper validation ([example](https://github.com/seattle-uat/civiform/blob/fa2a7e3883f1edcac13780f054f60e421ce43b4b/server/app/forms/IdQuestionForm.java#L34-L46)). These are existing tech debt that would benefit from server-side validaton. Additionally, our browser test scaffolding will need to be updated to disambiguate number inputs from id inputs ([code](https://github.com/seattle-uat/civiform/blob/fa2a7e3883f1edcac13780f054f60e421ce43b4b/browser-test/src/support/applicant_questions.ts#L108)).

Neither of these is large on their own, but I'll also need to audit for other cases where we might rely on this type.

**Comment by clouser2** [comment]
This may actually be more complicated on the admin side. Presently, we don't have any patterns for per-field validation other than top-level messages. Fixing that up would definitely be nice (and likely part of our larger effort of improving the Admin UI). However, it also increases the scope of this quite a bit. I might file a separate issue for that work (and have it prioritized accordingly). Here, we can add a distinct `FieldWithLabel.numeric` helper for the new number input mode we want that is applicant-facing.

**Comment by clouser2** [comment]
MDN documentation states that inputmode=numeric / inputmode=decimal might not show the minus key (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode). This is be problematic if we want to accept negative numbers as input. Given this and the above, I'm not sure if switching to the pattern described will buy us much over what we currently have.

@rahaghas Do you have any thoughts on keeping these inputs as type="number"?

**Comment by clouser2** [comment]
Spoke with @rahaghas. Given the above comments, we're going to stay with `input[type="number"]` rather than switching to `inputmode=numeric`.

As such, the work here is complete.
