### ISSUE TITLE
Change icon for "Text"

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1904]
The icon for/next to "Text" is unexpected and not standard. Change icon to the standard capital T for text.

**Comment by th174** [comment]
> I recommend the use of this icon: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Anotes%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

I disagree. This icon is too close to the existing icon for Dropdown questions. 
<img width="131" alt="image" src="https://user-images.githubusercontent.com/15072580/166097258-b18ae5da-f056-4994-a124-f11825c67dff.png">

Although I concede that this icon isn't very intuitive for Dropdown either.

In any case, I think the most unambiguous icon for text is this one: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atext_fields%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by rahaghas** [comment]
The icon you’ve suggested works for me as well as long as we know with certainty that there is no future admin experience that is translated to a language that does not use the Latin alphabet. As you’ve pointed out, and I certainly agree, the drop down icon is what should be changed, regardless.

**Comment by th174** [comment]
Here's a comparison of the current icons and some new ones I'd like to propose:

Old:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/15072580/166142013-149f46dc-43d2-4a67-8944-c0bf3a68c5e9.png">

New:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/15072580/166143604-261a7e2f-cdaa-440c-9217-4e1b8d3280a6.png">

Differences:
* Checkbox - Used a checkbox instead of just a check
* Dropdown - I tried using a bulleted list, but I still think it could be better
* Enumerator - The original seemed really ambiguous, so I tried using a replay symbol, to emphasize that the question repeats. 
* ID - I think the original symbol is bugged, but I replaced it with a badge
* Number - I don't think the calculator is the right symbol here. The point of the form is to support *numerical input* not *numerical computation*. I tried going with a simple number symbol.
*  Radio Button - Changed from custom circles to just a standard radio button icon
* Text - Used text with the pencil to emphasize that this question is asking for *writing text* whereas Static is for *reading text*

**Comment by rahaghas** [comment]
May want to also consider this one for dropdown: https://fonts.google.com/icons
<img width="280" alt="Line item" src="https://user-images.githubusercontent.com/103459221/166148717-d0ff2e8d-c0c5-40a8-8478-4e8c07b21e46.png">

**Comment by rahaghas** [comment]
I also feel that having the static option in here is not very intuitive as it's the only one that isn't actually an input of any kind. Might we consider offering "Add static text" that as a separate action?

**Comment by rahaghas** [comment]
For enum another idea is a list with the plus icon: https://fonts.google.com/icons?icon.query=add or what is currently there just with a plus icon in the middle: https://fonts.google.com/icons?icon.query=add

<img width="280" alt="Group 125" src="https://user-images.githubusercontent.com/103459221/166149025-cd4539e4-56cc-4fc6-9d08-fda2b760c70c.png">

**Comment by rahaghas** [comment]
Here's my overall suggestion: I think it would be beneficial to include the type of input next to each option, is it a field? is it a picker? is it an upload? I've also included the icons I think are most intuitive + simple. 

To avoid a potential issue with localization in the future I think replacing the $ with the the more generic money icon would be best.

If we include the word "field" next to "text" and remove the static option from this list, I feel the edit icon won't be necessary.

<img width="300" alt="A  Large" src="https://user-images.githubusercontent.com/103459221/166149489-52bd1d06-8e3f-489e-a780-4195ff39f604.png">

**Comment by th174** [comment]
I really like your selection of icons. Do you have a pull request for that set?

**Comment by rahaghas** [comment]
No and I'm a bit new to Github so not quite sure how to do that!

**Comment by th174** [comment]
You can fork a copy of this project, and push your own commits to it.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/15072580/166334424-0003e98b-44a5-4618-9317-f96a9dc77a87.png">

Then, you can create a new pull request from your fork to merge those commits back to the original repo:
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/15072580/166334568-67b7ef1a-441e-42cb-8c9b-904faefde095.png">

**Comment by bion** [comment]
@rahaghas no worries about making a pull request. If you can give us SVG assets for those icons we can update the code.

**Comment by shanemc-goog** [comment]
FWIW the question type names aren't intended to be localized.  The admin side isn't localized.

**Comment by rahaghas** [comment]
I think that's that's the more generic currency icon. I'm just concerned we may run into a scenario where the currency someone needs to enter is not the dollar. I recognize that we don't plan to localize, but there may still me a reason why someone would need to enter a non-dollar currency, potentially.

**Comment by shanemc-goog** [comment]
That's definitely fair.  The database model doesn't support other currencies so we'd have to do a lot of other work to support non USD, and entry etc etc so it may be ok to wait until then for a broad expansion.

**Comment by rahaghas** [comment]
makes sense! happy to keep it for now, it's certainly clearer if USD is the only thing we support anyway
