### ISSUE TITLE
Add tab UI to indicate toolbar navigation

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1906]
See here for example screenshot / more info: https://docs.google.com/presentation/d/1goxiepPXPrW3wK8wUSNoCpcf7iXIohXfj96iTYiQxo0/edit#slide=id.gf083eb9b36_0_1333

See here for what it could look like (add underline and different color to indicate current tab): https://docs.google.com/presentation/d/1goxiepPXPrW3wK8wUSNoCpcf7iXIohXfj96iTYiQxo0/edit#slide=id.g101493a1a12_0_733

**Comment by goldblatt** [comment]
also would we be able to add some stuff not in google docs to this since not everyone can access google docs!

**Comment by rahaghas** [comment]
My suggestion is to increase the font-weight of the selected tab item and and a 2px border-bottom. The border-bottom and the text should be the action color. Also, giving each tab a min-width of 160px on desktop. Here's a mock:
<img width="670" alt="Screen Shot 2022-04-22 at 5 22 47 PM" src="https://user-images.githubusercontent.com/103459221/164797351-25b2ae68-6c77-4adc-a670-a28ff15e4833.png">

**Comment by baipai** [comment]
About the google doc, agree with @goldblatt. What we did in the past is we put the file in the [public google doc](https://drive.google.com/drive/folders/1_uVkq1uOD14p19DvQzbXs2s0XhSOQjgF?usp=sharing)(wiki have that) to let everyone can access the information, not only the rolling based googler, but also gov people and community members.

**Comment by clouser2** [comment]
I can take a look at this one. The main work will be in plumbing through the "active" tab in all of the relevant views. This should be relatively low effort once that's done.

Conservative effort: 2 hours

**Comment by glorialiou** [comment]
Adding screenshots from the original Google presentation links. These presentations are quite old and quite long and the authors no longer work on CiviForm (and I don't have access control for them!), but yes moving forward where appropriate we should consider a more public avenue.
<img width="1001" alt="Screen Shot 2022-05-24 at 12 15 03 PM" src="https://user-images.githubusercontent.com/11811064/170114958-479b7006-55bd-469b-914d-21e117abbf03.png">

<img width="466" alt="Screen Shot 2022-05-24 at 12 15 23 PM" src="https://user-images.githubusercontent.com/11811064/170115128-6371d5d3-9c5e-4319-af5e-3a01ec037ce4.png">

**Comment by clouser2** [comment]
@rahaghas Is there a separate ticket tracking redesigning the nav for the program admin UI? For now, my PR updated the existing nav. Trying to figure out whether we consider this workstream complete or not.

**Comment by rahaghas** [comment]
I don't believe there currently is a seperate ticket, no

**Comment by clouser2** [comment]
Filed #2651. The issue of highlighting the active nav element is complete. We can address the navbar redesign as part of the larger Admin UI workstream.
