### ISSUE TITLE
Program admin can download ZIP files containing completed applications

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#191]
This isn't going to be very sophisticated: just download a file and store it locally. The security aspect of this isn't great, so eventually it would be better to make people view on the web, such as by linking them to the AWS bucket where it's stored, so they can view on the web w/o downloading.

**Comment by lianne-oy** [comment]
M1 Review - Based on lower priority of M2, move to M3.  Core form system is focus for M2.

**Comment by neel-a-mehta** [comment]
#650 starts this, and #664 will complete it.
