### ISSUE TITLE
Unable to exercise auth code in dev

### ISSUE THREAD

**Issue by cassandralfernandes** [seattle-uat/civiform#1938]
We use a containerized [node app](https://github.com/panva/node-oidc-provider) to simulate OIDC auth services in dev and test, but it only actually works for test mode. This means that it's not possible to exercise the real auth code in the local dev environment.

We should

1. fix the integration with the fake auth service in dev mode
2. create a means of connecting to a real auth backend in dev mode to exercise the real integration

**Comment by shanemc-goog** [comment]
I have a local working config for OIDC.
Need to find a solution for SAML.

**Comment by shanemc-goog** [comment]
Closing as the OIDC need is resolved.
