### ISSUE TITLE
Add ability to "Publish" in individual program view

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1948]
Right now, there is no ability to "Publish" (no "Publish" button) from the "Edit program" view so it's unclear how to end this program creation/editing user journey. The admin has to go back to the "Programs" tab and click on "Publish all programs," which is not intuitive. To view the details of what will be published, admin needs to go into the Versions tab. We should reduce the number of steps to review and publish.

**Comment by kristinyim** [comment]
Closing in favor of #1589
