### ISSUE TITLE
Searching for applications for Application ID/Name across all versions

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1956]
The Utility Discount Program staff find it easier to review applications within CiviForm (rather than exporting into a CSV). They need to be able to search for applications using the Application ID and/or applicant's name. They need to be able to search across all versions.

The ideal state is to use the existing search bar within the Program Admin view to search across all form versions and to be able to search by Application ID (name would also be nice, I believe this is how it is currently set up)

The current search function doesn't display results from all form versions. The user needs to click into each form version and then search. 

**Done when**
Program Admins can search and locate a single application via the Application ID. AND the Program Admin doesn't need to know which version is the current version at the time the applicant submitted the form. 
![Program Admin - Searching by Application ID_2](https://user-images.githubusercontent.com/86082659/154338045-6b9f03fc-ad7c-4d9b-ae42-37490c073e33.png)

**Comment by bion** [comment]
@elisekalstad this feature is now on staging
