### ISSUE TITLE
CiviForm Down -- Residents and Admins unable to access

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1991]
**Describe the bug**
Residents and CiviForm Admins get the error message "7mnk316em" when trying to login or complete a form. 

**To Reproduce**
RESIDENT 1:
1. Go to https://civiform.seattle.gov
2. Click on "Continue as Guest"
3. Select a program "Utility Discount Program"
4. See error, attached

RESIDENT 2:
1. Go to https://civiform.seattle.gov
2. Click on "Login"
![Error logging in_resident and admin](https://user-images.githubusercontent.com/86082659/155820098-5bb8313f-5cee-4ebc-bfe0-fc855c34a17c.JPG)

3. Login with username and password
4. Select a program "Utility Discount Program"
5. See error

CIVIFORM ADMIN:
1. Go to https://civiform.seattle.gov
6. Click on "Admin"
7. See error, attached

**Screenshots**
Attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dkatzz** [comment]
Seeing this error in the logs:

! @7mnkjikcd - Internal server error, for (GET) [/applicants/9989/programs/497/preview] ->
play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Multiple entries with same key: Enum_Household Member=services.question.types.EnumeratorQuestionDefinition@30a and Enum_Household Member=services.question.types.EnumeratorQuestionDefinition@2ee]

https://docs.google.com/spreadsheets/d/1iS78kVpUerWXkD0GOklJaTxwUcusC1KSYT7MM9zwwSk/edit?resourcekey=0-VstgnOqAEoR9jNtEGU92Ag#gid=0

**Comment by shanemc-goog** [comment]
Will have @bion pull the program data to understand what the full program configuration on MOnday

**Comment by bion** [comment]
@elisekalstad to help with debugging, have there been any changes published for the utility discount program recently?

**Comment by bion** [comment]
After pulling the program configuration from Seattle prod, determined that the cause of the issue was a duplicate draft question definition in the current draft. No programs referenced the duplicate, so deleting it resolved the issue. Will need to investigate further to determine how the duplicate came into existence, but this incident is now mitigated.

Mitigation was running the following:
```sql
DELETE FROM questions WHERE id = 747;
DELETE FROM versions_questions WHERE questions_id = 747;
```

**Comment by elisekalstad** [comment]
For root causes, I'm wondering if it was an issue of having the "Edit Questions" page open in 2 different browser windows. I was making edits to one of the questions, there's a good chance I had it open to edit in to web browser tabs.
