### ISSUE TITLE
Long names are displayed as "Anonymous Applicant"

### ISSUE THREAD

**Issue by shubha-rajan** [seattle-uat/civiform#2000]
**Describe the bug**
If your name has more than 2 spaces in it (for example, first, middle and two last names), it is not tokenized correctly and as a result, the name in the top right corner is displayed as "Anonymous Applicant".  Handling of the displayed name is done here: https://github.com/seattle-uat/civiform/blob/56dbc97751b5ade86fed62ae0072232e4c6697eb/universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java#L93-L102

**Expected behavior**
The user's full name should be displayed.

**Screenshots**
<img width="220" alt="image" src="https://user-images.githubusercontent.com/19631367/156236770-86f93cfc-2a1e-462f-b9e0-29b095468362.png">
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/19631367/156236817-4a9f7875-d414-4449-844b-2685c617f0fa.png">

**Comment by jalengg** [comment]
Hello, I'm interested in this project and would like to tackle this one if possible. I've posted an intro in the slack and mentioned this good first issue. Thanks in advance.

**Comment by alluvm** [comment]
Hey, I'm also interested in doing this. Did you start working on this @jalengg or is it still free?

**Comment by jalengg** [comment]
Hey @alluvm, I've created a fork with my solution-in-progress if you'd like to take a crack at it as well.
