### ISSUE TITLE
Applicant gets Program Application ID Number when they submit program form

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#209]
Dynamically generate an "application ID number" when the applicant hits submit. Show it on the "thank you" page once their answers are saved to the database.

**Comment by bion** [comment]
It'd be helpful to get a bit more clear about our terminology around "application" since it's used in a few different ways right now. I propose we call this "program application ID number" to indicate that it is program-specific.

**Comment by neel-a-mehta** [comment]
Yeah, the term `application' is overloaded. Sure, we can make that name change
