### ISSUE TITLE
SAML should set authority_id and lookup users by it

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#2092]
**Describe the bug**
With Accounts.authority_id in the database and CiviFormProfile.setAuthorityId() available, SamlCiviFormProfileAdaptor should call it with an appropriate ID that will never change for the logged in user.  As in OIDC #2049 

Likewise SamlCiviFormProfileAdapter.java needs to search for auth primarily as in OIDC #2104

**Comment by shanemc-goog** [comment]
@shubha-rajan can you point me at how I can I get the unique ID for SAML in SamlCiviFormProfileAdapter as I do in OIDC [here](https://github.com/seattle-uat/civiform/blob/d1f0c7390f42965372e96b584b8c9f10091360f5/universal-application-tool-0.0.1/app/auth/oidc/OidcCiviFormProfileAdapter.java#L70) . and ideally to a SAML spec that identifies it as an unchangeable identifier.

**Comment by shanemc-goog** [comment]
@zaralouis-sf want to link your PR here?

**Comment by zaralouis-sf** [comment]
Fixed by PR #2120

**Comment by zaralouis-sf** [comment]
Fixed by PR #2120
