### ISSUE TITLE
Unclear that "Next" Is really "Save & Next"

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2098]
It needs to be clear that in order for CiviForm to save a resident's answers, they need to select "Next". Is there a way to change the wording on the button so that it's clear that "next" is really a "save & next"? We have residents going back to previous pages and being confused why answers are deleted.

**Describe the solution you'd like**
Change button text to "Save & Next" or something like that!
![Save and Next](https://user-images.githubusercontent.com/86082659/159353108-2543c61d-e0b6-458b-a33c-2d9103b7aeec.png)

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by swatkat1** [comment]
To do: Update Translations accordingly.
