### ISSUE TITLE
UAT admin can localize/translate forms & questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#211]
UAT admin can see a list of languages they can localize forms into on a dedicated tab. Then they can specify localized strings for all questions in the form.

It would look something like this on the question page:
![image](https://user-images.githubusercontent.com/77128518/108777687-31d83680-7532-11eb-9551-69f08121ea1b.png)

**Comment by carolinedanzi** [comment]
This seems to be a duplicate of #778, which is nearly ready for story acceptance
