### ISSUE TITLE
Set up local S3 for dev env

### ISSUE THREAD

**Issue by hmhsu** [seattle-uat/civiform#216]
**Describe the solution you'd like**
Current local dev setup does not include connection to a S3 bucket. We should setup local S3 alternative for local development.

**Additional context**
https://github.com/localstack/localstack looks promising, especially if we are going to adopt more AWS services.

**Done when**
Done when local dev env could connect to a S3 bucket or alternative and enable feature development involving S3 (file uploads etc).

**Comment by neel-a-mehta** [comment]
@hmhsu , have we finished this?

**Comment by hmhsu** [comment]
Ah yes, this is done in #549.
