### ISSUE TITLE
Decide on color scheme / illustrations / graphic assets

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#221]
What color scheme might work with the city of Seattle? Can we get 20%ers to help make assets?

**Comment by neel-a-mehta** [comment]
I was just saying that blue/green/teal seems to be a common color for Seattle public institutions (buses, etc). Anna says kid stuff uses those colors too.

**Comment by HansEngebretsen** [comment]
^^ Correction to the above, I think we have a pretty accurate idea of what works for the city, but we'd like to do this on what works for the application in general. 

City style guide: https://app.uxpin.com/design-system/3f410cc070aa87dbff70/city-of-seattle-digital-style-guide

**Comment by neel-a-mehta** [comment]
Be sure to put this guide on the Wiki, including the key colors and fonts. Like how most orgs/companies have a "branding kit."

**Comment by HansEngebretsen** [comment]
Assigning this to @jakejwright since I don't see Holli in here, Jake can you forward on to Holli?

**Comment by neel-a-mehta** [comment]
UX team has got it
