### ISSUE TITLE
Remove duplication in ProfileAdapters

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#2229]
[SamlCiviFormProfileAdapter.java](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/auth/saml/SamlCiviFormProfileAdapter.java) is a fork of [IdcsProfileAdapter.java](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/auth/oidc/IdcsProfileAdapter.java) which contains a lot profile merging and setup logic.

A common base class can likely be extracted to reduce future errors and copying for the next auth provider.

**Comment by goldblatt** [comment]
This is still valid-- if we introduce a new profile adaptor we should work on this

**Comment by shanemc-goog** [comment]
should be pretty easy to do too.
