### ISSUE TITLE
Implement checking blocks for completion

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#224]
When applicant starts a program application, they are taken to the first block that isn't complete yet.

**Describe the solution you'd like**
Fix the stubbed implementation of `ReadOnlyApplicantProgramServiceImpl#getFirstIncompleteBlock`

**Done when**
Done when starting a new program that already has data for the first N blocks starts on N+1. for the applicant

**Comment by carolinedanzi** [comment]
https://github.com/seattle-uat/civiform/pull/399 - as soon as the tests pass I'm merging
