### ISSUE TITLE
Site renders multiple html tags

### ISSUE THREAD

**Issue by gwendolyngoetz** [seattle-uat/civiform#2257]
**Describe the bug**
When loading a page the application is creating two html tags. We should remove the outer html tag and keep the one with the lang attribute.

Example:

```
<!DOCTYPE html>
<html>
<html lang="en">

...

</html>
</html>
```

**Comment by wuteek** [comment]
Hello, I am new to Open Source and was wondering if I could try to solve this issue? Is it okay if you could provide me with more information to help me solve this? Thank you in advanced

**Comment by syntapy** [comment]
@wuteek I think you want to look in https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/views/HtmlBundle.java

Theres a couple lines there where theres an html tag. I think one of them you might wanna get rid of it

Get your dev environment set up first though (install Docker and then do run-dev etc..)

**Comment by th174** [comment]
Opened a PR to remove the extra html tag
