### ISSUE TITLE
Duplicate meta tags rendered on the page

### ISSUE THREAD

**Issue by gwendolyngoetz** [seattle-uat/civiform#2258]
**Describe the bug**

The application is adding duplicate meta tags for viewport and civiform-build-tag. The meta tags in _head_ should stay, but the _header_ ones probably need to be removed. Probably worth checking with @bion first.

Truncated example:

```
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="civiform-build-tag" content="dev">
</head>
<body>
    <header>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="civiform-build-tag" content="dev">
    </header>
</body>
</html>
```

**Comment by bion** [comment]
Yep, this looks like a bug. Good find @gwendolyngoetz !

**Comment by th174** [comment]
Made a quick PR that removes the duplicate tag
