### ISSUE TITLE
Question selection does not save

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2283]
**Describe the bug**
There is one question on a form that doesn't store the residents' correct answer. The question defaults to the first option on the radio-type question.

**To Reproduce**
1. Go to test form: https://civiform.seattle.gov/programs/testing_genericprogram
2. Navigate through the form until asked about household member
3. Enter "Spouse/Partner" as the relationship
4. Go to next page
5. Go to previous, and see that "Spouse/Partner" is correctly stored!
6. Go to review, and see that it defaulted to "Myself incorrectly

**Expected behavior**
Store the residents' original selection

**Screenshots**
Attached 
[Question delection defaults back to first one.pdf](https://github.com/seattle-uat/civiform/files/8474620/Question.delection.defaults.back.to.first.one.pdf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shanemc-goog** [comment]
@elisekalstad  do you know when this question was first made?

#2041 fixed this on 3/22, though I'm not sure when it was released for Seattle's deployment.

Any question that was already in the bad state before the deployment will continue to be so.  It needs to be removed and a new question created in it's place.

**Comment by elisekalstad** [comment]
You're right!! I re-did the question and it works great!!! Apologies for the wild goose chase.

**Comment by shanemc-goog** [comment]
The referenced question does have the corrupted state it looks like, so I suspect it's an older question.

We can see from the HTML that the last two options start repeating the IDs, which was the previous corruption issue.


```
<select value="" class="block outline-none box-border m-auto px-3 py-2 border border-gray-500 rounded-lg w-full bg-white focus:border-seattle-blue text-black text-lg placeholder-gray-500 h-12" id="HqwsJbIs" name="applicant.enumhousehold_member[0].household_member_relationshipenum.selection" placeholder="Choose an option:">
<option value="" hidden="" selected="">Choose an option:</option>
<option value="0">Myself</option>
<option value="1">Child</option>
<option value="2">Friend</option>
<option value="3">Relative</option>
<option value="4">Roommate</option>
<option value="0">Spouse/Partner</option>
<option value="1">Tenant</option></select>
```

**Comment by shanemc-goog** [comment]
Ok great.  You may need to archive that version of the question or update the description so it doesn't get reused on accident.
