### ISSUE TITLE
Show Json Data download button

### ISSUE THREAD

**Issue by goldblatt** [seattle-uat/civiform#2288]
Currently we have a way to download json data, but it is not visible from the UI

**Comment by bion** [comment]
it's below the CSV download butto
![Screenshot from 2022-04-13 11-35-17](https://user-images.githubusercontent.com/473671/163247502-70280830-b276-462f-9f78-276c31f7f870.png)
n

**Comment by goldblatt** [comment]
ahh sorry thought i had grabbed this when i deployed staging, but i had not!
