### ISSUE TITLE
404 error when downloading 1 applicant's income document

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2331]
**Describe the bug**
The admin. assistant working on the Emergency Bill Assistance program came across a 404 error for just 1 application. She tried to download the resident's income document and got the attached error. Can she retrieve the document?

**To Reproduce**
1. Log in as program admin for Emergency Bill Assistance
2. View application 12474
3. Click on income document

**Screenshots**
Attached

**Desktop (please complete the following information):**
 **- Browser [e.g. chrome**, safari]--used chrome
![Uploading 404 error.jpg…]()

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bion** [comment]
@elisekalstad the screenshot doesn't appear to be working, would you please retry uploading it?

**Comment by elisekalstad** [comment]
![Uploading 404 error.png…]()

**Comment by bion** [comment]
@elisekalstad still not working, dangit. all we need is the error code though, would you please copy the text of the error page and paste it here?

**Comment by elisekalstad** [comment]
Oh rats! Ok here it is:

This civiform.seattle.gov page can't be found. No webpage was found for the web address: https://civiform.seattle.gov/admin/programs/633/files/applicant-12474%252Fprogram-576%252Fblock-51-0%252Fimage.jpg

**Comment by bion** [comment]
@elisekalstad thank you. Are you or the admin able to download files for other applicants to the same program?
