### ISSUE TITLE
Scope out which AWS terraform resource we want to create

### ISSUE THREAD

**Issue by goldblatt** [seattle-uat/civiform#2337]
Do we want to create AWS configuration exactly matching Seattle or would we want to create an https://aws.amazon.com/apprunner/ (more similar to what we do with Roc's deployment)

**Comment by goldblatt** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_service

**Comment by goldblatt** [comment]
pricing info here https://aws.amazon.com/apprunner/pricing/ 

if we get very lil usage it could be <$50 per month

**Comment by goldblatt** [comment]
we could also use https://aws.amazon.com/elasticbeanstalk/ which does similar things

**Comment by goldblatt** [comment]
for app runner cannot use docker hub (but can put the code up on the AWS container service) and https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker.html is maybe the way to do this with elastic beanstalk

**Comment by bion** [comment]
A few thoughts:

- Whatever we can do to reduce the configuration/complexity burden for a deployment is good, all things being equal. Which definitely suggests going for something like AR or EB.
- We also need to keep costs down, but that's less of an issue so long as these services are more of a marginal increase in price vs like doubling the cost of hosting.
- Whatever solution we go with, we need to be able to ensure that our security posture isn't degraded relative to the existing AWS and Azure deployments. i.e. we need to ensure
  - The app servers are only accessible via HTTP and only accepting traffic from the load balancer and nowhere else
  - The app servers and database are in a private subnet
  - The database is only accessible from within that private subnet

**Comment by azizova-leyla** [comment]
For AppRunner available config is  2 vCPU | 4GB, but our requirements say we need 2 vCPU 8GB. Do we really need 8GB or will it work with 4?

**Comment by azizova-leyla** [comment]
Pricing with some big assumptions for EB: https://calculator.aws/#/estimate?id=d868d10768d15d7ab6ff24e7e1f34a8dd1c2f700

**Comment by goldblatt** [comment]
okay we have decided to use app runer closing this
