### ISSUE TITLE
Time rendering is fixed to Los Angeles timezone

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#2341]
**Describe the bug**
Our [visual date rendering](https://github.com/seattle-uat/civiform/blob/4ca24782255d2b1f09daf58c43408c46621b0f43/universal-application-tool-0.0.1/app/views/BaseHtmlView.java#L84) fixes times to LA.

We need to make this work correctly for any timezone.

**Comment by shanemc-goog** [comment]
FWIW this is everywhere Los_Angeles shows in our repo

![image](https://user-images.githubusercontent.com/90928876/165120356-1aed5dc4-e181-4bc4-bd7e-8d8be318f0d2.png)

**Comment by clouser2** [comment]
I can take this one.
