### ISSUE TITLE
Check timezones for date inputs for roc deployment

### ISSUE THREAD

**Issue by goldblatt** [seattle-uat/civiform#2342]
**Describe the bug**
The code base hard codes Los Angeles as the system timezone.  This may have undesired interactions such as when users enter a date, and we store that date as a UTC based time.

EG:  If they enter 2/1/22, and it's stored with an implication of PT, when it's later rendered it might be displayed as the previous/next day etc.  This might be OK, but we should verify and have it WAI for some set intention.

Just to work through an example:
Given LA is at or behind most states, the likely impact is that a date entered in Rochester (ET) will be stored as PT, and if it's rendered timezone aware it'd show as the same date but 3AM; and likely we'd not render the hours anyway.  If we had defaulted the date to ET, then it would likely cause the previous date to be shown for Seattle.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clouser2** [comment]
I don't think the system's hard-coding of Los Angeles will affect this (#2341).

However, our serialization / deserialization of dates does have potential for issues here. When serializing, we take the applicant input (e.g. 2011-01-01), treat it as UTC, and store the millisecond representation of the `Instant` as a long in the DB ([CfJsonDocumentContext.putDate](https://github.com/seattle-uat/civiform/blob/main/server/app/services/CfJsonDocumentContext.java#L111-L118)).

When de-serializing in [CfJsonDocumentContext.readDate](https://github.com/seattle-uat/civiform/blob/main/server/app/services/CfJsonDocumentContext.java#L312-L315), we do the inverse of this, but use the default system TimeZone ([Java docs](https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html#getDefault--). This may not necessarily be UTC and could be configured elsewhere in our set up.

I *believe* the correct implementation is to ensure we deserialize in UTC as well for consistency.
An alternative would be to instead store dates in their raw String representation. That said, we'd need a story for migrating any existing data.
