### ISSUE TITLE
Browser toasts don't support rendering multiple messages

### ISSUE THREAD

**Issue by clouser2** [seattle-uat/civiform#2347]
**Describe the bug**
Currently, we only support rendering a single message within a toast. When there are multiple error messages, several controllers render this as a series of sentences. An alternative may be to display them as a list (e.g. ul) so it's easier to see that they're distinct errors.

Originally from https://github.com/seattle-uat/civiform/pull/2343#issuecomment-1108806643.

**Comment by bion** [comment]
@clouser2 if it's not too much trouble please include a screenshot of the current UX, may help demonstrate why this is a bug and not a feature request

**Comment by shanemc-goog** [comment]
I think #1699 is an existing version of this issue too

**Comment by clouser2** [comment]
Indeed. #1699 tracks the exact same issue. Let's just consider this a duplicate of that issue
<img width="850" alt="Toast with multiple errors" src="https://user-images.githubusercontent.com/1870301/165166107-03b7f1e3-a078-4a1e-8886-a7bfa8473dbc.png">
.
