### ISSUE TITLE
[Maybe] Use Tailwindcss CLI (instead of Webpack) to build styles

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#235]
### How?
This would look something like:
* Adding something similar to the `build:styles` npm script to package.json in [this PR](https://github.com/distributeaid/shipment-tracker/pull/32/files)
* Adding a `npm run <our script name(s)>` command to our Dockerfile (I think)
* Removing the tailwind style import from our javascript (currently in index.js)

Part of this task is determining if we want to do this. See the Why and Why not below.

### Why?
There are a few benefits of doing this:
* No need to maintain precarious Webpack.scala + webpack.sbt code that may need work to be maintained/updated in the future
* Webpack seems to be pretty slow - this would eliminate the step of installing and building Webpack
* It's pretty awkward that the way we currently (as of #214) include Tailwindcss styles is by importing it into a javascript file that is otherwise empty. As far as we can tell, the generated javascript file pretty much just defines a string of all the styles and appends it in a `<style>` tag. Would be nicer if we could skip the JS step and just include generated CSS instead.

### Why not?
* It's possible we want Webpack for other reasons - other JS/CSS plugins we don't foresee right this moment. In that case, it might make more sense to just keep our Tailwindcss build step in Webpack.

**Comment by hmhsu** [comment]
This is done in #552
