### ISSUE TITLE
UAT admin can restore past published version

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#243]
This overwrites the currently published version and deletes the draft currently being worked on.

Remember that the *entire* UAT is versioned together; it's not like each form has a version that's independent of the rest. The whole system gets upgraded at once.

**Comment by neel-a-mehta** [comment]
Hey @bion , I just added a few more to the [`versioning` label](https://github.com/seattle-uat/civiform/issues?q=is%3Aissue+is%3Aopen+version+label%3Aversioning). Think that's sufficient?

**Comment by bion** [comment]
@neel-a-mehta yep, that's helpful. Thanks!
