### ISSUE TITLE
Question -> New Version can be done multiple times overwriting previous ones.

### ISSUE THREAD

**Issue by shanemc-goog** [seattle-uat/civiform#2497]
**Describe the bug**
Creating a New Version of an active question can be done multiple times with each subsequent one replacing previous changes.

**To Reproduce**
1. Open the Admin question page in 2 tabs
2. In Tab 1 click New Version on a question.  Make changes to that questions description then Save
Notice: the changes are shown in the Question view.
3. IN Tab 2, repeat Step 2
4. Reload tab 1s view of the Questions and notice it's changes no longer show.

The database will correctly reflect 1 "draft" question

**Expected behavior**
When New Version is selected and there's a draft in progress, load the existing draft instead of trying to make a new one.

There are very few Admin's and their mental model will want the existing draft and not to see an error that they need to reload first.

**Comment by nbeloglazov** [comment]
I'll give it a shot.
