### ISSUE TITLE
Add support for Auth0

### ISSUE THREAD

**Issue by goldblatt** [seattle-uat/civiform#2501]
We need to add support for mozilla auth0 for bloomington

**Comment by goldblatt** [comment]
assigning to bion for now, but someone else can hop in

**Comment by goldblatt** [comment]
would probably need to add: https://github.com/seattle-uat/civiform/blob/main/server/app/auth/oidc/IdcsProfileAdapter.java, https://github.com/seattle-uat/civiform/blob/main/server/app/auth/oidc/IdcsOidcProvider.java and values to https://github.com/seattle-uat/civiform/blob/main/server/conf/application.conf.

**Comment by goldblatt** [comment]
there is some documentation here: https://docs.civiform.us/contributor-guide/developer-guide/authentication-providers#adding-a-new-idp on what would need to be done

**Comment by kmcnellis** [comment]
This is just for applicant login, right?
