### ISSUE TITLE
TI can add a client

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#251]
Needs to provide Name and Date of Birth

**Comment by bion** [comment]
I think this means the TI creates a new applicant, rather than selecting an existing applicant from a list, right?

**Comment by neel-a-mehta** [comment]
Correct!

**Comment by neel-a-mehta** [comment]
@gcapiel says: "Creating an applicant requires a first name, last name and date of birth.  Email address and phone number are optional fields."
