### ISSUE TITLE
"Last updated" timestamps aren't updated for draft version when "publish all drafts"

### ISSUE THREAD

**Issue by clouser2** [seattle-uat/civiform#2513]
**Describe the bug**
When clicking "publish all drafts" with a new program, the last updated timestamp doesn't update, even though it does for already published programs.

Technically, this is working as intended from how the system is currently implemented.

**To Reproduce**
1. Go to staging.seattle.civiform.com
2. Create a new program. Observe the "last updated" time.
3. Wait 1 minute since we render timestamps at minute granularity
4. Publish All Drafts
5. Observe all already-published programs have a new "Last Updated" timestamp, while the newly created version does not

**Expected behavior**
The "Last Updated" timestamp is also updated for the draft version OR the timestamps for already published versions aren't updated.

**Screenshots**
<img width="944" alt="Screen Shot 2022-05-18 at 3 42 07 PM" src="https://user-images.githubusercontent.com/1870301/169167379-acf1a77e-7994-4f5a-99ae-591477f9c4e6.png">

**Additional context**
This is due to the fact that we create a new program entity when associating an existing program with a new version ([code](https://github.com/seattle-uat/civiform/blob/75bc407f70d51feb4e9e8d832aff8f197ca34cab/server/app/repository/VersionRepository.java#L82)).

A quick workaround is to also perform a save on the draft program versions as well.

**Comment by goldblatt** [comment]
would love to get more info on how much timestamps are used @kristinyim

**Comment by shanemc-goog** [comment]
`This is due to the fact that we create a new program entity when associating an existing program with a new version`

Just wanted to clarify this, During publishing, if a Program doesn't already have a new draft associated revision we don't create a new revision (outside of updating the timestamp). What is happening is that we're adding to the M:M relationship between the unchanged Active associated program revision and the Draft in the versions table (via versions_program table) and pac4j/ebean treat that as an Update of the program row.

This is technically incorrect since the program configuration didn't change, but a side effect of using the ebean annotations to manage it automatically.

**Comment by shanemc-goog** [comment]
For the overall issue, I think it's likely more correct UX to show the Published time for programs that actually had changes; that is those associated with the Draft revision before the publish action.

**Comment by clouser2** [comment]
> For the overall issue, I think it's likely more correct UX to show the Published time for programs that actually had changes; that is those associated with the Draft revision before the publish action.

I'm not sure I follow. If we're implicitly updating timestamps for programs not associated with the draft revision due to the pac4j bug, it seems confusing to not also ensure the timestamps are updated for programs that were associated with the draft revision. Given that one of the purposes of these timestamps is to aid in debugging, I'd assume that having inconsistency there could lead one to have to ponder why "unedited" programs were considered updated more recently than "edited" programs after the publish. If we were to find a way to disable the auto-update of the timestamp when updating the M:M relationship, then I don't think we'd need to apply any workarounds.

I've merged a fix for this. If there's a different direction I should take this fix, please let me know and I'm happy to try and rework.

**Comment by kristinyim** [comment]
I asked Seattle about this today and they would really like a versioning system that includes when something was last updated and why. Right now, they have an external doc that tracks these things so when a program asks about a change they have documentation. I think Shane is right is that this can just be a cosmetic fix for now but something to think about for later.
