### ISSUE TITLE
UAT admins can invite TIs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#252]

**Comment by neel-a-mehta** [comment]
TIs are going to be invite-only, so they can't create accounts at whim. UAT admins have to invite them / initialize accounts for them.

**Comment by lianne-oy** [comment]
UAT admins can configure who is a TI.  If they pick someone w/o an account yet; account is waiting (using provided TI email) for them until they create an account.  But no email is sent to invite.

Leaving open for when we have email working.
