### ISSUE TITLE
Unable to open docs for 1 application 

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2547]
**Describe the bug**
There is one application (#13665) where none of the program admins can open any documents--the documents are for Government ID and Income Verification, they are JPEGs and PDFs. The staff can view the application, but when then go open the uploaded documents, the page goes blank and the whole application goes away.

Staff mentioned that this has happened before and it's usually when a resident has previously submitted an application. They then search for the original application and can pull the documents. But this one looks to be the first application that the resident submitted.

**To Reproduce**
1. Search for application #13665
2. Click to download the documents in the application (gov ID and income)
3. See that page goes blank and application disappears

**Comment by kristinyim** [comment]
Going to leave this for Seattle to investigate. Please let us know how it goes and if you would like to escalate.

**Comment by elisekalstad** [comment]
Fixed with July deployment
