### ISSUE TITLE
De-duplicate logic for file upload views

### ISSUE THREAD

**Issue by clouser2** [seattle-uat/civiform#2589]
Presently, we have Azure and AWS-based file upload strategies that contain a fair amount of duplication for rendering the applicant-facing UI. This duplication has led to bugs where functionality is only implemented in one strategy but not the other (#2487). We can likely consolidate a fair amount of the logic and tie it in with our other rendering strategy used for other question types.

**Comment by kristinyim** [comment]
Going to be addressed in fix-it week.

**Comment by clouser2** [comment]
Work here is complete!
