### ISSUE TITLE
emailField should call `.email()` instead of `.input()` in EditTrustedIntermediaryGroupView.java

### ISSUE THREAD

**Issue by syntapy** [seattle-uat/civiform#2762]
**Describe the bug**
Just make that teeny change over [here](https://github.com/seattle-uat/civiform/blob/main/server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java#L76) as mentioned [here](https://github.com/seattle-uat/civiform/pull/2281#discussion_r899358717)

**To Reproduce**
1. Open the text editor / IDE and look at the file

**Expected behavior**
File should look different

**Comment by cindychangy** [comment]
I can make this change :)
