### ISSUE TITLE
In deploy scripts for AWS don't allow names with a dot

### ISSUE THREAD

**Issue by azizova-leyla** [seattle-uat/civiform#2806]
It breaks s3 bucket certificates, and might have other issues. Prefer - or _.

Add a check in our scripts for this.

**Comment by gwendolyngoetz** [comment]
I'd suggest we enforce hyphens (-). I've seen conflicting information before that underscores (_) may have problems in domain names.

**Comment by azizova-leyla** [comment]
Brett, can you take a look at this? Both for setup and deploy (ideally in a shared place somewhere)

**Comment by clouser2** [comment]
Sounds good.

@azizova-leyla  To clarify, when we say "name" here, we mean the identifier for an AWS entity/resource that we're going to create, correct?

**Comment by azizova-leyla** [comment]
Correct. And those are usually concatenated from a user provided variable in the config, and the name in .tf file that we put in. 
You might need to check those separately, checking user provided values would be my first priority.

Terraform does create a terraform_plan file that should have the final identifiers for everything, but I'm not sure how to easily check just the names from it.

**Comment by clouser2** [comment]
I took an initial look at this. We can address this with a multi-pronged approach:

1. Add top-level validation for user-provided values that prevent dots. We could likely just make the regex [a-zA-Z0-9-] for consistency.
2. Attempt to validate all resource names that terraform will create prior to calling terraform apply.

#1 is likely sufficient to consider this workstream complete and will prevent a large source of user errors. However, it doesn't fully prevent us from errantly creating a resource with name `{user_provided_value}.somereourcewithanerrantdot`. For that, #2 would serve as a stop-gap.

## 1. Top-level validation

Terraform already has support for this through custom validation rules that can be used as part of the variables.tf file ([docs](https://www.terraform.io/language/values/variables#custom-validation-rules)). That said, we'd prefer to print an error message that we control as early as possible. It'd likely be nice to set regexes on these on the off-chance that someone runs terraform apply not through our scripts. That said, it's probably lower priority.

Instead, we can update our `variable_definitions.json` ([code](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/templates/aws_oidc/variable_definitions.json)) to also include an optional regexp for validation (and a field indicating a custom error message to be shown when this validation is failed). This can be consulted during our typical validation and an error message can be shown early in the process ([code](https://github.com/seattle-uat/civiform/blob/2a6398564779835294331a45b9768d77782df069/cloud/shared/bin/lib/config_loader.py#L70-L76)).

## 2. Validate terraform resource names

I believe we can achieve this through the following:
* `terraform plan -out=plan.terraform` - Generates a plan file. Initialize this with an empty state file so it would create a plan for *all* resources
* `terraform show -json plan.terraform` - parses the binary output from the previous `plan` command into humand-readable JSON.
* Use `jq` ([link](https://stedolan.github.io/jq/manual/#Basicfilters)) to extract all "name" attributes and confirm that it matches the regexp we care about (`jq '..|.name?'`)

If we apply this sequence of steps prior to calling `terraform apply` in our scripts, we should catch the majority of errors of this type.

Assuming no objections, I'll likely start this tomorrow.

**Comment by clouser2** [comment]
After some more investigation, it turns out that `terraform plan` / `terraform apply` will already raise an error if an invalid resource name is encountered:
```
│ Error: only alphanumeric characters and hyphens allowed in "name": "clouser2.something-lb"
│
│   with module.ecs_fargate_service.module.ecs-alb.aws_lb.lb,
│   on .terraform/modules/ecs_fargate_service.ecs-alb/main.tf line 27, in resource "aws_lb" "lb":
│   27:   name                             = "${var.name_prefix}-lb"
```

Given this, there's not really a need to try and validate the terraform resource names (item #2 above) since terraform will already fail before creating the resources. As such, performing top-level validation (e.g. #1 from above) should be sufficient.
