### ISSUE TITLE
Create GTM FAQ for partners

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#286]
What will we require from program admins? From UAT admins? From TIs? Who will manage these things? What's the budget required?

**Comment by lianne-oy** [comment]
Pushing to next Milestone - still Lianne and Jake working on this and intent is to create someing that can answer qs for business leads in the city for potential operational changes.

**Comment by lianne-oy** [comment]
Here is draft - we will have this complete by M4.

https://docs.google.com/document/d/1Ap34Fk_usci0oPrYZBCF2Q1alijI4w6FYu2d4H3LS8o/edit?hl=en#
