### ISSUE TITLE
Set up integrations with Amazon SNS/SES

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#287]
Per #174, we will use AWS's Simple Notification Service and Simple Email Service. Find ways to enable/integrate them.

* https://aws.amazon.com/sns/
* https://aws.amazon.com/ses/

**Comment by ndmckinley** [comment]
Reopening since we should probably get Neel involved in deciding whether there's any chance we'll get to this - strikes me as an icebox issue rather than a closed one, sorry, I misspoke in standup today.  Our SNS integration is in good shape but we don't have an SES integration at all.
