### ISSUE TITLE
AWS TF security improvements

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#2934]
- [ ] Looks like RDS ingress is open to [anyone on the Internet](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/templates/aws_oidc/vpc.tf#L83-L88). Is this required, or can this be locked down?
- [ ] It is recommended to set enable_key_rotation = true ([TF doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_key)) for all created KMS keys like [civiform_kms_key](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/modules/setup/secrets.tf#L4-L11), [backend_storage_key](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/modules/setup/backend_storage.tf#L19-L26), and [file_storage_key](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/modules/setup/secrets.tf#L4-L11).
- [ ] It is recommended to export significant [CiviForm database](https://github.com/seattle-uat/civiform/blob/main/cloud/aws/templates/aws_oidc/main.tf#L24-L43) events to CloudWatch for visibility (by setting the enabled_cloudwatch_logs_exports attribute).

**Comment by azizova-leyla** [comment]
Maybe useful reference from Seattle's deployment: https://github.com/seattle-uat/civiform-deploy/tree/main/infra

**Comment by nbeloglazov** [comment]
Question limiting ingress traffic, wouldn't DB be accessible only from within VPC anyway? From public internet it should be impossible to get hold of db address/ip.  Though limiting ingress wouldn't hurt.

**Comment by azizova-leyla** [comment]
Correct, this is an extra measure to also limit ingress. DB shouldn't be accessing from public internet at all.
