### ISSUE TITLE
Let CiviForm admin specify "transformations" of fields

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#294]
In the form builder, let the CiviForm admin add some simple scripting or logic to transform the inputted data. For instance, if the applicant put in their date of birth, the admin could specify a transformation like `age = TODAY() - birthdate` to compute their age. Or the admin could redact all but the last 4 digits of an applicant's SSN.

This isn't strictly necessary, since program admins can do calculations on Excel on their side, but it would be a big boost for admins who are less comfortable with Excel.

**Comment by bion** [comment]
In what context is this transformation taking place? Is this part of export?

**Comment by neel-a-mehta** [comment]
I imagine the UAT admin would specify transformations in the form builder. But the transformation would only be applied on export.

**Comment by neel-a-mehta** [comment]
Generally I think we want to minimize complexity of the application, so I'm iceboxing this because the admin can always do transformations (more efficiently than on our app, I might add) on Excel.
