### ISSUE TITLE
Investigate template/fillable PDF fields in Adobe Acrobat

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#319]
We think that Acrobat lets you name and specify certain fields as fillable on your PDF. Then there should be a library that lets you read those fields. Confirm!

**Comment by neel-a-mehta** [comment]
@bion is anyone researching this? 

cc @gcapiel

**Comment by bion** [comment]
@neel-a-mehta A couple devs have looked into it a little bit. I've implemented PDF filling a couple times in other programming languages. Fields are identified by their "name" property and can be edited using Adobe acrobat: https://helpx.adobe.com/acrobat/using/pdf-form-field-properties.html

Whatever library we use will allow us to specify fields by name for filling.
