### ISSUE TITLE
Dark mode for UAT admins, at least

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#359]
Optionally can extend to other user groups, but UAT admins will be spending a *lot* of time in the app and so would benefit lots from dark mode.

**Comment by HansEngebretsen** [comment]
https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457355651939996&cot=14 

This is done, do we need one for light mode? (we only have dark mode here)

**Comment by neel-a-mehta** [comment]
Eh, if we're going to default to dark mode, we don't need a light mode. I'll mark this one as closed
