### ISSUE TITLE
Make applicant-facing forms resilient to CSRF

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#363]
@bion is less worried about this one: "I'm inclined to let the city do that one since it's more effort and I'm confident we're defended against it."

**Comment by ndmckinley** [comment]
This is defended against by the CSRF filter in Play - every form has an anti-CSRF tag.  I'm inclined to close this - @neel-a-mehta do you want this open for the security scan?

**Comment by ndmckinley** [comment]
Closing based on discussion in standup.
