### ISSUE TITLE
Make applicant-facing forms resilient to SQL injections

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#364]

**Comment by ndmckinley** [comment]
I do not think that a sql injection attack has any chance of succeeding unless it takes advantage of a vulnerability in ebeans, and the CVE database doesn't record any instances of that happening in the past.

**Comment by ndmckinley** [comment]
I'm inclined to close this @neel-a-mehta - do you want to leave it open until the security scan completes?

**Comment by neel-a-mehta** [comment]
I think it's fine to close this one out -- we'll let the security scan tell us if we need to reopen.
