### ISSUE TITLE
UAT admins can specify configuration options for questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#376]
This doesn't mean that each individual configuration option has to be built out. It just means that UAT admins should have the ability to specify configuration options in general.

**Comment by lianne-oy** [comment]
More work needed to validate - moving to M6.

**Comment by lianne-oy** [comment]
Multi option questions are implemented; but needs additional work for each question type in the future.  Closing and will need to reopen new issue for additional question types needed (once known).
