### ISSUE TITLE
UAT admins can specify validation rules for questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#377]
This doesn't mean that each individual validation rule has to be built out. It just means that UAT admins should have the ability to specify validation rules in general.

**Comment by natsid** [comment]
Remaining (but in-progress) dev tasks for this: #589 and #590.

**Comment by natsid** [comment]
This story is complete in a general respect.

That is, an admin is able to specify a handful of custom validation configs (min and max length for text questions, min and max value for number questions, and disallowing PO boxes for address questions).

**Comment by natsid** [comment]
It is now relatively straightforward to add further validation configs (and other type-specific configs) for the types mentioned in the last comment, as well as all the other existing types.

**Comment by lianne-oy** [comment]
This issue is closed; bugs will be added to future Milestone.
