### ISSUE TITLE
"Text" question type: implement bare bones

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#388]
Make it possible for UAT admins to create, and for applicants to fill out, questions of this type. Answers should be saved to a database. Configuration options and validation criteria aren't necessary yet. 

![image](https://user-images.githubusercontent.com/77128518/110535312-181c1f00-80ee-11eb-8dd4-f4d93ddc2918.png)

See context for question types at https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes

**Comment by natsid** [comment]
The `text` question type, as described above (no validation or extra configuration), is implemented.
