### ISSUE TITLE
"Text" question type: implement simple validation criteria

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#390]
Main issue for the Text question type is #388, so see that first.

This includes:
* Min length (in characters)
* Max length (in characters)

**Comment by hmhsu** [comment]
This should be done now.

**Comment by natsid** [comment]
Are you sure this is complete @hmhsu ? Before I went OOO last week I was still working on displaying the admin-configurable text validations to the applicant and did not complete it.

**Comment by natsid** [comment]
Ohh, I just noticed #544 which I think covers it.
