### ISSUE TITLE
"Checkbox button set" question type: implement bare bones

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#396]
This question type creates a list of checkboxes. Applicants may pick one or more choices, depending on how the admin configured the question.

![image](https://user-images.githubusercontent.com/77128518/110537618-ece6ff00-80f0-11eb-8347-95034644d0f6.png)

Make it possible for UAT admins to create, and for applicants to fill out, questions of this type. Answers should be saved to a database. Configuration options and validation criteria aren't necessary yet.

See details at https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes

**Comment by neel-a-mehta** [comment]
[See this wiki page](https://github.com/seattle-uat/civiform/wiki/Adding-a-new-question-type) to learn how to add a new question type to the codebase!

**Comment by carolinedanzi** [comment]
(Milestone 4 review): This is in progress and will most likely be out for review 04/05 or early 04/06
