### ISSUE TITLE
"Address" question type: implement bare bones

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#398]
This question type creates another multi-part widget with several fields, each corresponding to a different component of a United States address.

![image](https://user-images.githubusercontent.com/77128518/110540955-1e61c980-80f5-11eb-8622-3ab1b7ae5995.png)

Make it possible for UAT admins to create, and for applicants to fill out, questions of this type. Answers should be saved to a database. Just implement the sub-fields; configuration options, validation criteria, and custom functionality aren't necessary yet.

See details at https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes

**Comment by neel-a-mehta** [comment]
## Sub-fields

Address line 1 (required)
- This usually corresponds to a street address or P.O. Box number.
- Implement as a text field.

Address line 2 (optional)
- This usually corresponds to a unit or apartment number, 
- It’s considered good UX practice to hide this field behind a button or link: make the user hit a button to reveal this field. This stops people from instinctively typing their city into this field.
- To reduce confusion, explicitly mark this as optional.
- Implement as a text field.

City (required)
- Implement as a text field.
- State (required)
- Implement as a dropdown.
- Include:
- All 50 states
- The District of Columbia (DC)
- The 6 outlying territories: American Samoa (AS), Guam (GU), Northern Mariana Islands (MP), Puerto Rico (PR), US Minor Outlying Islands (UM), and US Virgin Islands (VI)
- Armed forces address codes: Armed Forces Americas (AA), Pacific (AP), and others (AE)
- Offer both the full name and the postal abbreviation for easier skimming, such as “CA - California”.
- WA may want to be called “Washington State” to distinguish from Washington, DC.

ZIP (required)
- Implement as a text input field that only supports digits, and with a required length of 5.
- Avoid implementing as a plain old number field, since some ZIP codes start with a “0” (e.g. 02110 for Boston).

**Comment by natsid** [comment]
One thing we are currently missing from our Address question type in our data model is "Address line 2".

**Comment by natsid** [comment]
I would say the "bare bones" of the address question type is complete. Should we open a new issue for "Address line 2"?

**Comment by neel-a-mehta** [comment]
Yeah, Address Line 2 is still a requirement, but it's fine to make that its own issue. I'll go do that quickly.
