### ISSUE TITLE
"Repeater" question type: implement bare bones

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#405]
The Repeater Question type will be used to ask applicants for an arbitrary number of repeated entities (children, household members, jobs, cars, etc.). Admins will be able to create Repeated Questions for each Repeater Question (#612), and add these to program blocks. Applicants will be asked Repeated Questions for each repeated entity the applicant lists (#613).

![image](https://user-images.githubusercontent.com/77128518/110679068-0b0e3700-81a5-11eb-97e2-13dd85759eaa.png)

In the future it’d be great to import the text typed into these fields into questions in the repeated blocks -- for instance, applicants type their children’s first names into the multi-text question, and those first names auto-fill into the Name questions when it comes time to fill in details about each child. But that adds a lot of complexity to the UAT admin experience (they have to drill deep into the data model to show what field the text inputs correlate with), so it’s better to leave off for v1. 

(Also, there are edge cases where two household members have the same name, so auto-filling information might get messy.)

Make it possible for UAT admins to create, and for applicants to fill out, questions of this type. Answers should be saved to a database. Just implement the sub-fields; configuration options, validation criteria, and custom functionality aren't necessary yet.

See details at https://github.com/seattle-
uat/universal-application-tool/wiki/Question-type-requirements-notes

See more details at 
https://docs.google.com/document/d/1jkbFPzG_whZ1AqZVmxmkGuoqR5wRdG817COX5usPAWo/edit#heading=h.vkhepsgmicsf

**Comment by neel-a-mehta** [comment]
Subfields: 

Nickname fields (required)
- Implement each as a required text input field.
- Applicants can add/delete fields. There can never be less than 1 field; if the applicant has 0 items to report, they can just hit “skip” instead.

**Comment by neel-a-mehta** [comment]
[See this wiki page](https://github.com/seattle-uat/civiform/wiki/Adding-a-new-question-type) to learn how to add a new question type to the codebase!

**Comment by lianne-oy** [comment]
In progress, moving to M5.
