### ISSUE TITLE
"Number" question type: implement simple validation criteria

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#409]
Let the admin specify:

- Minimum value
- Maximum value

When building a question of this type.

See #392, the parent issue for this, and [this wiki page](https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes) for details.

**Comment by natsid** [comment]
Oops, I guess I shouldn't have closed this quite yet.

This story is ready for story-acceptance testing.

**Comment by neel-a-mehta** [comment]
Good to go, but we identified some bugs (tracked in other issues).
