### ISSUE TITLE
"Enumerator" question type: implement simple configuration options

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#425]
Let the admin specify:

![image](https://user-images.githubusercontent.com/77128518/110679377-693b1a00-81a5-11eb-9d4f-8185f5db50c9.png)

- Placeholder text in the nickname field. In the mockup above, this would be “Full name.”
- Name of the type of item. In the mockup above, this would be “Member.” This text is shown after the word “Add” on the plus button.

when building a question of this type.

See #405, the parent issue for this, and [this wiki page](https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes) for details.

**Comment by neel-a-mehta** [comment]
#859 is the eng task for part of this.

To clarify the latest requirements, from @kendrickt :

> I think we could have two admin-configurable strings here, and we need to pick some good defaults.
> The first is the placeholder text in the input field itself. This could default to the empty string.
> The second string would be for "element". This would change what the add button says, and what the aria label for the delete button has.

IMO, String 1 could default to the empty string or "Name"; String 2 could default to "Item".

**Comment by kendrickt** [comment]
The dev issues is #859

**Comment by neel-a-mehta** [comment]
Doing story acceptance review.

1. On Staging, creating a "Pokemon in your party" enumerator. Each item will be called a "Monster."

![image](https://user-images.githubusercontent.com/77128518/118163446-fc840c00-b3ef-11eb-89d3-7324538e4d3e.png)

2. Adding some repeated questions nested under that.
3. Creating a program that uses that enumerator and its questions.
4. Publishing!
5. Logging in as guest applicant now.
6. Starting the form.
7. Label on the button gives the item name that I was expecting.
![image](https://user-images.githubusercontent.com/77128518/118163669-3f45e400-b3f0-11eb-8691-402a7775dcdb.png)
8. New fields say "Nickname for Monster" as a placeholder, which I like.
![image](https://user-images.githubusercontent.com/77128518/118163701-4cfb6980-b3f0-11eb-8ea7-74a0d137f2f5.png)
9. Hitting Save to start entering repeated info.
10. The review screen shows exactly what I expect.
![image](https://user-images.githubusercontent.com/77128518/118163791-68667480-b3f0-11eb-9060-354415934301.png)

Approved! ✅
