### ISSUE TITLE
"Repeater" question type: implement simple custom functionality

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#433]
#405 is the main issue for this. We'd like to add some custom functionality to this question type:

- There is a plus button that applicants can use to add items, up to the maximum allowed number.
- Next to each nickname field is a delete button that removes an item. The delete buttons disappear if the applicant has hit the minimum number of allowed items, and reappear once they’re above the minimum.

**Comment by lianne-oy** [comment]
Moving to M5; in progress.

**Comment by lianne-oy** [comment]
Bion:  Should set a global max of 20 (?).  Punt until whole feature is usable (nice to have).
