### ISSUE TITLE
Make ErrorAnd constructors private

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#443]
**Describe the bug**
The [`ErrorAnd`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/ErrorAnd.java) constructors don't have enough generic context to disambiguate a result that is an `ImmutableSet<T>` and errors of type `T`. Consider:

```
    ImmutableSet<String> result = ImmutableSet.of("a", "b", "c");
    ErrorAnd<ImmutableSet<String>, String> errorAndResult = new ErrorAnd<>(result);
```

The resulting `errorAndResult` will have errors and no result because the first constructor it matches is the `ErrorAnd(ImmutableSet<E> errors)` constructor. 

Thankfully, the public static methods that create `ErrorAnd`s have enough generic context, and we should be using them anyways.
 

**To Reproduce**
(in branch https://github.com/seattle-uat/universal-application-tool/tree/errorand-bug)

Add this test to `services.ErrorAndTest`, and it will fail.
```
  @Test
  public void resultIsImmutableSet() {
    ImmutableSet<String> result = ImmutableSet.of("a", "b", "c");
    ErrorAnd<ImmutableSet<String>, String> errorAndResult = new ErrorAnd<>(result);

    assertThat(errorAndResult.hasResult()).isTrue();
    assertThat(errorAndResult.isError()).isFalse();
  }
```

**Expected behavior**
The `ErrorAnd` constructors are private and only the public static methods that construct `ErrorAnd`s are used (`ErrorAnd#error`, `ErrorAnd#errorAnd`, `#ErrorAnd#of`). 

Tests should be added to ensure the public static methods can disambiguate `ImmutableSet<T>` results from errors of type `T` when using `ErrorAnd.errors` and `ErrorAnd.of`.

**Comment by Snackeroo** [comment]
@Snackeroo and @hmhsu are working on this issue.
