### ISSUE TITLE
Unguarded `get`s need to be guarded.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#444]
**Description**
Calling the `get` method from  `Optional`, `Map`, and `List` classes can throw runtime exceptions or return nulls. We have lots of `get`s that are not checked, and these `get`s need to be guarded by checking `Optional#isEmpty`, `Map#containsKey`, and `List#size` when appropriate.  

**Desired outcome**
All `Optional#get` and `Map#get` calls are guarded by checks. If a value needed is not available, a 4XX-level HTTP status code should be returned to the user if it is the result of bad user input, or a `RuntimeException` should be thrown if it is the result of a bug in the system.

For an example see: #434 

**Additional context**
A good place to start would be `grep \.get\( app/* -R --include="*.java"`. Not all of these are bad `get`s!

**Comment by Snackeroo** [comment]
Working on this.

**Comment by hmhsu** [comment]
Thanks for picking this up. There may be some complexity in terms of handling asynchronous exceptions. Let me know if you have any questions!

**Comment by kendrickt** [comment]
[DONE-ish]

Closing this because we don't need to track this any more. If bugs pop up for specific unprotected `get`s, we can create new issues as the come up.
