### ISSUE TITLE
Refactor tests to seed programs with blocks with `ProgramBuilder` where appropriate.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#445]
**Is your feature request related to a problem? Please describe.**
We are inconsistent in seeding programs and blocks for testing. There's now a [`support.ProgramBuilder`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/support/ProgramBuilder.java) available in tests that can be used to fluently seed programs with blocks.  

**Describe the solution you'd like**
Standardize the use of `ProgramBuilder` across the tests. 

The programs built should only contain the relevant pieces for the test in scope. For example, if a test only checks that the program's name is present, then only use `ProgramBuilder#newProgram("program name")`. That will help keep unused raw strings from cluttering our tests. If it makes sense to test that program description is also present, then add the assertion and use `ProgramBuilder#newProgram("program name", "program description")`.

There may be some tests where it doesn't make sense to use `ProgramBuilder` to seed programs with blocks (e.g. [`ProgramServiceImplTest`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java) tests programs can be created and blocks can be added via the service).

**Additional context**
See #403 for the PR that added `ProgramBuilder` and includes refactoring of some of the tests to use it.

This would be best done in tandem with #447 

**Done when**
Tests consistently use `support.ProgramBuilder` to seed programs with blocks. The [`ResourceCreator.insertProgram`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/support/ResourceCreator.java) and `ResourceCreator.insertProgramWithOneBlock` are deleted. The [`ProgramService`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/program/ProgramService.java) and [`ProgramRepository`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/repository/ProgramRepository.java) should not be used by tests to seed programs.

**Comment by thomasphung** [comment]
I could look into this.

**Comment by kendrickt** [comment]
[DONE-ish]

Closing because most things use `ProgramBuilder` now, and we don't need to track this.
