### ISSUE TITLE
Refactor tests to seed questions with `support.Questions` where appropriate.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#447]
**Is your feature request related to a problem? Please describe.**
We are inconsistent in seeding questions for testing. There is now a cached [`support.Questions`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/support/Questions.java) question bank available in tests that can be used to standardize and share questions between tests.

**Describe the solution you'd like**
Tests that need questions use `support.Questions` to seed questions. If more questions need to be added, add them to `support.Questions`. 

There may be some tests where it doesn't make sense to use `support.Questions` (e.g.  [`QuestionServiceImplTest`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java) tests creating questions, so they shouldn't be pre-seeded).

**Additional context**
See #446 for the PR that adds caching to `support.Questions`.

This would be best done in tandem with #445 

**Done when**
Tests consistently use `support.Questions` for seeding questions. The [`ResourceCreator.insertQuestion`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/support/ResourceCreator.java) is seldom used or not used at all. Ad-hoc question creation is not used at all. The [`QuestionService`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/QuestionService.java) and [`QuestionRepository`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/repository/QuestionRepository.java) should not be used by tests to seed questions.

**Comment by davidrhallartificialeducation** [comment]
Picking this up now

**Comment by kendrickt** [comment]
[DONE-ish]

Closing because most things use `ProgramBuilder` now, and we don't need to track this.
