### ISSUE TITLE
"ID / account number": implement simple validation criteria

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#463]
Let the admin specify the following validation criteria when building a question of this type:

- Maximum length
- Minimum length

See #453, the parent issue for this, and [this wiki](https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes) page for details.

**Comment by lindsayzad** [comment]
Relevant to orca launch: The form requires a child's school id, which should be exactly 7 numbers long

**Comment by lindsayzad** [comment]
Duplicated in #1616 
Closing this issue, as the other has more detail and related user testimony
