### ISSUE TITLE
Enable MFA/2FA for Active Directory (AD) to authenticate city staff and TIs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#470]
@bion was saying that multi-factor authentication may be needed to authenticate city staff, who will have access to data about children. May be needed for TIs, too. May be mandatory given that we're collecting data about children and ages. We would thus need to *require* MFA for these users. These users would log in with AD.

@ndmckinley said that the city hasn't configured IDCS to use MFA yet, though we could easily use it if they turned it on. Unclear if we will require MFA for applicants though.

**Comment by ndmckinley** [comment]
MFA is turned on for AD users - @neel-a-mehta your call whether we should keep this issue open or move it around, given that.  Arguably our "bare essentials" part of this is done.

**Comment by neel-a-mehta** [comment]
Great! I think we're good here then.
