### ISSUE TITLE
Change our default Locale from ENGLISH ("en") to US ("en-US")

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#473]
**Describe the solution you'd like**
We should update our application's default locale to "en-US". This involves:

1. Change the locale list in `application.conf` to use "en-US" instead of "en"
2. Change `messages.en` to `messages.en-US` (note: use hyphen, not underscore)
1. Update the default locale in `ApplicantData` from Locale.ENGLISH to Locale.US
1. Update our test data for questions to use Locale.US instead of Locale.ENGLISH
1. Find and replace all other instances:
    1. Locale.ENGLISH --> Locale.US
    2. "en" --> "en-US"

**Additional context**
For more on Play's i18n structure, see https://www.playframework.com/documentation/2.8.x/JavaI18N

To test:
1. Run `bin/run-dev` to start the application
2. Navigate to http://localhost:9000
3. Select "Guest" login
4. View the program list page - you should see the page heading as "Programs"
5. In Chrome, look at the cookies - there should be one called PLAY_LANG and it should be set to "en-US"

**Done when**
When the app is running locally, the PLAY_LANG cookie is set to "en-US" rather than "en" and the page title for http://localhost:9000/applicants/1/programs is "Programs", not "title.programs" (this shows the messages are pulled correctly)

**Comment by Snackeroo** [comment]
@Snackeroo I am working on this issue.
