### ISSUE TITLE
Add a getBlockBefore() method to ReadOnlyApplicantService

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#479]
**Describe the solution you'd like**
We would like a `getBlockBefore` method on [`ReadOnlyApplicantProgramService`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java) so that we can eventually implement a logical back button. Implementation steps:

1. Add `getBlockBefore` to the [`ReadOnlyApplicantProgramService`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java) interface
2. Implement `getBlockBefore` in [`ReadOnlyApplicantProgramServiceImpl`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java) - this should find the Block in the `getCurrentBlockList` and return the previous Block in that list, if it exists. Reference `getBlockAfter` for help
3. Write unit tests for the service impl class

**Done when**
There is a `getBlockBefore` method implemented for the read only applicant service

**Comment by bion** [comment]
This is blocked pending discussion with design about back behavior.

**Comment by carolinedanzi** [comment]
Closing this  issue - we do not need this at the moment
