### ISSUE TITLE
Set up localstack.cloud so our browser tests can upload files locally

### ISSUE THREAD

**Issue by hmhsu** [seattle-uat/civiform#482]
**Is your feature request related to a problem? Please describe.**
Our local dev environment does not connect to a dev S3.

**Describe the solution you'd like**
Integrate local dev environment with [localstack](https://github.com/localstack/localstack) so we have a dev S3 and store files locally.

**Additional Context**
[`AmazonS3Client.java`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/repository/AmazonS3Client.java) implements the logic to connect to a AWS S3 bucket. The client is only active when relevant [config](https://github.com/seattle-uat/civiform/blob/17cf42e64bb440d0ff783b5114cbc1a2bfb57df3/universal-application-tool-0.0.1/conf/application.conf#L387) is set. Local dev environment currently does not set this config.

We want to setup a fake S3 with localstack and point default local config to it.

**Done when**
Done when we have browser tests that verify that our app can store files locally.

**Comment by syntapy** [comment]
Is the s3 bucket in the `infra/filestorage.yaml` the one needing to be set local? It seems it is kind of intertwined with other aspects of the infrastructure. Would those need to be set up on localstack as well, or would it be best to isolate the s3 or just make another one?

Would there be an advantage in setting up the whole infrastructure on localstack in terms of more closely mimicking the production infrastructure locally?

**Comment by hmhsu** [comment]
Good question! Those YAMLs are CloudFormation config we use to set up our prod-like environment in AWS. I don't see much value in replicating the whole thing in prod-like environment locally. It might just be easier to make a local s3 with localstack and point our play app to it.

@ndmckinley or @bion, feel free to correct me if I am wrong.

**Comment by ndmckinley** [comment]
I think you've got it right!  Sounds fun.

**Comment by syntapy** [comment]
Thanks. Yeah I guess I was making it waay too complicated

Anyhow, now I'm stuck on a simple java bug as described [here](https://stackoverflow.com/questions/66648135/aws-java-sdk-cannot-find-symbol-method-endpointconfigurationjava-lang-string)

Basically I added [this](https://github.com/syntapy/universal-application-tool/blob/403acfcd3005644b504efca5d7d69daaae119f83/universal-application-tool-0.0.1/app/repository/AmazonS3Client.java#L108-L124) stuff as well as the [line](https://github.com/syntapy/universal-application-tool/commit/403acfcd3005644b504efca5d7d69daaae119f83#diff-505999c787e2db448c36fd4015818be56a087accb95a52c390a7afb78748a1f9) in the sbt

However, when I run from the docker-compose I get the error described in the SO post

**Comment by hmhsu** [comment]
Looks like you are importing aws java sdk version 1.x while we are already using v2.15. Would you use version 2 instead? I think the sdk imported should already have everything that you might need from aws.

**Comment by syntapy** [comment]
Ok, that explains why the syntax already there was different than mine
