### ISSUE TITLE
Test helper method to answer questions from `support.TestQuestionBank`

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#484]
**Is your feature request related to a problem? Please describe.**
It is annoying to answer questions correctly in unit tests when they aren't coming from HTTP forms with all the path/value pairs. It would be nice to have methods on [`support.TestQuestionBank`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/support/TestQuestionBank.java) like

`public void answerNameQuestion(Applicant applicant, String firstName, String middleName, String lastName)`

to populate the test pre-defined name question.

**Describe the solution you'd like**
For each test-defined `Question` available in `support.TestQuestionBank` there is at least one `public void answerX` method that puts the values provided in the method arguments into the right places in the applicant data.

**Done when**
`support.TestQuestionBank` has methods to answer questions, and applicant related tests that need to answer questions use them.

**Comment by davidrhallartificialeducation** [comment]
Picking this up now

**Comment by davidrhallartificialeducation** [comment]
@kendrickt Hey Kendrick, I've created methods that put values to the ApplicantData, and am now wanting to integrate those method's into Applicant related tests.  I took a look at `ApplicantQuestionTest` but am unsure what should be replaced.  May I have a small example of what you'd like replaced in a unit test with `TestQuestionBank.answerApplicantName(...)`
