### ISSUE TITLE
Add a back button to the Applicant program block view with proper routing

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#485]
Add a back button to Applicant program block view with proper routing. Should utilize `getBlockBefore` (probably compute this in edit [controller](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java) method and pass it into the edit/form view).

Blocked by #479, which adds `getBlockBefore` to the `ReadOnlyApplicantProgramService`.

This is a bit of a bigger "first issue" task.

### Done when
What conditions need to be met before this issue can be closed?

**Comment by bion** [comment]
Follow up with design to approve this.

**Comment by natsid** [comment]
It's unclear whether we ever want to actually implement this. The current design does not have a back button and relies on the user being able to utilize the browser's back button to return to the last page they saw.

**Comment by elisekalstad** [comment]
This keeps coming back up from CBOs and Program Admins. They would expect residents and CBOs to be able to go "back" to a previous application page.
