### ISSUE TITLE
Refactor inner classes on ApplicantQuestion into their own separate classes

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#489]
**Describe the solution you'd like**
Currently, each question type has its own class on [`ApplicantQuestion`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java) with (for example) logic to check whether the applicant entered invalid information. These classes are getting hard to read, and should be pulled into their own separate files (perhaps in a subdirectory under `services/applicant/questions`)

Notes:
* The inner classes are not static - they share state with `ApplicantQuestion`, so refactoring not be as straightforward as separating code into files
* This will involve reworking implementation and test code to use the new, separate classes

**Done when**
Each ApplicantQuestion type is in its own file

**Comment by natsid** [comment]
This is becoming a more important task as we build out more question types (and their validation logic, especially). I'm hoping to pick this up today so that I can add more unit test coverage for the individual subclasses.
