### ISSUE TITLE
Implement readInteger in ApplicantData

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#491]
### Description
Similar to the `readString` method, implement a `readInteger` method that attempts to read an int at the given path in the [`ApplicantData`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java).

### Additional context
Our question system has a number of recognized [`ScalarType`s](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/ScalarType.java#L6) (as of writing this, it only has `STRING` and `INT`). The `ApplicantData` `read` methods should attempt to parse values in its underlying JSON object into the given scalar type.

**Comment by fripi89** [comment]
Getting started
