### ISSUE TITLE
Wireframe out a Parks & Rec Scholarship Application 

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#495]
In general we want to take PDF applications and wireframe them out into question-by-question mobile app. Example of this can be found [here](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457355053644129&cot=14). Visual assets for wireframes can be downloaded [here](https://drive.google.com/file/d/1oIaPwxy_vwwjqPsvxQbla0gSeifw081O/view?usp=sharing).

We recommend starting with the Parks & Rec [Scholarship Application PDF](https://www.seattle.gov/Documents/Departments/ParksAndRecreation/Programs/ENGLISH%20General%20Scholarship%20Application%202021-2022_B.pdf).

**Comment by neel-a-mehta** [comment]
Take PDF applications and wireframe them out into question-by-question mobile app. Example of this can be found [here](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457355053644129&cot=14). Visual assets for wireframes can be downloaded [here](https://drive.google.com/file/d/1oIaPwxy_vwwjqPsvxQbla0gSeifw081O/view?usp=sharing).

**Comment by neel-a-mehta** [comment]
Someone had a question about this in Slack; here's my response....

> The plan is for all forms to lead off with a few basic questions like the person's name, phone number, and email. (I think that's it but @HansEngebretsen can confirm.) Specific forms will have to implement all the other questions like your address and such. But once the user fills out one form, they'll be able to skip all those questions in future forms, since their data will be auto-filled.

**Comment by baipai** [comment]
I think I am tackling this one, and welcome anyone interested to be part of this.

**Comment by soomoon** [comment]
@baipai happy to work on this with you. Let me know how I can help.
