### ISSUE TITLE
Make responsive/hi-fi mockup(s) for the core application interface

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#496]
Make responsive/hi-fi mockup(s) for the core application interface. Wireframes for UX flows can be found [here](https://miro.com/welcomeonboard/5DhFYqq7YkeqKG2jQ5YT7JJCWzkpSOdzXg1DFSFvywde9WAoIA5ubBk0fYq9wIpi)

- Simple visual styling for mobile-first open source project (loosely based on [tailwind](https://tailwindcss.com/) default UI). Accounting for diverse usability & applications. 
- Built on that, specifically for the City of Seattle. Style guide [here](https://app.uxpin.com/design-system/3f410cc070aa87dbff70/city-of-seattle-digital-style-guide), and a (rough) example of usage [here](http://tiny.cc/uat-proto-app).

**Comment by neel-a-mehta** [comment]
1.  Make responsive/hi-fi mockup(s) for the core application interface. Wireframes for UX flows can be found [here](https://miro.com/welcomeonboard/5DhFYqq7YkeqKG2jQ5YT7JJCWzkpSOdzXg1DFSFvywde9WAoIA5ubBk0fYq9wIpi)

1.  Simple visual styling for mobile-first open source project (loosely based on [tailwind](https://tailwindcss.com/) default UI). Accounting for diverse usability & applications.

Built on that, specifically for the City of Seattle. Style guide [here](https://app.uxpin.com/design-system/3f410cc070aa87dbff70/city-of-seattle-digital-style-guide), and a (rough) example of usage [here](http://tiny.cc/uat-proto-app).

**Comment by lianne-oy** [comment]
Still need more work here, moving to M5

**Comment by neel-a-mehta** [comment]
I think Holly/Hans had a few good passes on this
