### ISSUE TITLE
The `textarea` HTML tag does not support `value` attribute but we are using it to show default content.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#499]
**Describe the bug**
> Default content entered between the opening and closing tags. <textarea> does not support  the value attribute. 
[source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)

There are places where we use `textarea` HTML tag with the `value` attribute, but this is not supported. ([ProgramBlockEditView example](https://github.com/seattle-uat/civiform/blob/874983375704a2b37984c33715f22d4094ea6b4b/universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java#L114)). There may be more `textarea`s being used.

**To Reproduce**
1. start the app
2. login as admin
3. create a program
4. edit the program
5. edit the block
6. update block description

At this point, the block description IS updated, and will show up in the applicant block view. It does not show up in the block edit view. 

**Expected behavior**
Default content in `textarea` should show up. This means the default content is added between the opening and closing tags, instead of with the `value` attribute.

**Screenshots**
![textareabug](https://user-images.githubusercontent.com/12072571/111022370-351f4f00-8387-11eb-869d-97e7ca3443ee.png)

**Comment by AWBaumann** [comment]
This issue was fixed in the latest UI update.
