### ISSUE TITLE
If user is on IE, show banner telling them to upgrade to Edge/etc

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#512]
@AWBaumann has reported that IE11, which is not HTML5-compatible, is making life hard for us. We agreed it's fine to not support IE11 given that it's going EoL soon, which will let us use more HTML5 components.

However, many public schools and libraries will still have IE11 (or older) installed, and many of our applicants will be using it. So, if we detect the user is on any version of Internet Explorer, we should show a banner telling them to upgrade to Edge or another browser. The good news is that pretty much every modern Windows PC will have IE *and* Edge, so users shouldn't have too hard a time going to Edge.

**Comment by neel-a-mehta** [comment]
cc @bion

**Comment by neel-a-mehta** [comment]
This should be done on the client side only -- read the user agent screen, see if it's IE, and if so put up a banner.

**Comment by nbeloglazov** [comment]
One issue doing it client-side is that JS that does the detection must also be compatible with IE11. And that can be harder to enforce, especially given that we have no browser tests running on IE11 to ensure it stays that way. More robust would be to add a filter on the server-side which will redirect all requests from older browsers (e.g. IE11) to a dedicated "Please use newer browser" page.
