### ISSUE TITLE
Create UX contribution guide on the wiki

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#517]
Create a guide on the Wiki to show UXers how to contribute. Mention:

- Look for the `UX` label on github <https://github.com/seattle-uat/civiform/labels/UX>
- Look for the `Good First Issue` label <https://github.com/seattle-uat/civiform/labels/good%20first%20issue>
- Join the Miro board (whatever the link ends up being)
- Drop your mocks in Miro, put them in a frame, and copy the link

**Comment by HansEngebretsen** [comment]
https://github.com/seattle-uat/civiform/wiki/UX
