### ISSUE TITLE
On homepage, offer simple way for testers to log into fake Civiform + Program Admin views

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#524]
Our testers won't be able to authenticate with ADCS/IDCS, and yet they'll need to test out the Civiform Admin (formerly UAT Admin) view and the program admin view. So add some simple way for testers to log into a fake Admin view, where they can see and work with fake forms and user data. Again, it's just for testing, and we can remove this "cheat code" before launch.

**Comment by neel-a-mehta** [comment]
This is connected with #522 and #523, which will be key for testing.

**Comment by neel-a-mehta** [comment]
OK so guest login for applicants is available on seattle.civiform.com. I don't think we have login for program admins yet though.

**Comment by lianne-oy** [comment]
Do not need program / civiform admin log-in if third party.
