### ISSUE TITLE
Use Ebean updated and created timestamps for Applicants instead of custom created times

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#529]
**Describe the solution you'd like**
Currently, we are setting a custom `created_time` on Applicant metadata for use in comparing Applicants and merging profiles. We can (and should) instead use the Ebean built-in created or updated times (see [@WhenCreated and @WhenModified](https://ebean.io/docs/features/history))

**Done when**
We no longer set or read `created_time` in JSON and instead use fields on the `Applicant` model
`ApplicantData` does not include a parallel `metadata` JSON field on creation

**Comment by syntapy** [comment]
Hi, I'd like to give this one a shot. I'll see if I can figure this out
