### ISSUE TITLE
Create a color palette

### ISSUE THREAD

**Issue by ndmckinley** [seattle-uat/civiform#534]
As in https://github.com/seattle-uat/civiform/pull/531/files#r596437082

We need a theme / color palette so we don't have to select colors directly each time.

e.g.
```java
Theme.TEXT_PRIMARY = StyleUtils.joinStyles(Style.TEXT_BLACK, StyleUtils.dark(Styles.TEXT_GREY_100));
Theme.BG_PRIMARY = StyleUtils.joinStyles(Style.BG_WHITE, StyleUtils.dark(Styles.BG_GRAY_600));
```

**Comment by HansEngebretsen** [comment]
Suggest splitting this out into 
1 - Core visual styling for admins
2 - core visual styling for applicants
3 - core visual styling for City of Seattle applicants

**Comment by baipai** [comment]
Here is another good place to look into the style and design system for gov.
https://designsystem.digital.gov/design-tokens/
