### ISSUE TITLE
Define product requirements for the PDF field mapping UI

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#547]
## Situation

Almost every government program accepts PDF forms, whether emailed in or printed out and handed in. PDF is thus a good "lowest common denominator" as we're building out our form-generation system.

It's one thing to spit out data as a PDF, but we want to make it so that applicants' answers get inserted into the given form's *real* PDF. As in, the same PDF that someone would use if they were filling it out by hand.

#546 covers the backend, but here we have to define the frontend: how does the Civiform admin specify which of an applicant's answers go to each part of the PDF? Concretely, if someone gave you a PDF [like this](https://www.seattle.gov/Documents/Departments/ParksAndRecreation/Programs/ENGLISH%20General%20Scholarship%20Application%202021-2022_B.pdf) and you built a Google Form that asked the same questions, how would you map the answers to your Google Form onto the PDF?

You'd need to build some kind of UI that lets someone specify which form fields go to which parts of the PDF. #546 handles the mechanics of writing to the PDF, but here we need to figure out what that mapping UI looks like. We call this the PDF field mapping UI.

## What we need

Define the product requirements (and, optionally, the UX, though #131 will help you out there) for this PDF field mapping UI. It'll be a page on the admin portal that lets them upload a PDF file on the left, and see the list of all questions in a given program form on the right. Then, for each question, they just need to select the matching part of the PDF.

How should this page work? What is the interaction model? What's the user journey look like? We need a product requirements doc, written in Google Docs, that answers:

- How do we leverage the fact that Adobe Acrobat [can specify certain form fields in a PDF as "fillable"](https://acrobat.adobe.com/us/en/acrobat/how-to/create-fillable-pdf-forms-creator.html) to make our lives easier? Can we make the admin just upload a PDF file whose fields are all marked as fillable?
- Should the user drag their mouse to select a certain rectangle on the PDF, and then specify that the answer to a given question will be printed there? Or should we just list each fillable field in the PDF in a dropdown, and let users just select one entry from that dropdown?
- Can the answer to a given question be used more than once?
- How would the admin specify a "transformation" of applicant data before it goes to the PDF? For instance, if the applicant gave us their birthdate but the PDF requires their age, how would the admin specify the algorithm to convert birthdates into age?
- What if the answer to a certain question could be too long to fit comfortably in the space given on the PDF? Would we use addendum pages like in #546?  
- Many PDFs require the applicant's name to be signed (or their initials to be printed) in several places. But we don't want or need the applicant to draw their signature for us in our digital form. So how do we generate a signature to be placed in the signature field (or initials)? How does the admin specify that a certain part of the PDF should get a signature or initials?

As you see, there's a lot of complexity. This is a big project, so don't worry if you can only get answers to a few at a time.
 

## Resources 

First, look at a couple government PDF forms like [this](https://www.seattle.gov/Documents/Departments/ParksAndRecreation/Programs/ENGLISH%20General%20Scholarship%20Application%202021-2022_B.pdf) and [this](https://www.dshs.wa.gov/sites/default/files/FSA/forms/pdf/14-001.pdf) to see how government PDFs are usually laid out.

See the [full list of PDF issues](https://github.com/seattle-uat/civiform/labels/PDF) to get a sense of the full scope of work we have to do to enable PDF export.

**Comment by neel-a-mehta** [comment]
@HansEngebretsen  have you made any mocks for the PDF field-mapping page? (Not a huge priority since that's only due toward M6 and M7, but curious)

Anything else you'd add to this, @gcapiel ?

**Comment by HansEngebretsen** [comment]
Nope - this is somewhat dependent on the drag-n-drop interface we were planning to use, and what we could do within those confines. I think @ndmckinley was working on it at one point? Any ideas what the library we were using for that was?
