### ISSUE TITLE
enable civiform.com for our AWS instance

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#555]
Can we point civiform.com to our AWS instance.  I'm holding the domain under my personal GoDaddy account.  Please provide me the configuration that I need to set.

Gerardo

**Comment by neel-a-mehta** [comment]
This will be essential for both user testing (we can point them to civiform.com) and helping community contributors see what work has been done already.

**Comment by gcapiel** [comment]
we also need to put a warning across the top asking people to not enter personal/real data as this is just a demo/example system.  something like what mibridges does in their demo site referenced on github: [demo site](https://demo.michiganbenefits.org/).  maybe we can pick one of these tailwind formats: https://tailwindui.com/components/marketing/elements/banners

**Comment by gcapiel** [comment]
because we can't transfer the domain to route 53 until 5/10, we will go with godaddy's domain forwarding to http://prod-civiform-publiclb-916393258.us-west-2.elb.amazonaws.com/ until then.  i tested it and it works, but reverted back to point to our github repo, because before we start sending  people there we should implement the banner.  we also need to show the login as admin button when the domains is *.amazonaws.com .

**Comment by gcapiel** [comment]
Here's the banner CSS: https://play.tailwindcss.com/6yyHmMFEmG?size=540x720

**Comment by hmhsu** [comment]
will work on adding the banner today/tomorrow.

**Comment by gcapiel** [comment]
let's have the banner show on every page while the system is not officially in production even though it's on production servers.
