### ISSUE TITLE
Add Google Analytics tracking code

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#575]
Once the Google Analytics has been set up in #574, grab the tracking code and unique ID (UA-something?) and put it in the repo. The generic tracking code should go in the main codebase, but the Seattle-specific tracking ID should go in some special Seattle-specific configuration file, so that other cities could easily swap in their own Google Analytics code.

**Comment by victorotazu** [comment]
Copy the global site tag into the <head> section of your HTML in order to start measuring user interactions with CiviForm (seattle.civiform.com):

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S5Z0YE69TM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S5Z0YE69TM');
</script>
```

**Comment by gcapiel** [comment]
Once we move over to our official *.seattle.gov subdomain, we should configure it with Seattle's GA account (gatc-other) and the CiviForm property (267779978).
