### ISSUE TITLE
Basic styling for Applicant experience

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#578]
Add some styling to the Applicant pages. We should just do a basic initial pass to make the pages usable, even without any high fidelity UX mocks.

The pages that come to mind right now that need styling are:
* program list
* program block forms

**Done when** the Applicant experience is understandable and usable by a random outside user.

**Comment by lianne-oy** [comment]
Made some progress; but not complete.  Moving to M5.

**Comment by lianne-oy** [comment]
Still need to define e2e applicant experience.

**Comment by neel-a-mehta** [comment]
Here's a mock of what the applicant experience can look like with Seattle styling. May want to coordinate with Aaron to settle on final styling: April Showers Bring June Launches (tm)
