### ISSUE TITLE
Make Tailwind Playground demo for Application form page

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#587]
## Background 

On https://tiny.cc/cvf-flow, we've created some wireframes for what a few key pages of our app will look like. We will eventually be building these pages using the Tailwind CSS library.

But as an intermediary step, we need someone to envision what the final page would look like and how it would be implemented using Tailwind.

So check out [that board with wireframes](http://tiny.cc/cvf-flow), and [use the Tailwind Playground](https://play.tailwindcss.com/) to create a demo of what this page should look like.

## The task

When an applicant is applying for a program, they will step through a series of linked screens. What does each screen look like? How does navigation from one screen to the next work? What "breadcrumbs" are shown? 

## Submit 
Reply to this issue with the URL for your Tailwind Playground demo for this page, such as <https://play.tailwindcss.com/wMKlKdzVhW>.

**Comment by neel-a-mehta** [comment]
Hans made some great mobile-friendly mocks here in case anyone would like to start Tailwind-ifying them:
https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457356256048960&cot=14

![Uploading image.png…]()

**Comment by holly-r-li** [comment]
I'll take this

**Comment by neel-a-mehta** [comment]
@HansEngebretsen had an early prototype we can build off, btw: https://play.tailwindcss.com/traAFbmqFG

**Comment by holly-r-li** [comment]
Here's what I have so far (one screen): https://play.tailwindcss.com/2uNkS4wJOv

Getting the html/css "template" done was the hardest part -- now replicating this for other screens -- and just swapping out components -- should be *relatively* straightforward. 

@neel-a-mehta @gcapiel and Hans (for some reason, can't @ him) -- is there a preferred way of standardizing elements and styling? Esp. given that all the application screens will reuse the same buttons, input fields, etc. I'm new to Tailwind but used @apply for simple components, in this version ^.
