### ISSUE TITLE
Fix all usages of `services.Path.path()`.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#606]
**Is your feature request related to a problem? Please describe.**
A `Path.path()` method doesn't make sense. What is the path of a path?

In some places, what it really means is `Path.toString()`. e.g.

```
String.format("question %s updated", questionForm.getQuestionPath().path())
```

In other places, it just means `Path` but the string version of it. This is code debt because our classes should be using Path objects and not strings representing paths. 

**Describe the solution you'd like**
Our application should use Path objects and not strings representing paths. The `Path.toString()` method may be necessary when interfacing with json data, and presenting to the UI. But otherwise, most places should be using `Path` objects.

In some cases (e.g. exception string formatting) the path object can be used as is, and the `toString()` method will be invoked automatically.

Cases:
1. JSON methods: use `toString()` explicitly.
2. String formatting: just use `Path` and let `toString()` be automatically invoked
3. Other (I don't think this exists): update our methods to take `Path` objects instead of strings representing paths.

**Additional context**

The most complicated behavior is in `QuestionRepository.PathConflictDetector`. For now, this can just use `toString()` and will be addressed in a separate PR.

**Done when**
`Path#path()` is deleted.

**Comment by randomUser00** [comment]
If this is still open, I would like to try to solve the issue

**Comment by kendrickt** [comment]
It is still open! I assigned it to both of us. If you haven't already joined our [slack group](
https://join.slack.com/t/civiform/shared_invite/zt-niap7ys1-RAICICUpDJfjpizjyjBr7Q) you should do that - feel free to ask any questions here or in slack!

**Comment by kendrickt** [comment]
@randomUser00 any updates on this ticket?

**Comment by randomUser00** [comment]
I had exams till today starting rn

**Comment by randomUser00** [comment]
I have made the changes! Since this is my first time contributing please let me know if I made errors so I can rectify them.

**Comment by kendrickt** [comment]
Is there a PR open?
