### ISSUE TITLE
Add "program details" URL for every program

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#607]
On the program list page, we can offer a button that will let users open up a separate page to get more details about the program -- often, this will be a seattle.gov page. We would implement this by adding a field for a program details URL in each program.

This isn't required for launch by any means, but it would be a nice add if we have time to improve the UX.

**Comment by neel-a-mehta** [comment]
Here are the key URLs for each program:

Orca middle school - https://www.affordableseattle.org/program-info/4-orca-opportunity-middle-school#transportation
Childcare scholarship - https://www.affordableseattle.org/program-info/12-seattle-parks-and-recreation-preschool-scholarships#educationandchildcare
Preschool program - https://www.affordableseattle.org/program-info/13-seattle-preschool-program#educationandchildcare

cc @lianne-oy

**Comment by neel-a-mehta** [comment]
This feature is something the City would really like to see happen, btw

**Comment by lianne-oy** [comment]
Should go in today

**Comment by AWBaumann** [comment]
Ready for story acceptance. @neel-a-mehta

**Comment by neel-a-mehta** [comment]
The field to input the URL is there:

![image](https://user-images.githubusercontent.com/77128518/121567744-ed8f7a00-c9ec-11eb-9721-3b7563b71e46.png)


You can't see it in this screenshot, but the "Program details" page goes to the URL I entered

![image](https://user-images.githubusercontent.com/77128518/121567959-24fe2680-c9ed-11eb-9c4b-d25291b2c064.png)
