### ISSUE TITLE
ApplicantData.put methods are too recursive

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#624]
**Is your feature request related to a problem? Please describe.**
Currently there are no rules to what data can be added to `ApplicantData`. For example, an empty applicant data can have the following data added:

```applicant.children[10].jobs[5].employer.text = "Google"```

There are rules in place that can make adding data to `ApplicantData` more robust:

1. Paths to answers look like `{parent_path}.{question_name}.{scalar}`. The `question_name` JSON object shouldn't be put at `{parent_path}` if the parent path doesn't already exist.

2. Paths to repeated entities look like `{parent_path}.{repeated_entity_name}[{index}]`. The `repeated_entity_name` JSON array shouldn't be put at `{parent_path}` if the parent path doesn't already exist.

3. Paths to repeated entities look like `{parent_path}.{repeated_entity_name}[{index}]`. For `N > 0`, the JSON object at index `N` shouldn't be added to the JSON array at `repeated_entity_name` if the JSON object at index `N-1` doesn't already exist.

Rules 2 and 3 depend on being able to specify the order of updates in a single `ApplicantService.stageAndUpdateIfValid`. It currently uses a `Set` and we don't want to be dependent on order.

**Describe the solution you'd like**
In `ApplicantData`, the `putParentIfMissing` and `putParentArray` methods recursively call `putParentIfMissing` (this issue is linked in TODOs). Get rid of the recursion, and then fix all the tests that break because tests are assuming they can add applicant data anywhere.

**ALTERNATIVE SOLUTION**: allow `ApplicantData.put` methods to be flexible, and enforce the rules in `ApplicantService`. 

**Additional context**
#625 PR adds recursive for adding parent arrays.

**Done when**
Rules are enforced, tests are added for the rules, and tests pass.

If this work isn't going to be done, please remove the TODO comments marked with #624 before closing this issue.

**Comment by kendrickt** [comment]
We may not be able to enforce update ordering in the ApplicantService. If not, then we may need to enable adding `something[3]` before `something[2]`.

**Comment by carolinedanzi** [comment]
Originally, Natalie and I decided that `ApplicantData` should be "dumb", in that it blindly adds whatever we tell it to, and it's up to callers to enforce logic around valid updates

**Comment by bion** [comment]
> Originally, Natalie and I decided that `ApplicantData` should be "dumb", in that it blindly adds whatever we tell it to, and it's up to callers to enforce logic around valid updates

I agree, I think it's best to keep validation concerns out of ApplicantData, which has as its single responsibility performing updates to the underlying JSON data structure.

**Comment by bion** [comment]
The description for this issue reads more like it's asking for more validation than being specifically scoped to recursion?

**Comment by kendrickt** [comment]
[NOT DOING]

`ApplicantData` is the wild west, and anything can be put anywhere. We'll rely on the controllers and services using `ApplicantData` to properly handle things.
