### ISSUE TITLE
Finish writing application review end-to-end browser test

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#632]
We are migrating our end-to-end browser tests from using Java with Selenium to using TypeScript with [Playwright](https://playwright.dev/). Please see our [wiki section on browser testing](https://github.com/seattle-uat/civiform/wiki/Testing#functional-browser-tests) before proceeding.

This test should do the following (not that steps 1 and 2 are already complete in [application_review.test.ts](https://github.com/seattle-uat/civiform/blob/main/browser-test/src/application_review.test.ts), this issue is to extend that test):

1. login as admin
2. create a question
3. create a program
4. add the question to the program
5. log in as applicant
6. complete the program created in step 3
7. login as admin
8. view applications for the program created in step 3
9. view the application submitted in step 6
10. assert that the answer to the question is the same as submitted in step 6

**Comment by hmhsu** [comment]
I think I can take this as I am going to add a browser test for my recent PR.
