### ISSUE TITLE
`hasValue` in the `ApplicantQuestion` subclasses don't seem to WAI

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#634]
We decided on a convention of storing `null` for "never answered" pieces of data, and `""` (the empty string) for "answered with a blank value".

However, it seems like the underlying spring form data binder binds empty inputs as `null` (at least that's what I guess is happening).

I ran into this issue while implementing min and max length validations for text questions. When there is no value entered in the applicant form, our code evaluates `hasValue()` to `false`, so we end up not running our `getQuestionErrors` validations.

Needs more investigation to conclude the root cause and obviously to fix the issue as well.

**Comment by hmhsu** [comment]
I think you're right that we don't store empty strings now [1].

[1] https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java#L89

**Comment by natsid** [comment]
Ah, thanks @hmhsu ! That's a great reference and makes me think that just updating it to `""` there will fix the issue.

**Comment by carolinedanzi** [comment]
I'm happy to help here - we decided to never allow binding the empty string - if they didn't answer a question (includes seeing `""` for number questions), then we put null instead. 

We may want to look at some of the `ApplicantQuestion` logic -  I added `isAnswered` methods to address questions, which check if the path exists (the applicant saw the question, but did not put an answer) - we may want to add something like this to the other types, too.

**Comment by natsid** [comment]
@carolinedanzi the `isAnswered` solution that checks for the path existence looks like exactly what we need! Thanks for implementing that for some of the types. Adding `isAnswered` to the `TextQuestion` type in #761.

**Comment by natsid** [comment]
I think we can just get rid of `hasValue` in general now.

**Comment by natsid** [comment]
Oops - not fixed till #769 goes in.
