### ISSUE TITLE
Clean up: ReadOnlyQuestionService.getQuestionDefinition(String) and (Path) are not used.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#651]
**Is your feature request related to a problem? Please describe.**
The `ReadOnlyQuestionService`'s [`getQuestionDefinition(String)`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java#L47) and [`getQuestionDefinition(Path)`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java#L58) methods are not being used except in tests. 

**Describe the solution you'd like**
Clean up the two methods. The [constructor](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java#L18) can also be cleaned up a bit - the [`scalarParents`](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java#L14) private map can be deleted.

**Additional context**

**Done when**
The two methods are deleted.

**Comment by davidrhallartificialeducation** [comment]
Hi, I'd like to start this issue, and have it tackled by EOD Tomorrow!
