### ISSUE TITLE
Automatically log visitors in as guest applicant (remove blue buttons page on home screen)

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#658]
Anyone who visits Civiform should be instantly logged in as a guest. They can still log in with their IDCS credentials if they have them, but at the start they're always a guest.

This means they can always apply for programs without hitting an auth wall.

It also means there's no such thing as a "logged-out state" for any of our UI.

**Comment by neel-a-mehta** [comment]
I think we're pretty much there, except when you visit the website homepage, you get hit with an auth-wall rather than getting auto-logged-in as a guest.

**Comment by kendrickt** [comment]
Do we really want to do this? If an applicant logs out, it'll look like they're logged in as something else, which may be a confusing experience.

Should we just create a simple applicant login page?

**Comment by neel-a-mehta** [comment]
Good points. Here's how I could envision things working:

- An applicant visits CiviForm for the first time. They land on the applicant homepage (the list of available programs). In the top right corner it says something like, "Not Logged In."
- An applicant logs in with an IDCS account. They see their name in the top righr corner.
- That applicant logs out. They go back to the applicant homepage and see "Not Logged In" in the top right corner.
- When a logged-out applicant goes to fill out a program form, they see a message like, "You're not logged in -- applying as a guest."

Does that work? The main goal of this issue is to get rid of the "blue button" page and have new users land on a more friendly and more informative homepage.

![image](https://user-images.githubusercontent.com/77128518/121033976-a601b780-c77a-11eb-98c2-3cbb8f68b7fe.png)

**Comment by lianne-oy** [comment]
Potentially 1 day of work; tied to #660

**Comment by kendrickt** [comment]
Not doing this. We're doing #1377 instead.
