### ISSUE TITLE
Create Partner Login page for CBOs/TIs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#662]
It's just a normal login page, except it's just for CBOs (Community Benefit Orgs) who are our TIs (Trusted Intermediaries).

See https://newmibridges.michigan.gov/s/isd-partnershiplanding?language=en_US, which is a good example of what this page could look like.

**Comment by lianne-oy** [comment]
Needs additional discussion before work can get started; need to figure out if multi-factor authentication is required for TI.

Lianne to add to city agenda / send email to confirm.

**Comment by baipai** [comment]
And it also needs to consider what kind of information needs to be put in the “page”. 
People who may check out this page, IT(CBO) = application > admin. Are we putting any IT(CBO) information here to let applications look for support? or is there any other website that already provides IT(CBO) information and can point them out? like seattle.gov?

**Comment by baipai** [comment]
The login part for the partner can be something like this.
<img width="680" alt="Screen Shot 2021-05-04 at 10 53 02 PM" src="https://user-images.githubusercontent.com/11348330/117023504-c11c7a00-ad2b-11eb-9a92-f22260410307.png">
