### ISSUE TITLE
Put "Partner Login" link in footer and/or header

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#663]
This is how CBOs/TIs will log in. When they click it, take them to a Partner Login page where they can enter their credentials.

See how MI Bridges advertises the Partner Login link via https://newmibridges.michigan.gov/s/isd-partnershiplanding?language=en_US

**Comment by ndmckinley** [comment]
TIs can log in with the regular login page.  They'll be automatically recognized as TIs.
