### ISSUE TITLE
Expose dev/seed for user acceptance testing in AWS and pre-populate with our four pilot programs

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#684]
In preparation for user testing, we would like to easily be able to clear and pre-populate the DB with the 4 pilot programs, which are DEEL SPP, SDOT Vehicle License Fee Rebate and Orca discount student cards and SPR scholarship.

We will build the programs manually using the UI and then export their definitions in a way that can be loaded with dev/seed

**Comment by neel-a-mehta** [comment]
#522 and #523 are connected to this

**Comment by lianne-oy** [comment]
Please remove SDOT Vehicle License Fee Rebate (sunsetting in June 2021) and add parking zone permit discount.  Move to M6.

**Comment by lianne-oy** [comment]
This needs to be done as soon as Elise is done creating forms BUT BEFORE the first applicant submits for each program - moving to fast follow.  Wipe prod DB in meantime.

**Comment by neel-a-mehta** [comment]
Is this done yet?

**Comment by hmhsu** [comment]
We've enabled this in staging. For prod, we now have daily backup so it would be easy to roll the database back to a previous state if necessary. So I think we can close this.
