### ISSUE TITLE
Migrate SecurityBrowserTest to playwright

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#699]
There is one selenium browser test file left, [SecurityBrowserTest](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java). This issue is to migrate it over to [the new browser testing system](https://github.com/seattle-uat/civiform/tree/main/browser-test) that uses playwright.

Done when: SecurityBrowserTest.java is deleted and the functionality it tests is covered by a playwright test

**Comment by syntapy** [comment]
I'm working on this right now

**Comment by bion** [comment]
wontfix
