### ISSUE TITLE
Values are not displayed for checkboxes in view applications

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#708]
**Describe the bug**
Values are not displayed for checkbox types in view applications

**To Reproduce**
1. Create a checkbox type question.
2. Apply to the program
3. View the submitted application

**Expected behavior**
I should be able to see the values of the checkboxes I selected

**Screenshots**
<img width="1166" alt="Screen Shot 2021-04-08 at 11 11 50 AM" src="https://user-images.githubusercontent.com/437060/114076433-8245f200-985b-11eb-9baa-2266359f4fdf.png">

**Comment by carolinedanzi** [comment]
This is fixed as of #704: 
<img width="536" alt="Screen Shot 2021-04-11 at 12 11 29 PM" src="https://user-images.githubusercontent.com/8559046/114317900-372c1900-9abf-11eb-983b-4329c0f41440.png">
