### ISSUE TITLE
Typo on the Programs page when entering as a Guest

### ISSUE THREAD

**Issue by kencenerelli** [seattle-uat/civiform#709]
There's a typo on the Programs page when entering as a Guest.

The phrase "and well handle" should be "and we'll handle".

1. Go to 'http://seattle.civiform.com/loginForm'
2. Click on 'Continue'
3. The text with the typo is on the right

**Comment by carolinedanzi** [comment]
We forgot to escape the apostrophe in the messages file - I will fix this in #980
