### ISSUE TITLE
Checkbox values are displayed in all uppercase despite being created in mixed case

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#710]
**Describe the bug**
Checkbox values are displayed in all uppercase despite being created in mixed case.  They are stored in mixed case as entered based on what I see when I try to create a new version of the question.

**To Reproduce**
1. Create a checkbox question
2. Enter possible values in lowercase or mixed case
3. View application as an applicant

**Expected behavior**
Case should be maintained

**Screenshots**
<img width="865" alt="Screen Shot 2021-04-08 at 11 18 56 AM" src="https://user-images.githubusercontent.com/437060/114077057-3cd5f480-985c-11eb-85e5-203538877639.png">
<img width="1179" alt="Screen Shot 2021-04-08 at 11 18 34 AM" src="https://user-images.githubusercontent.com/437060/114077061-3d6e8b00-985c-11eb-81fd-10256187705c.png">

**Comment by carolinedanzi** [comment]
This appears to be fixed:
![Screen Shot 2021-06-23 at 11 31 47 AM](https://user-images.githubusercontent.com/8559046/123149895-9e970b00-d416-11eb-91e6-7285e9965810.png)
