### ISSUE TITLE
`QuestionDefinitionBuilder.sample()` should make questions with more details.

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#712]
**Is your feature request related to a problem? Please describe.**
The `QuestionDefinitionBuilder.sample` method makes a minimal sample that isn't very helpful for an admin.

**Describe the solution you'd like**
First, samples should not be part of `QuestionDefinitionBuilder`. I don't think that's the right scope, since it is only being used in Views.

Second, each question type supported should have more details (e.g. real names, question text, paths, etc) so that the rendered sample is more helpful for the admins.

**Additional context**

**Done when**
QuestionDefinition samples can be made for each question type with proper fields and options so that the rendered sample is more helpful.

**Comment by thomasphung** [comment]
I would like to tackle this issue. I'll let you guys know if any issue comes up.

**Comment by kendrickt** [comment]
@AWBaumann can you add any additional context here? You recently updated some scripting to the rendered samples so they partially update as you update the form.
