### ISSUE TITLE
Improve speed of browser tests by caching container build

### ISSUE THREAD

**Issue by ndmckinley** [seattle-uat/civiform#714]
Store browser test container in ECR and make the build step use a cache from there.  Is this the right place to start?  https://github.com/actions/cache. Seems like it might help?

**Comment by hmhsu** [comment]
Looks promising. The only complaint? I have is the size limit of the cache of the whole repo is 5GB. Considering our images, we can only cache at most 2!

**Comment by ndmckinley** [comment]
Woah, our images are huge!  I suppose our prod image is merely "big".  Bummer!
