### ISSUE TITLE
Civiform admin: switch to "synchronized" versioning

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#759]
- All program forms and questions should be versioned together with a monotonically increasing version number that the entire Civiform instance shares. [@bion has a doc for this](https://drive.google.com/file/d/1OJhbwpCnqB8sS-e7gAKdlGxsRvb8IBBg/view?usp=sharing).
- A separate page is created that lists all the past versions (avoid the endless sideways scrolling of the [mocks](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457356370156646&cot=14), but the concept is right). Admins can click over to it to view all past versions.
- Click on a past version to overwrite the current draft with a copy of that past version.
- Overall, use the [light theme](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354953282475&cot=14) mocks rather than the nearby dark theme ones.

**Comment by neel-a-mehta** [comment]
Doing story acceptance testing.

* Logging in as admin on staging.seattle.civiform.com
* I just published a version before, so I go to the Versions tab and see Version 140 as active (with my most recent changes) and Version 141 is draft (with nothing inside, which makes sense).
* I see a helpful list of all past versions, from 132 to 139. I assume there's a reason we start at 132.
* I update my test program (Coffee program) to include the Favorite Ice Cream question. This requires making a new version.
* Go back to Versions. I see my updated coffee program is in the draft. Shows me the last updated time as 5 minutes ago, which I don't think is accurate. see the time in the bottom right of my screenshot (except I'm on eastern time, so +3 hours).
* 
![image](https://user-images.githubusercontent.com/77128518/116263066-131b3980-a747-11eb-8991-177979bb7c47.png)
* I go to edit the Favorite Ice Cream question. Add chocolate as an option alongside vanilla and strawberry.
* Go back to Questions list. I see the favorite Ice Cream question has a new draft.
* Go back to Versions. The last updated date hasn't changed, and the favorite ice cream doesn't show up there.
* Hm, I'll just publish what i have right now.
* Go back to Versions. I see version 141 includes the coffee program and a few other programs (idk why). shows the right last updated time. the draft shows the same last updated time, except this one is version 142 and is empty.
* Go back to edit the Ice Cream question again. Add another option (Rocky Road).
* Go back to Versions. I see version 142 includes a change to the coffee program, which makes sense since I edited a question that's contained therein. however, it still shows the same last-updated time as the published version, even though i updated it several minutes after -- this seems like a bug.
* Publish this version.
* Actually I want to undo my change and roll back to version 141. I scroll down to it and hit Set Live.
* My draft is gone, as expected. The Active program gives right now as the last updated time -- makes sense.
* Return to the Ice Cream question, and see just chocolate (no rocky road). That makes sense.
* Return to Versions and make version 142 active. Rocky Road returns as a flavor choice in the question.

**Comment by neel-a-mehta** [comment]
OK everything else looks good. I just want to review the draft thing -- right now, I haven't touched the draft in a while and the draft editing time appears the same as the active version's last updated date:

![image](https://user-images.githubusercontent.com/77128518/116467079-49d37b80-a83d-11eb-89e0-e348e9ee3789.png)

Adding Banana as a flavor option. Saving. Returning to Versions screen. Still says same old "last updated" date.

Creating and updating a new program called "N Test". The Draft card shows that my program is indeed included in the draft, but the Last Updated date/time is still stale -- still showing the Active card's Last Updated date.

![Uploading image.png…]()

**Comment by ndmckinley** [comment]
Ah right, those don't technically count as updates to the *version*. 🤦  I'll look into that sometime soon - seems like a minor issue.

**Comment by neel-a-mehta** [comment]
Yup, I'll count this issue as Closed and just make a low-pri bug for htat.
