### ISSUE TITLE
Block name and description should be localized

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#767]
### Describe the solution you'd like
Currently, we only store a single name and description for blocks. To support more languages, we should change these to `ImmutableMap<Locale, String>` so we can display the text in an applicant's preferred locale.

### Done when

1. BlockDefinition uses `ImmutableMap<Locale, String>` for `name` and `description`
1. The applicant's view of a block uses strings in their preferred locale
2. BlockDefinition still has a `name` field that is immutable (this is used as an identifier for admins)

**Comment by carolinedanzi** [comment]
2021-04-21: Pause on this for now while we decide whether we want to display block name and description to applicants

**Comment by bion** [comment]
Block name and description are not shown to the applicant
