### ISSUE TITLE
Enable translation/i18n of questions directly within the Civiform admin UI

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#778]
#776 describes how admins can download a list of *all* strings required to be translated, translate in a new column, and re-upload. A more graphical (and maybe easier to implement) alternative is for Civiform admins to be able to edit question titles, help texts, and options (for checkboxes, radio buttons, etc.) directly within the Civiform admin UI.

**Comment by neel-a-mehta** [comment]
This is going to be more important than #776; we want admins to be able to edit translations from directly within the UI.

#829 requests UX help for this.

**Comment by neel-a-mehta** [comment]
All right, going to list some product requirements and rough wireframes here -- more as proofs of concept rather than proper UI/UX explorations. Hopefully, everything here will be agnostic to the specifics of UI/UX implementation.

- Every question tracks which language(s) it has been translated into. By default, every question starts off with just English.
- The set of languages that any question is translated into is shown in the question bank, like so. We can use either the full language names (English, Spanish, French) or their [2-letter language codes](https://www.sitepoint.com/iso-2-letter-language-codes/) (EN, ES, FR).
![image](https://user-images.githubusercontent.com/77128518/115302468-75b17b80-a130-11eb-99d0-d54cbb1e8309.png)
- In the Question editor page, there's one tab for every translation that a given question has. The tab bar is placed under the fields that are invariant to translation (namely, the fields that only the admin sees, like the question name and description). But all the fields that change per translation (such as the user-facing text) are within the tabbed pane and change when the user switches tabs. ([Tailwind snippet](https://play.tailwindcss.com/ieqjtUpoGn))
![image](https://user-images.githubusercontent.com/77128518/115303314-77c80a00-a131-11eb-9666-9cfbc611f7b3.png)

**Comment by neel-a-mehta** [comment]
- Note that free-text configuration options are also in the tabbed pane, so the admin has to specify different versions of each for each language. (A pitfall of this design is that configuration options that presumably should always be the same -- such as the min or max number of options the user can choose -- also change between tabbed panes, meaning the admin has to copy the same values every time they add a new language. But I think that's OK for now.)
![image](https://user-images.githubusercontent.com/77128518/115303736-fcb32380-a131-11eb-9dc5-aab6064ae9be.png)
- When the user hits "+ Add Language" in the tab bar, a text input field appears. They then hit a "+" button to create a translation for that language. ([Tailwind snippet](https://play.tailwindcss.com/9kIBRPcSDW))
![image](https://user-images.githubusercontent.com/77128518/115303933-469c0980-a132-11eb-82eb-23c8cace344c.png)

**Comment by neel-a-mehta** [comment]
Things I have *not* figured out, and that a UXer should think about:

- How you remove a language 
- How we separate configuration/validation options that change with every language (such as the text labels of various checkboxes, like the races example above) and options that should stay the same (such as the min/max number of choices required above).

**Comment by carolinedanzi** [comment]
This is complete, except for custom question options

**Comment by lianne-oy** [comment]
Going out for review today!

**Comment by neel-a-mehta** [comment]
Testing it now:

- As admin on staging, go in and create a new text question
- Manage translations => add spanish translation
- Make a new program, add the question
- Publish
- Log back in as guest
- I see I can enter it in English
- Log in as another guest and set language to Spanish
- Program and question are successfully translated!

So that part's good. Now just testing if I can translate one of the multi-option questions...

- Go back as admin
- Make a checkbox question
- Translate to Spanish -- nice, I can edit each option
![image](https://user-images.githubusercontent.com/77128518/119168050-1fcd3d80-ba26-11eb-8357-6f52afabc003.png)
- Add spanish translation
![image](https://user-images.githubusercontent.com/77128518/119168575-a6821a80-ba26-11eb-91ac-cd3040e1357b.png)
- Add to program
- Publish
- Log back in as guest
- Set language to Spanish
- Go to program
- Translated options show up!
![image](https://user-images.githubusercontent.com/77128518/119169599-d1b93980-ba27-11eb-9c47-f0e4ba14470f.png)

This is all good!
