### ISSUE TITLE
Implement "contextualized" paths for repeated questions

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#783]
In order to get the fully specified JSON path to applicant data that has a repeater as a parent, we need the path with indices into any repeaters.

Currently, we just use the path from the QuestionDefinition to look up applicant data. However, that path is "unhydrated" and is a generic path like `applicant.household_members[].address`. We need the path with indices, like `applicant.household_members[0].address`, in order to actually reference the applicant data to prefill forms and to update applicant data.

The solution must also work for nested repeaters. For example, `applicant.household_members[1].employers[0].phone_number`.

### More thoughts about the potential solution

The solution for this will likely involve creating a new `RepeaterContext` class that has a list of indices into any repeaters as well as the full path to the repeater question - this may either be a path or a question definition... Haven't thought it through enough to know yet.

For example:

```java
public class RepeaterContext {
  public ?? repeater;
  public ImmutableList<Integer> repeaterIndices;

  public RepeaterContext(?? repeater, ImmutableList<Integer> repeaterIndices) {
    this.repeater = repeater;
    this.repeaterIndices = repeaterIndices;
  }

  public Path hydratedPath(Path path) throws NotInTheRightContextException {
    // Combines repeater, repeaterIndices, and path to compute the hydrated path.
  }

  // Other helpers?
}


?? repeater = something that contains "applicant.household_members[].employers[]"

RepeaterContext repeaterContext = new RepeaterContext(repeater, ImmutableList.of(0,0));
```

**Comment by kendrickt** [comment]
A small brain dump:

It would be handy for `RepeaterQuestionDefinition` to have a `Path path` member and `getPath` method. The other questions don't really need a `Path`, but just the question name (formatted?) and scalar fields.

What if the `RepeaterContext` was just a hydrated path? If I have a `RepeaterQuestionDefinition` and its unhydrated path, and the right indices, I can generate a `hydrated parent path`. All the `Path`s for the updates are just the hydrated path joined with the question name and scalar.

**Comment by natsid** [comment]
> What if the RepeaterContext was just a hydrated path?
That makes sense to me too! To clarify, in this case `RepeaterContext` would take `RepeaterQuestionDefinition` with its unhydrated path and indices in the constructor, and then just have a getter that returns a `Path`.
