### ISSUE TITLE
Make Tailwind Playground demo for Checkbox set question type

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#795]
## The task

Please create a Tailwind playground demo for this feature:

* UX task: #562
* Story: #396
* Tracker: [tiny.cc/cvf-ux-tracker](tiny.cc/cvf-ux-tracker)

## Background 

On [tiny.cc/cvf-flow](tiny.cc/cvf-flow), we've created some wireframes for what a few key pages of our app will look like. We will eventually be building these pages using the Tailwind CSS library.

But as an intermediary step, we need someone to envision what the final page would look like and how it would be implemented using Tailwind.

So check out [that board with wireframes](http://tiny.cc/cvf-flow), and [use the Tailwind Playground](https://play.tailwindcss.com/) to create a demo of what this page should look like.

## Submit 
Reply to this issue with the URL for your Tailwind Playground demo for this page, such as <https://play.tailwindcss.com/wMKlKdzVhW>.

**Comment by neel-a-mehta** [comment]
@AWBaumann started a prototype for this: https://play.tailwindcss.com/ttK8KNY5h4

**Comment by holly-r-li** [comment]
https://play.tailwindcss.com/cZxdJjzhrz

In this instance, it's a repeater question; the child in question is shown in the pill

![image](https://user-images.githubusercontent.com/82596874/115772552-3f1c7080-a37d-11eb-9c93-63e3a0c79a4f.png)

**Comment by neel-a-mehta** [comment]
Looks great, thanks!
