### ISSUE TITLE
Creating an address question with "disallow PO boxes" checked returns an error

### ISSUE THREAD

**Issue by natsid** [seattle-uat/civiform#817]
Error looks like: "7jdfaak98".

Needs investigation.

**Comment by natsid** [comment]
This bug blocks story acceptance of #377.

**Comment by kendrickt** [comment]
Solution: the checkbox dom needs to have `value=true`.

**Comment by neel-a-mehta** [comment]
When I do this: 
![image](https://user-images.githubusercontent.com/77128518/115078460-a2b22400-9ecd-11eb-9032-65cfb201f1ef.png)

I get this:

![image](https://user-images.githubusercontent.com/77128518/115078475-a9d93200-9ecd-11eb-8b44-0ade69882953.png)

**Comment by kendrickt** [comment]
i can fix this after a couple meetings :sob:
