### ISSUE TITLE
Document application code

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#818]
At the very least all public classes should have javadoc-style docstrings. Most public methods should as well.

Non-exhaustive list of classes in need of a docstring or in need of a much more descriptive and detailed docstring:

- [x] [ApplicantData](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java)
- [x] [Question](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Question.java)
- [x] [Application](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Application.java)
- [x] [Applicant](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Applicant.java)
- [x] [Program](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Program.java)
- [x] [BaseModel](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/BaseModel.java)
- [x] [AdminLayout](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/views/admin/AdminLayout.java)
- [x] [AdminProgramBlocksController](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockQuestionsController.java)
- [x] [admin/AdminQuestionController](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionController.java)
- [x] [AdminApplicationController](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java)

**Comment by lianne-oy** [comment]
Focus for last week
