### ISSUE TITLE
Applications are not being considered complete unless all question fields are completed

### ISSUE THREAD

**Issue by gcapiel** [seattle-uat/civiform#847]
**Describe the bug**
Applications are not being considered complete unless all question fields are completed. 

**To Reproduce**
1. Apply on staging to "Gerardo Short App to Test Completed Apps", which just has a name question
2. Leave middle name empty, but fill out first name and last name.
3. Save the one question being asked
4. The application is not considered complete until the middle name is filled in.

**Expected behavior**
Some fields on questions such as name should be optional and the question is considered answered when the non-optional questions are saved.

**Comment by kendrickt** [comment]
Closing because this was fixed at some point.
