### ISSUE TITLE
Applicant can submit simple form

### ISSUE THREAD

**Issue by lianne-oy** [seattle-uat/civiform#86]

**Comment by gcapiel** [comment]
wireframes : https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354366327300&cot=14

**Comment by lianne-oy** [comment]
M1 Review - In progress

**Comment by neel-a-mehta** [comment]
#114 is the specific implementation of this.

**Comment by neel-a-mehta** [comment]
Depends on #87
