### ISSUE TITLE
Let applicants choose the language for any given program form

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#864]
While #354 specifies that applicants should be able to choose a global language across the entire app, we should let them select a language for each particular program form they're filling out. That's because each program form has its own set of supported languages, and the user's preferred language may or may not be available for that program form.

**Comment by neel-a-mehta** [comment]
This isn't going to be all that necessary IMO, since I don't think many applicants will want the website to be in language X but their program form to be in language Y. Right now, I think the behavior is to use the applicant's global language if it's available, otherwise English -- which seems like totally fine.

**Comment by AWBaumann** [comment]
Can this be closed since we allow the user to change the language from any page?

**Comment by neel-a-mehta** [comment]
@AWBaumann -- if we remove this feature, the logic would be, "use the user's chosen global language if the program form is available in that language, else use English." For instance, if the user chose French as their language and the form is offered in English, French, and Spanish, they'd get the form in French. If it's only offered in English and Vietnamese, they'd get the form in English. That logic sounds good enough to me but wanted to see if that sounds good to you too. If that sounds good, we can safely get rid of this feature as long as that logic is implemented.
