### ISSUE TITLE
Several key screens should appear before applicant jumps into body of application

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#865]
These screens are, in order:

1. Choose your language (#864)
1. Here are the documents you will need (#233)
1. Enter your phone or email address (#380)
1. If we recognize your phone or email, go log in with IDCS (already in place, I think)

**Comment by neel-a-mehta** [comment]
This mockup shows the information architecture and which screens should flow into which: https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457358402367557&cot=14

cc @bion

**Comment by kendrickt** [comment]
With #1144, since the review page can be accessed before an application is filled in, we could also use that as the jumping off point.

**Comment by lianne-oy** [comment]
Screen 1 - what you need to complete -  PR
Screen 2 - summary page  - fast follow

**Comment by AWBaumann** [comment]
Only partly done. Need to add one more screen (in progress)

**Comment by neel-a-mehta** [comment]
Preview screen appears to be in. Here's how it looks when the applicant is brand new:

![image](https://user-images.githubusercontent.com/77128518/122287960-63408d80-cea6-11eb-9c59-41f66dab0197.png)

And when you've previously submitted a form that uses some questions that are in the current form, it'll be partly filled:

![image](https://user-images.githubusercontent.com/77128518/122288089-853a1000-cea6-11eb-99b6-bbe5810039e6.png)

Then, when I click in, it shows my data pre-filled:

![image](https://user-images.githubusercontent.com/77128518/122288216-a1d64800-cea6-11eb-8d8b-c467a46b9113.png)

**Comment by neel-a-mehta** [comment]
So language choosing (#864) now happens automatically instead of being chosen by the user. Documents needed (#233) is cleverly covered by this preview. I think #380 is not useful since we can't check the applicant's email / phone against IDCS; the phone and email questions should just be asked in the body of the form.

So I think we're good here. Further comments will be in the constituent issues.
