### ISSUE TITLE
Let applicant recover account if they forgot password

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#885]
Link to this from the login page (#884).

I think IDCS already contains the code for this (but may be wrong); just need to build out the UI and possibly the email-sending mechanism

I think IDCS only lets you do 'forgot password' if you specify your username, so a workaround for us is to just email people their username and tell them to check their emails to get their username, which they can then plug into the forgot password page.

**Comment by lianne-oy** [comment]
This is part of IDCS workflow owned by the city.
