### ISSUE TITLE
Enable sitewide support for Seattle's Tier 1 Languages

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#901]
Per https://www.seattle.gov/iandraffairs/LA, there are 7 Tier 1 languages (besides English) that Seattle wants city websites to support:

> Traditional Chinese*, Spanish, Vietnamese, Somali, Amharic, Korean, Tagalog
> *There are two primary Chinese writing systems: Traditional and Simplified Chinese. The two systems are mutually intelligible. Considering the composition of Seattle's Chinese language users and their English proficiency, we recommend translating into Traditional Chinese for written materials. For oral interpretation, we should include both Cantonese and Mandarin.

Ensure that our site-wide language selector offers all of these options. If we have time, we can start adding the Tier 2 and Tier 3 languages.

**Comment by carolinedanzi** [comment]
The Tier 1 languages are now supported, though we don't have translations for the app text yet. But an applicant can select their preferred Tier 1 language from the dropdown

**Comment by neel-a-mehta** [comment]
#921 covers actually implementing the translations. For now, any string that lacks a translation in the user's chosen language will fall back to English. However, the infrastructure is there, so we can close this issue.
