### ISSUE TITLE
Draft program's "last updated" date appears stale on Versions page

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#907]
Some recent [testing of the Versioning page](https://github.com/seattle-uat/civiform/issues/759#issuecomment-828751117) found that the Draft version's "Last Updated" time is never updated -- it's always set to the Active version's "Last Updated" time, even if changes are made to the draft. 

We should change that behavior so the Draft version displays the date/time that the last questions or programs were edited.

**Comment by shanemc-goog** [comment]
Related to #1657
