### ISSUE TITLE
Program admins can see a filterable, paginated list of applications their program has received

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#940]
As specified [in this doc](https://docs.google.com/document/d/1xruNGvnI5FuvmoibzUujPvcIXkRGi7Kx1gSx6IpAd8Y/edit?usp=sharing), program admins should be able to see a list of all applications to their programs in a two-pane view. They should be able to filter viewable programs using a few filters specified in the doc. In addition, they should only see a limited number of applications on one page (50?) and have to click to other pages to see the rest. This will be become important as the admins get 1000s of applications.

**Comment by ndmckinley** [comment]
That doc doesn't specify a two-pane view.  Do you see that as mandatory?

**Comment by bion** [comment]
LGTM
