### ISSUE TITLE
Enable sorting programs in the Civiform / Program Admin's list of programs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#941]
Once you get 20 or so programs in your CiviForm instance, it can get annoying to find the one you're looking for in the huge list. To remedy this, we can enable sorting the list of programs by:

- Alphabetical
- Last modified
- Number of applications

And possibly others.

**Comment by kristinyim** [comment]
Similar to #1238 and will be tackled together thus closing
