### ISSUE TITLE
IDCS should not show Public Utilities & Permissions pages when you log in

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#967]
When you sign up for an SPU utilities account on the Seattle website, you don't see this page at all. But for CiviForm, you do see this page. Ideally we'd configure the app such that we don't have to show this screen to new users.

![image](https://user-images.githubusercontent.com/77128518/117047133-82f96900-acdf-11eb-8845-481be808f868.png)

**Comment by neel-a-mehta** [comment]
We should also get rid of this page, which is the one that leads into the "allow" screen.

![Uploading image.png…]()

**Comment by neel-a-mehta** [comment]
... Also, when you register for an account, you're dropped on the Public Utilities website, which probably will confuse users. We should find a way to redirect users back to the CiviForm login page, probably.

**Comment by neel-a-mehta** [comment]
Here's the exact workflow:

- I register at login.seattle.gov
- I have to choose "Seattle Public Utilities" before my account can be confirmed (the screenshot above)
- I log in with my username and password
- I get dropped on https://myutilities.seattle.gov/eportal/#/accountlookup/default (the Public Utilities site I saw earlier)

**Comment by bion** [comment]
Tracking this here: https://github.com/seattle-uat/civiform/issues/1585
