### ISSUE TITLE
Let Civiform admins add eligibility rules to their programs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#970]
Before applicants apply for a program, they will want to know if they are eligible for the program in the first place. Program admins will also want to ensure that applicants who aren't eligible don't apply.

To do this, we need to:

- Create an engine where CiviForm Admins can specify eligibility rules (#1450)
- Build a UI to build these rules (#973)
- Surface eligibility rules to applicants (#1449)
- Implement a way for applicants to enter their data and check if they are applicable; if they are not applicable, exit the form immediately (#617)

**Comment by elisekalstad** [comment]
@bion -- I see this was closed, any reason? Or can I reopen?

**Comment by bion** [comment]
@elisekalstad closed as a duplicate of https://github.com/seattle-uat/civiform/issues/1738 and https://github.com/seattle-uat/civiform/issues/973
