### ISSUE TITLE
Let Civiform admins delete/archive questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#997]
Right now there's no way to get rid of a question once it's created. Add a way to get rid of a question, or at least archive it. May want to add a prerequisite that the question is no longer used in any forms, since getting rid of a question that *is* used in forms may cause some havoc.

**Comment by lianne-oy** [comment]
Will be done today

**Comment by neel-a-mehta** [comment]
Testing:

- Go to staging site and log in as global Civiform admin
- Go to question bank from top bar
- Appears that some questions can be archived, but some can't -- why?

![image](https://user-images.githubusercontent.com/77128518/121227013-226ac800-c859-11eb-8d47-2583dd0d2789.png)

- Archiving one question
- I see the button now says "Restore Archived"
- Click that button => question is back to normal.

Looks like this works, although there are some usability questions that will get separate issues (prob for icebox).

**Comment by ndmckinley** [comment]
Questions that are in use cannot be archived.
